<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Matthew J. C. Crump">

<title>7&nbsp; Pruebas t – Respondiendo preguntas con datos</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06b-chi_cuadrado.html" rel="next">
<link href="./05-Foundation_Inference.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-1116FZ99DZ"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-1116FZ99DZ', { 'anonymize_ip': true});
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="7&nbsp; Pruebas t – Respondiendo preguntas con datos">
<meta property="og:description" content="">
<meta property="og:site_name" content="Respondiendo preguntas con datos">
<meta name="twitter:title" content="7&nbsp; Pruebas t – Respondiendo preguntas con datos">
<meta name="twitter:description" content="A free textbook teaching introductory statistics for undergraduates in psychology, including a lab manual, and course website. Licensed on CC BY SA 4.0">
<meta name="twitter:image" content="https://almadana.github.io/libro_cuanti/imgs/TextbookCover.png">
<meta name="twitter:site" content="@MattCrumpLab">
<meta name="twitter:card" content="summary">
<meta name="twitter:image-height" content="1310">
<meta name="twitter:image-width" content="916">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./06-ttests.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Pruebas t</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Respondiendo preguntas con datos</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/almadana/libro_cuanti/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Science_Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">¿Por qué estadística?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Describing_Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describir los datos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02b-tablas_final.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Tablas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Correlación</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-SamplesPopulations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Probabilidad, muestreo y estimación</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Foundation_Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Fundamentos de la inferencia</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-ttests.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Pruebas t</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06b-chi_cuadrado.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Pruebas chi cuadrado</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-RMANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Repeated Measures ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-FactorialANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-MixedANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">More On Factorial Designs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-Simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Simulating Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-Thinking.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Thinking about answering questions with data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-Gifs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">GIFs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#revisá-tu-confianza-en-el-promedio" id="toc-revisá-tu-confianza-en-el-promedio" class="nav-link active" data-scroll-target="#revisá-tu-confianza-en-el-promedio"><span class="header-section-number">7.1</span> Revisá tu confianza en el promedio</a></li>
  <li><a href="#prueba-t-de-una-muestra-una-nueva-prueba-t" id="toc-prueba-t-de-una-muestra-una-nueva-prueba-t" class="nav-link" data-scroll-target="#prueba-t-de-una-muestra-una-nueva-prueba-t"><span class="header-section-number">7.2</span> Prueba t de una muestra: una nueva prueba t</a>
  <ul class="collapse">
  <li><a href="#fórmulas-de-la-prueba-t-de-una-muestra" id="toc-fórmulas-de-la-prueba-t-de-una-muestra" class="nav-link" data-scroll-target="#fórmulas-de-la-prueba-t-de-una-muestra"><span class="header-section-number">7.2.1</span> Fórmulas de la prueba t de una muestra</a></li>
  <li><a href="#qué-representa-t" id="toc-qué-representa-t" class="nav-link" data-scroll-target="#qué-representa-t"><span class="header-section-number">7.2.2</span> ¿Qué representa t?</a></li>
  <li><a href="#calcular-t-a-partir-de-datos" id="toc-calcular-t-a-partir-de-datos" class="nav-link" data-scroll-target="#calcular-t-a-partir-de-datos"><span class="header-section-number">7.2.3</span> Calcular t a partir de datos</a></li>
  <li><a href="#cómo-se-comporta-t" id="toc-cómo-se-comporta-t" class="nav-link" data-scroll-target="#cómo-se-comporta-t"><span class="header-section-number">7.2.4</span> ¿Cómo se comporta t?</a></li>
  <li><a href="#tomando-una-decisión" id="toc-tomando-una-decisión" class="nav-link" data-scroll-target="#tomando-una-decisión"><span class="header-section-number">7.2.5</span> Tomando una decisión</a></li>
  </ul></li>
  <li><a href="#prueba-t-de-muestras-pareadas" id="toc-prueba-t-de-muestras-pareadas" class="nav-link" data-scroll-target="#prueba-t-de-muestras-pareadas"><span class="header-section-number">7.3</span> Prueba t de muestras pareadas</a>
  <ul class="collapse">
  <li><a href="#mehr-song-y-spelke-2016" id="toc-mehr-song-y-spelke-2016" class="nav-link" data-scroll-target="#mehr-song-y-spelke-2016"><span class="header-section-number">7.3.1</span> Mehr, Song y Spelke (2016)</a></li>
  <li><a href="#los-datos" id="toc-los-datos" class="nav-link" data-scroll-target="#los-datos"><span class="header-section-number">7.3.2</span> Los datos</a></li>
  <li><a href="#los-puntajes-de-diferencia" id="toc-los-puntajes-de-diferencia" class="nav-link" data-scroll-target="#los-puntajes-de-diferencia"><span class="header-section-number">7.3.3</span> Los puntajes de diferencia</a></li>
  <li><a href="#la-diferencia-media" id="toc-la-diferencia-media" class="nav-link" data-scroll-target="#la-diferencia-media"><span class="header-section-number">7.3.4</span> La diferencia media</a></li>
  <li><a href="#calcular-t" id="toc-calcular-t" class="nav-link" data-scroll-target="#calcular-t"><span class="header-section-number">7.3.5</span> Calcular <em>t</em></a></li>
  <li><a href="#interpretar-valores-t" id="toc-interpretar-valores-t" class="nav-link" data-scroll-target="#interpretar-valores-t"><span class="header-section-number">7.3.6</span> Interpretar valores <em>t</em></a></li>
  <li><a href="#obtener-valores-p-para-valores-t" id="toc-obtener-valores-p-para-valores-t" class="nav-link" data-scroll-target="#obtener-valores-p-para-valores-t"><span class="header-section-number">7.3.7</span> Obtener valores <em>p</em> para valores <em>t</em></a></li>
  <li><a href="#test-unilateral-de-una-cola-o-one-tailed-en-inglés" id="toc-test-unilateral-de-una-cola-o-one-tailed-en-inglés" class="nav-link" data-scroll-target="#test-unilateral-de-una-cola-o-one-tailed-en-inglés"><span class="header-section-number">7.3.8</span> Test unilateral (de una cola, o one-tailed en inglés)</a></li>
  <li><a href="#test-bilateral-de-dos-cola-o-two-tailed-en-inglés" id="toc-test-bilateral-de-dos-cola-o-two-tailed-en-inglés" class="nav-link" data-scroll-target="#test-bilateral-de-dos-cola-o-two-tailed-en-inglés"><span class="header-section-number">7.3.9</span> Test bilateral (de dos cola, o two-tailed en inglés)</a></li>
  <li><a href="#test-unilateral-o-bilateral" id="toc-test-unilateral-o-bilateral" class="nav-link" data-scroll-target="#test-unilateral-o-bilateral"><span class="header-section-number">7.3.10</span> ¿Test unilateral o bilateral?</a></li>
  <li><a href="#grados-de-libertad" id="toc-grados-de-libertad" class="nav-link" data-scroll-target="#grados-de-libertad"><span class="header-section-number">7.3.11</span> Grados de libertad</a></li>
  </ul></li>
  <li><a href="#la-prueba-t-de-muestras-pareadas-contraataca" id="toc-la-prueba-t-de-muestras-pareadas-contraataca" class="nav-link" data-scroll-target="#la-prueba-t-de-muestras-pareadas-contraataca"><span class="header-section-number">7.4</span> La prueba t de muestras pareadas contraataca</a></li>
  <li><a href="#prueba-t-de-muestras-independientes-el-regreso-d-la-prueba-t" id="toc-prueba-t-de-muestras-independientes-el-regreso-d-la-prueba-t" class="nav-link" data-scroll-target="#prueba-t-de-muestras-independientes-el-regreso-d-la-prueba-t"><span class="header-section-number">7.5</span> Prueba t de muestras independientes: ¿el regreso d la prueba t?</a></li>
  <li><a href="#simulando-datos-para-tests-t" id="toc-simulando-datos-para-tests-t" class="nav-link" data-scroll-target="#simulando-datos-para-tests-t"><span class="header-section-number">7.6</span> Simulando datos para tests <span class="math inline">\(t\)</span></a>
  <ul class="collapse">
  <li><a href="#simular-una-prueba-t-de-una-muestra" id="toc-simular-una-prueba-t-de-una-muestra" class="nav-link" data-scroll-target="#simular-una-prueba-t-de-una-muestra"><span class="header-section-number">7.6.1</span> Simular una prueba t de una muestra</a></li>
  <li><a href="#simular-una-prueba-t-de-muestras-pareadas" id="toc-simular-una-prueba-t-de-muestras-pareadas" class="nav-link" data-scroll-target="#simular-una-prueba-t-de-muestras-pareadas"><span class="header-section-number">7.6.2</span> Simular una prueba t de muestras pareadas</a></li>
  <li><a href="#simular-una-prueba-t-de-muestras-independientes" id="toc-simular-una-prueba-t-de-muestras-independientes" class="nav-link" data-scroll-target="#simular-una-prueba-t-de-muestras-independientes"><span class="header-section-number">7.6.3</span> Simular una prueba t de muestras independientes</a></li>
  </ul></li>
  <li><a href="#videos" id="toc-videos" class="nav-link" data-scroll-target="#videos"><span class="header-section-number">7.7</span> Videos</a>
  <ul class="collapse">
  <li><a href="#test-de-una-o-dos-colas" id="toc-test-de-una-o-dos-colas" class="nav-link" data-scroll-target="#test-de-una-o-dos-colas"><span class="header-section-number">7.7.1</span> Test de una o dos colas</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/almadana/libro_cuanti/edit/master/06-ttests.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Pruebas t</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Matthew J. C. Crump </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<p>Volvamos atrás en el tiempo. William Sealy Gosset consiguió trabajo en la cervecería Guinness. Sí, la que hace la famosa stout irlandesa. Lo que pasó después fue más o menos así (lo estoy inventando, pero la idea general es cierta).</p>
<p>Guinness quería que todas sus cervezas fueran las mejores. Nada de errores, nada de birra mala. Querían mejorar el control de calidad para que, sin importar en qué parte del mundo sirvieras una Guinness, siempre saliera perfecta: 5 estrellas sobre 5, siempre.</p>
<p>Tenían catadores expertos. Cada vez que probaban una Guinness que no era 5 de 5, lo notaban al instante.</p>
<p>Pero había un gran problema. Hacían un barril de cerveza, y querían saber si <strong>cada pinta</strong> que saliera de ahí iba a ser perfecta. Así que los catadores se tomaban pinta tras pinta del barril… hasta que se acababa. Algunos barriles salían bien, otros no. Guinness tenía que arreglar eso. Pero el mayor problema era que, después del testeo, <strong>no quedaba cerveza para vender</strong> —se la habían tomado toda (recordá que esta parte me la estoy inventando para ilustrar el punto; seguro algo les quedaba para vender).</p>
<p>Guinness tenía un problema de población y muestreo. Querían saber si toda la población de cervezas producidas era de 5 estrellas. Pero si probaban toda la población, no les quedaba nada para vender.</p>
<p>Ahí entra William Sealy Gosset. Gosset resolvió el problema. Se hizo preguntas como:</p>
<ol type="1">
<li><p>¿Cuántas muestras necesito tomar para saber si toda la población es de 5 sobre 5?</p></li>
<li><p>¿Cuál es la menor cantidad de muestras que puedo tomar para saber eso, de forma que Guinness pueda testear menos cervezas, vender más, y acortar el tiempo de control de calidad?</p></li>
</ol>
<p>Gosset resolvió esas preguntas e inventó algo llamado la <em>prueba t de Student</em>. Como trabajaba para Guinness, podía ser despedido si divulgaba secretos comerciales (como la prueba t). Pero igual publicó su trabajo, bajo un seudónimo <span class="citation" data-cites="Student1908">(<a href="references.html#ref-Student1908" role="doc-biblioref">Student 1908</a>)</span>. Se hizo llamar “Student”, y por eso el test se llama <em>prueba t de Student</em>. Ahora ya sabés el resto de la historia.</p>
<p>Y resultó ser algo muy útil. La prueba t se usa todo el tiempo. Y se usa porque sirve. En este capítulo vamos a ver cómo funciona.</p>
<p>Te va a sorprender saber que lo que ya vimos antes (el test de Crump, el test de aleatorización) es muy parecido a la prueba t. Así que ya venís pensando en lo necesario para entender las pruebas t. Seguramente te estás preguntando qué es eso de <span class="math inline">\(t\)</span>, qué significa. Ya vamos a contarte. Pero antes, una idea más.</p>
<section id="revisá-tu-confianza-en-el-promedio" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="revisá-tu-confianza-en-el-promedio"><span class="header-section-number">7.1</span> Revisá tu confianza en el promedio</h2>
<p>Ya hablamos de tomar una muestra de datos. Sabemos cómo calcular la media, la desviación estándar, y cómo ver los datos en un histograma. Todo eso nos ayuda a entender mejor nuestras muestras.</p>
<p>Capaz pensás que la media y la desviación estándar son cosas muy distintas, que no deberían combinarse. La media te dice dónde están la mayoría de los datos, y la desviación estándar cuánto varían. Sí, son distintas. Pero combinarlas puede darnos información útil.</p>
<p>Si te digo que mi media muestral es 50, y no te digo nada más, ¿cuán confiado estás de que los números están cerca de 50? ¿Te preguntás si hay mucha variabilidad, si algunos valores están lejos? Deberías preguntártelo. La media sola no dice cuánto representa al resto de los datos.</p>
<p>Puede ser representativa, si la desviación estándar es chica. O no, si la desviación es grande. Para confiar en la media, necesitás saber cuánta variabilidad hay.</p>
<p>¿Cómo combinamos media y desviación para obtener una medida de confianza?</p>
<p>Podemos usar un cociente:</p>
<p><span class="math display">\[\frac{\text{media}}{\text{desviación estándar}}\]</span></p>
<p>Veamos qué pasa:</p>
<p><span class="math display">\[\frac{\text{número}}{\text{mismo número}} = 1\]</span></p>
<p><span class="math display">\[\frac{\text{número}}{\text{número chico}} = \text{número grande}\]</span></p>
<p><span class="math display">\[\frac{\text{número}}{\text{número grande}} = \text{número chico}\]</span></p>
<p>Si la media es 50 y la desviación es 1:</p>
<p><span class="math display">\[\frac{50}{1} = 50\]</span></p>
<p>Si la desviación es 100:</p>
<p><span class="math display">\[\frac{50}{100} = 0.5\]</span></p>
<p>Cuando la desviación es baja, el cociente es grande: más confianza. Si la desviación es alta, el cociente es chico: menos confianza. Así que esta proporción nos da una idea de cuán confiable es la media.</p>
<p>En resumen: creamos una estadística descriptiva dividiendo la media por la desviación estándar. Y tenemos una forma de interpretarla. Si el resultado es grande, la media representa bien a los datos. Si es chico, no tanto. Este tipo de razón es clave en estadística: compara lo que sabemos con lo que no sabemos.</p>
<p>Casi todo lo que viene en este libro se basa en esta lógica. Las fórmulas siguen este esquema:</p>
<p><span class="math display">\[\text{estadístico} = \frac{\text{medida de lo que sabemos}}{\text{medida de lo que no sabemos}}\]</span></p>
<p>o también:</p>
<p><span class="math display">\[\text{estadístico} = \frac{\text{efecto}}{\text{error}}\]</span></p>
<p>Y esta es, justamente, la fórmula general de la prueba t. ¡Sorpresa!</p>
</section>
<section id="prueba-t-de-una-muestra-una-nueva-prueba-t" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="prueba-t-de-una-muestra-una-nueva-prueba-t"><span class="header-section-number">7.2</span> Prueba t de una muestra: una nueva prueba t</h2>
<p>Ahora sí, hablemos de las pruebas t. Vamos a ver tres tipos. Empezamos con la prueba t de una muestra.</p>
<p>Este test se usa para estimar la probabilidad de que tu muestra venga de una población específica. En particular, querés saber si la media de tu muestra podría venir de una población con cierta media.</p>
<p>Acá empieza lo confuso (y todavía no te dije la fórmula). En teoría, la prueba t usa parámetros conocidos de la población, como su media y su desviación. Pero en la práctica, casi nunca conocés esos valores. Así que tenés que estimarlos a partir de la muestra.</p>
<p>Recordá lo que vimos sobre estadística descriptiva y muestreo: la media muestral es un estimador insesgado de la media poblacional. Y la desviación muestral (la que divide por n–1) también lo es. Gosset se dio cuenta de que podía usar estas estimaciones para construir la prueba t.</p>
<p>Acá va la fórmula, primero en palabras:</p>
<section id="fórmulas-de-la-prueba-t-de-una-muestra" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="fórmulas-de-la-prueba-t-de-una-muestra"><span class="header-section-number">7.2.1</span> Fórmulas de la prueba t de una muestra</h3>
<p><span class="math display">\[\text{estadístico} = \frac{\text{efecto}}{\text{error}}\]</span></p>
<p><span class="math display">\[t = \frac{\text{efecto}}{\text{error}}\]</span></p>
<p><span class="math display">\[t = \frac{\text{diferencia de medias}}{\text{error estándar}}\]</span></p>
<p><span class="math display">\[t = \frac{\bar{X}-\mu}{S_{\bar{X}}}\]</span></p>
<p><span class="math display">\[t = \frac{\text{Media muestral - Media poblacional}}{\text{Error estándar muestral}}\]</span></p>
<p><span class="math display">\[\text{Error estándar estimado} = \text{Error estándar de la muestra} = \frac{s}{\sqrt{N}}\]</span></p>
<p>donde <em>s</em> es la desviación estándar de la muestra.</p>
<p>Capaz que todo esto te hizo bizquear un poco. Tranquilo, ya lo vimos antes, cuando dividimos la media por la desviación estándar. La prueba t no es más que la media muestral dividida por el error estándar de esa media. Eso es todo.</p>
</section>
<section id="qué-representa-t" class="level3" data-number="7.2.2">
<h3 data-number="7.2.2" class="anchored" data-anchor-id="qué-representa-t"><span class="header-section-number">7.2.2</span> ¿Qué representa t?</h3>
<p><span class="math inline">\(t\)</span> nos da una medida de confianza, igual que la relación (ratio) anterior en la que dividíamos la media por la desviación estándar. La única diferencia es que ahora dividimos por el <strong>error estándar de la media</strong> (que, recordá, también es una desviación estándar: la de la distribución muestral de la media).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>¿La <em>t</em> en <em>prueba t</em> significa algo? Aparentemente no. Gosset originalmente usó <em>z</em>. Y después Fisher lo llamó <em>t</em>, tal vez porque viene después de <em>s</em>, que suele usarse para la desviación estándar muestral.</p>
</div>
</div>
<p><span class="math inline">\(t\)</span> es una propiedad de los datos que recolectás. Se calcula con la media de la muestra y su error estándar (y también con la media poblacional, a la que llegamos enseguida). Por eso se dice que <em>t</em> es una estadística muestral: se calcula a partir de la muestra. ¿Qué valores deberíamos esperar obtener para esos <em>t</em>? ¿Cómo podríamos saberlo?</p>
<p>Empecemos con un ejemplo simple. Imaginá que tu media muestral es 5, y querés saber si viene de una población con media 5. ¿Cuál sería el valor de <em>t</em>? Cero: restamos 5 - 5 = 0. Como el numerador es 0, <em>t</em> también lo es. Así que <em>t</em> = 0 ocurre cuando <strong>no hay diferencia</strong>. Ahora tomás otra muestra. ¿La media será siempre 5? Probablemente no. Supongamos que da 6. ¿Qué valor tendrá <em>t</em>? El numerador es positivo: 6 - 5 = +1. Pero <em>t</em> no necesariamente será 1, eso depende del error estándar. Si es 1, entonces <em>t</em> será 1, porque 1/1 = 1. Si el error estándar es menor que 1, ¿qué pasa con <em>t</em>? Aumenta. Por ejemplo, 1 dividido por 0.5 da 2. Si el error estándar fuera 0.5, entonces <em>t</em> sería 2. Y con ese valor podríamos tener más confianza en que la diferencia que observamos no es casual.</p>
<p>¿Puede <em>t</em> ser menor que 1? Claro. Si el error estándar es grande, digamos 2, entonces <em>t</em> será más chico que 1 (en nuestro caso, 1/2 = 0.5). La dirección de la diferencia entre la media muestral y la poblacional también puede hacer que <em>t</em> sea negativo. Si la media muestral fuera 4, entonces la diferencia es negativa, y <em>t</em> también lo será, porque el numerador es negativo. El denominador (el error estándar) siempre será positivo (acordate por qué: se calcula a partir de la desviación estándar de la muestra, que siempre es positiva porque usamos cuadrados al calcularla).</p>
<p>Así que estas son algunas intuiciones sobre los valores posibles de <em>t</em>. Puede ser positivo o negativo, grande o chico.</p>
<p>Hagamos una cosa más para afinar la intuición. ¿Qué tal si generamos varias muestras, calculamos la media muestral <strong>y</strong> el error estándar de la media, y graficamos esas dos cosas entre sí? Así vamos a ver cómo varía típicamente la media con respecto al error estándar.</p>
<p>En la <a href="#fig-6muestraMSEM" class="quarto-xref">Figure&nbsp;<span>7.1</span></a>, tomé 1.000 muestras de tamaño N = 10 de una distribución normal (media = 0, desviación estándar = 1). En cada caso, calculé la media y el error estándar. Eso nos da dos estadísticas descriptivas por muestra, y podemos graficarlas como puntos en un diagrama de dispersión.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6muestraMSEM" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6muestraMSEM-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6muestraMSEM-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6muestraMSEM-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.1: Diagrama de dispersión con la media muestral en el eje x y el error estándar en el eje y
</figcaption>
</figure>
</div>
</div>
</div>
<p>Lo que obtenemos es una nube de puntos. Podés notar que tiene una forma más o menos circular. Hay más puntos en el centro, y menos a medida que se alejan. La nube muestra el rango típico de las medias muestrales: la mayoría está entre -1 y 1. El error estándar también varía entre aproximadamente 0.2 y 0.5. Recordá que cada punto representa una muestra.</p>
<p>Podemos ver estos datos de otra forma. En lugar de graficar directamente las medias y errores, podemos dividir la media de cada muestra por su error estándar. La <a href="#fig-6thisexample" class="quarto-xref">Figure&nbsp;<span>7.2</span></a> muestra un histograma de esos valores.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6thisexample" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6thisexample-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6thisexample-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6thisexample-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.2: Histograma de las medias muestrales divididas por sus errores estándar: una distribución t.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Interesante, el histograma tiene forma de curva normal. Está centrado en 0, que es el valor más común. A medida que los valores se alejan de 0, son menos frecuentes. Si recordás, nuestra fórmula para <em>t</em> era la media dividida por el error estándar. Eso es exactamente lo que hicimos acá. Este histograma te está mostrando una <strong>distribución t</strong>.</p>
</section>
<section id="calcular-t-a-partir-de-datos" class="level3" data-number="7.2.3">
<h3 data-number="7.2.3" class="anchored" data-anchor-id="calcular-t-a-partir-de-datos"><span class="header-section-number">7.2.3</span> Calcular t a partir de datos</h3>
<p>Probemos calcular un valor de <em>t</em> con una muestra chica. Supongamos que 10 estudiantes hicieron un test de verdadero/falso con 5 preguntas. Hay un 50% de chance de acertar cada una al azar.</p>
<p>Todos completan el test, corregimos, y calculamos el desempeño (porcentaje de respuestas correctas). Queremos saber si estuvieron adivinando. Si fue así, el promedio debería rondar el 50%, que sería igual a azar. Veamos la <a href="#tbl-tsmall" class="quarto-xref">Table&nbsp;<span>7.1</span></a>.</p>
<div class="cell">
<div id="tbl-tsmall" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tsmall-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7.1: Cálculo del valor t para un test de una muestra.
</figcaption>
<div aria-describedby="tbl-tsmall-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 16%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 31%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">estudiantes</th>
<th style="text-align: left;">puntajes</th>
<th style="text-align: left;">promedio</th>
<th style="text-align: left;">Diferencia_de_la_media</th>
<th style="text-align: left;">Desvíos_al_cuadrado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">61</td>
<td style="text-align: left;">-11</td>
<td style="text-align: left;">121</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">70</td>
<td style="text-align: left;">61</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">81</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">60</td>
<td style="text-align: left;">61</td>
<td style="text-align: left;">-1</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">40</td>
<td style="text-align: left;">61</td>
<td style="text-align: left;">-21</td>
<td style="text-align: left;">441</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">80</td>
<td style="text-align: left;">61</td>
<td style="text-align: left;">19</td>
<td style="text-align: left;">361</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">30</td>
<td style="text-align: left;">61</td>
<td style="text-align: left;">-31</td>
<td style="text-align: left;">961</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">90</td>
<td style="text-align: left;">61</td>
<td style="text-align: left;">29</td>
<td style="text-align: left;">841</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">60</td>
<td style="text-align: left;">61</td>
<td style="text-align: left;">-1</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;">70</td>
<td style="text-align: left;">61</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">81</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">60</td>
<td style="text-align: left;">61</td>
<td style="text-align: left;">-1</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sumas</td>
<td style="text-align: left;">610</td>
<td style="text-align: left;">610</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">2890</td>
</tr>
<tr class="even">
<td style="text-align: left;">Medias</td>
<td style="text-align: left;">61</td>
<td style="text-align: left;">61</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">289</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">DE</td>
<td style="text-align: left;">17.92</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">EEM</td>
<td style="text-align: left;">5.67</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">t</td>
<td style="text-align: left;">1.94003527336861</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Podés ver que la columna <code>puntajes</code> tiene los puntajes de cada uno de los 10 estudiantes. Hicimos todo lo necesario para calcular la desviación estándar. Recordá que la desviación estándar muestral es la raíz cuadrada de la varianza muestral, o sea:</p>
<p><span class="math inline">\(\text{desviación estándar} = \sqrt{\frac{\sum_{i}^{n}({x_{i}-\bar{x})^2}}{N-1}}\)</span></p>
<p><span class="math inline">\(DE = \sqrt{\frac{2890}{10-1}} = 17.92\)</span></p>
<p>El error estándar de la media se obtiene dividiendo la desviación estándar por la raíz de N:</p>
<p><span class="math inline">\(EEM = \frac{s}{\sqrt{N}} = \frac{17.92}{10} = 5.67\)</span></p>
<p><em>t</em> es la diferencia entre nuestra media muestral (61) y la media poblacional (50, si asumimos azar), dividida por el error estándar:</p>
<p><span class="math inline">\(t = \frac{\bar{X}-\mu}{S_{\bar{X}}} = \frac{61-50}{5.67} = 1.94\)</span></p>
<p>Y así se calcula <em>t</em> a mano. Es un embole. A mí ya me molestó hacerlo así. En el laboratorio vas a aprender a calcular <em>t</em> con software, que te lo da de una. Por ejemplo, en R solo tenés que escribir:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(puntajes, <span class="at">mu=</span><span class="dv">50</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  One Sample t-test</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; data:  puntajes</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; t = 1.9412, df = 9, p-value = 0.08415</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; alternative hypothesis: true mean is not equal to 50</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 95 percent confidence interval:</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  48.18111 73.81889</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; sample estimates:</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; mean of x </span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;        61</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="cómo-se-comporta-t" class="level3" data-number="7.2.4">
<h3 data-number="7.2.4" class="anchored" data-anchor-id="cómo-se-comporta-t"><span class="header-section-number">7.2.4</span> ¿Cómo se comporta t?</h3>
<p>Si <em>t</em> es solo un número que podemos calcular a partir de una muestra (y lo es), ¿qué hacemos con él? ¿Cómo usamos <em>t</em> para inferencia estadística?</p>
<p>Volvamos al capítulo sobre muestreo y distribuciones. Ahí hablamos de la distribución muestral de la media. Generamos muchas muestras, calculamos la media de cada una, y armamos un histograma de esas medias. Más adelante dijimos que podíamos hacer eso con <strong>cualquier</strong> estadístico. Para cada muestra podíamos calcular la media, la desviación estándar, el error estándar, e incluso <em>t</em>. Podríamos generar 10.000 muestras y hacer cuatro histogramas, uno para cada distribución muestral de cada estadístico. Eso fue exactamente lo que hice, y los resultados están en los cuatro paneles de la <a href="#fig-6sampdists" class="quarto-xref">Figure&nbsp;<span>7.3</span></a>. Usé un tamaño de muestra de 20, y tomé observaciones aleatorias de una distribución normal, con media = 0, y la desviación estándar = 1. Veamos las distribuciones muestrales de cada estadístico. <em>t</em> se calculó asumiendo que la media poblacional es 0.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6sampdists" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6sampdists-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6sampdists-1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6sampdists-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.3: Distribuciones muestrales de la media, la desviación estándar, el error estándar de la media, y <span class="math inline">\(t\)</span>.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Vemos cuatro distribuciones muestrales. Así es como se comportan los resúmenes estadísticos de muestras. Antes hablamos de <em>ventanas de azar</em> —estas son cuatro ventanas de azar, que miden distintos aspectos de una muestra. En este caso, todas las muestras provienen de la misma distribución normal. Pero por el error muestral, cada muestra es diferente. Las medias no son idénticas, las desviaciones tampoco, los errores estándar tampoco, y los valores de <em>t</em> tampoco. Todas varían, como muestran los histogramas. Así se comportan las muestras de tamaño 20.</p>
<p>Podemos ver de entrada que es poco probable obtener una media muestral de 2. Está muy fuera del rango típico. La distribución de las medias va más o menos de -0.5 a +0.5, y está centrada en 0 (¡justo la media poblacional, mirá vos!).</p>
<p>También es poco probable obtener desviaciones estándar fuera de 0.6 y 1.5; ese es el rango típico específico para la desviación estándar muestral.</p>
<p>Lo mismo pasa con el error estándar de la media: el rango es más chico, entre 0.1 y 0.3. Rara vez vas a encontrar una muestra con error estándar mayor a 0.3. Prácticamente nunca uno de 1 (en esta situación).</p>
<p>Y ahora mirá los valores de <em>t</em>. El rango va más o menos de -3 a +3. Los valores 3 apenas aparecen. Casi nunca vas a ver un 5 o un -5 acá.</p>
<p>Todas estas <em>ventanas de azar</em> se pueden usar como usamos las distribuciones muestrales antes (por ejemplo, en el test de Crump o el test de aleatorización), para hacer inferencias estadísticas. El proceso es el mismo para todas:</p>
<ol type="1">
<li>Generar estas distribuciones</li>
<li>Mirar tus estadísticos muestrales (media, SD, SEM, y <em>t</em>)</li>
<li>Calcular la probabilidad de obtener ese valor de <em>t</em> o uno más extremo</li>
<li>Obtener esa probabilidad</li>
<li>Evaluar si tus estadísticas muestrales parecen probables o improbables</li>
</ol>
<p>Enseguida vamos a formalizar todo esto. Por ahora, quiero que veas que esto que vas a hacer es algo que <strong>ya hiciste antes</strong>. Por ejemplo, en el test de Crump y el test de aleatorización, nos enfocamos en la distribución de diferencias de medias. Podríamos hacer lo mismo acá, pero esta vez nos vamos a centrar en la distribución de valores <em>t</em>. Después aplicamos las mismas reglas de decisión que usamos con las otras distribuciones.</p>
<p>Abajo vas a ver un gráfico que ya viste antes, pero ahora muestra una distribución de <em>t</em>, no de diferencias de medias. Recordá: si obtenemos un único valor <em>t</em> a partir de una muestra que recolectamos, podemos consultar la <em>ventana de azar</em> en <a href="#fig-6tdecision" class="quarto-xref">Figure&nbsp;<span>7.4</span></a> para ver si ese valor era esperable por azar o no.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6tdecision" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6tdecision-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6tdecision-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6tdecision-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.4: Aplicación de criterios de decisión a la distribución t. Histograma de valores t de muestras (n = 20) tomadas de una misma distribución normal (μ = 0, sd = 1)
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="tomando-una-decisión" class="level3" data-number="7.2.5">
<h3 data-number="7.2.5" class="anchored" data-anchor-id="tomando-una-decisión"><span class="header-section-number">7.2.5</span> Tomando una decisión</h3>
<p>Volvamos a nuestro ejemplo del test de verdadero/falso. Ahora podemos tomar una decisión sobre qué pasó ahí. Encontramos una diferencia de medias de 11. El valor de <em>t</em> fue 1.9411765. La probabilidad de obtener ese valor de <em>t</em> o uno más extremo es <span class="math inline">\(p\)</span> = 0.0841503.</p>
<p>Estábamos probando si nuestra media muestral de 61 podría venir de una distribución normal con media = 50. El test <em>t</em> nos dice que obtener ese <em>t</em>, o uno más grande, pasaría con probabilidad <span class="math inline">\(p\)</span> = 0.0841503. En otras palabras, el azar puede lograrlo, pero no muy seguido. En criollo: todos los estudiantes podrían haber estado adivinando… pero <strong>no es muy probable</strong> que haya sido solo eso.</p>
<p>La próxima prueba-<em>t</em> se llama <strong>prueba t de muestras pareadas</strong>. Y, spoiler: vamos a descubrir que en realidad es un <strong>prueba t de una muestra disfrazado</strong> (¡¿QUÉ?!). Sí. Si no entendiste el de una muestra, seguí leyendo.</p>
</section>
</section>
<section id="prueba-t-de-muestras-pareadas" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="prueba-t-de-muestras-pareadas"><span class="header-section-number">7.3</span> Prueba t de muestras pareadas</h2>
<p>Para mí (Crump), muchos análisis terminan siendo una prueba t de muestras pareadas. Simplemente porque muchas de las cosas que hago se reducen a eso.</p>
<p>Soy psicólogo cognitivo. Hago investigación sobre cómo la gente recuerda, presta atención y aprende habilidades. Hay muchos psicólogos como yo que hacen cosas parecidas. Hacemos experimentos muy similares. Son lo que se llama diseños de <strong>medidas repetidas</strong>. Se llaman así porque medimos cómo una persona hace algo más de una vez. Repetimos la medición. Por ejemplo, puedo medir cómo alguien realiza una tarea en la condición A, y luego ver cómo esa misma persona la hace en la condición B. Y veo que hace cosas distintas. Estoy <strong>midiendo repetidamente</strong> a la misma persona en ambas condiciones. Lo que me interesa es si la manipulación experimental cambia algo en cómo la persona realiza la tarea.</p>
<section id="mehr-song-y-spelke-2016" class="level3" data-number="7.3.1">
<h3 data-number="7.3.1" class="anchored" data-anchor-id="mehr-song-y-spelke-2016"><span class="header-section-number">7.3.1</span> Mehr, Song y Spelke (2016)</h3>
<p>Vamos a introducir la prueba t de muestras pareadas con un ejemplo real, de un estudio real. <span class="citation" data-cites="mehr20165">Mehr, Song, and Spelke (<a href="references.html#ref-mehr20165" role="doc-biblioref">2016</a>)</span> investigaron si cantarles canciones a los bebés los ayuda a ser más sensibles a las señales sociales. Por ejemplo, los bebés tienen que aprender a dirigir su atención hacia las personas como parte de aprender a interactuar socialmente. Tal vez cantarle a un bebé ayuda con ese proceso atencional. Cuando un bebé escucha una canción familiar, puede empezar a prestar más atención a la persona que la canta, incluso después de que termina. Esa persona puede volverse más importante para el bebé en términos sociales. Vas a aprender más sobre este estudio en el laboratorio de esta semana. Este ejemplo te prepara para las actividades de ese laboratorio. Acá va un resumen breve de lo que hicieron.</p>
<p>Primero, los padres fueron entrenados para cantarle una canción a sus bebés. Luego de varios días de cantarles esa canción, los padres fueron al laboratorio con sus bebés. En la primera sesión, se sentaron con sus hijos en las rodillas, de forma que los bebés pudieran mirar dos videos. En cada video aparecían dos personas nuevas que el bebé nunca había visto. Cada una de esas personas (los cantantes) cantaba una canción al bebé. Uno de los cantantes cantaba la canción <strong>familiar</strong>, que el bebé ya conocía por sus padres. El otro cantaba una canción <strong>no familiar</strong>, que el bebé nunca había oído.</p>
<p>Hubo dos fases de medición importantes: la fase de línea base (<em>baseline</em>) y la fase de prueba (<em>test</em>).</p>
<p>La fase de línea base ocurrió <strong>antes</strong> de que los bebés vieran y oyeran a los cantantes. Durante esta fase, los bebés miraban un video con ambos cantantes en simultáneo. Los investigadores registraban qué proporción del tiempo el bebé miraba a cada uno. Esta fase servía para ver si los bebés ya tenían una preferencia por alguno de los dos (antes de escucharlos cantar).</p>
<p>La fase de prueba fue <strong>después</strong> de que los bebés vieron y oyeron a cada cantante. En esta fase, los bebés veían videos mudos de los mismos cantantes. Se medía la proporción de tiempo que pasaban mirando a cada uno. La pregunta era: ¿los bebés mirarían más tiempo al cantante que había cantado la canción familiar, en comparación con el otro?</p>
<p>Hay más de una forma de describir el diseño del estudio, pero lo vamos a presentar así: fue un diseño de medidas repetidas, con una variable independiente (la manipulación), llamada <strong>fase de visualización</strong>: línea base vs.&nbsp;prueba. Hubo una variable dependiente (la medición), que fue la <strong>proporción de tiempo mirando</strong> al cantante que había cantado la canción familiar. Fue un diseño de medidas repetidas porque esa proporción se midió <strong>dos veces</strong>: una en la línea base (antes de que los bebés oyeran a los cantantes), y otra en la prueba (después de que los oyeran).</p>
<p>La pregunta clave era si los bebés cambiarían su tiempo de mirada, mirando <strong>más tiempo al cantante de la canción familiar</strong> durante la fase de prueba que en la línea base. Es una pregunta sobre un cambio <strong>dentro de cada bebé</strong>. En general, los posibles resultados eran:</p>
<ol type="1">
<li><p><strong>Sin cambio</strong>: la diferencia entre el tiempo de mirada al cantante de la canción familiar durante línea base y prueba es cero.</p></li>
<li><p><strong>Cambio positivo</strong>: los bebés miran más tiempo al cantante de la canción familiar durante la fase de prueba (después de haberlo visto y escuchado), comparado con la fase de línea base (antes de oírlos). Esto da una diferencia positiva si usamos la fórmula: Tiempo de mirada en prueba − Tiempo de mirada en línea base (al cantante de la canción familiar).</p></li>
<li><p><strong>Cambio negativo</strong>: los bebés miran más tiempo al cantante de la canción <strong>no familiar</strong> durante la fase de prueba (después de haberlos escuchado), en comparación con la línea base (antes de oírlos). Esto da una diferencia negativa con la misma fórmula: Tiempo de mirada en prueba − Tiempo de mirada en línea base (al cantante de la canción familiar).</p></li>
</ol>
</section>
<section id="los-datos" class="level3" data-number="7.3.2">
<h3 data-number="7.3.2" class="anchored" data-anchor-id="los-datos"><span class="header-section-number">7.3.2</span> Los datos</h3>
<p>Veamos los datos de los primeros 5 bebés del estudio. Esto nos va a ayudar a entender mejor algunas propiedades de los datos antes de analizarlos. Vamos a ver que los datos están estructurados de forma que podemos aprovechar con una prueba t de muestras pareadas. (Ojo: miramos solo los primeros 5 bebés para mostrar cómo funcionan los cálculos. El resultado final de la prueba t cambia si usamos todos los datos del estudio).</p>
<p>Acá está la tabla con los datos:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">infant</th>
<th style="text-align: right;">Línea_de_base</th>
<th style="text-align: right;">Test</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">0.60</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.41</td>
<td style="text-align: right;">0.68</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">0.72</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">0.28</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">0.50</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>La tabla muestra la <strong>proporción de tiempo mirando</strong> al cantante de la canción familiar durante las fases de línea base y prueba. Fijate que hay cinco bebés (del 1 al 5). Cada uno fue medido dos veces: una en la fase de línea base y otra en la de prueba. Como dijimos antes, esto es un diseño de <strong>medidas repetidas</strong>, porque se mide a cada bebé más de una vez (en este caso, dos). También se le llama diseño de <strong>muestras pareadas</strong>. ¿Por qué? Porque cada participante aporta un <strong>par de mediciones</strong> (una por cada condición del diseño).</p>
<p>Buenísimo, entonces… ¿qué nos interesa en realidad? Queremos saber si el <strong>tiempo medio de mirada</strong> al cantante de la canción familiar en la fase de prueba es mayor que en la fase de línea base. Estamos comparando las dos medias muestrales entre sí, buscando una diferencia. Ya sabemos que esas diferencias pueden surgir por azar, simplemente por el hecho de que tomamos dos muestras, y que las muestras naturalmente pueden diferir. Así que lo que queremos saber es si es <strong>probable o improbable</strong> que la diferencia observada se deba al azar.</p>
<p>En otras palabras, nos interesa mirar los <strong>valores de diferencia</strong> entre línea base y prueba para cada bebé. La pregunta es: ¿para cada bebé, aumentó su proporción de mirada al cantante de la canción familiar en la fase de prueba comparado con la fase de línea base?</p>
</section>
<section id="los-puntajes-de-diferencia" class="level3" data-number="7.3.3">
<h3 data-number="7.3.3" class="anchored" data-anchor-id="los-puntajes-de-diferencia"><span class="header-section-number">7.3.3</span> Los puntajes de diferencia</h3>
<p>Agreguemos los puntajes de diferencia a la tabla para que sea más fácil ver de qué hablamos. El primer paso es decidir <strong>cómo vamos a calcular la diferencia</strong>. Hay dos opciones:</p>
<ol type="1">
<li>Puntaje en fase de prueba − Puntaje en fase de línea base</li>
<li>Puntaje en fase de línea base − Puntaje en fase de prueba</li>
</ol>
<p>Vamos a usar la <strong>primera fórmula</strong>. ¿Por qué? Porque da <strong>diferencias positivas</strong> cuando el puntaje de la prueba es mayor que el de línea base. Eso hace que los puntajes positivos tengan sentido en este estudio: indican que el bebé miró más al cantante de la canción familiar <strong>después</strong> de escucharlo que <strong>antes</strong>.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">infant</th>
<th style="text-align: right;">Línea_de_base</th>
<th style="text-align: right;">Test</th>
<th style="text-align: right;">diferencias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">0.60</td>
<td style="text-align: right;">0.16</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.41</td>
<td style="text-align: right;">0.68</td>
<td style="text-align: right;">0.27</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">0.72</td>
<td style="text-align: right;">-0.03</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">-0.16</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.03</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Listo, ahora tenemos los puntajes de diferencia. Lo primero que podemos hacer es mirar esos valores y preguntar: ¿cuántos bebés mostraron el efecto que nos interesa? Específicamente: ¿cuántos tuvieron una diferencia positiva?</p>
<p>Podemos ver que <strong>tres de los cinco</strong> bebés mostraron un puntaje positivo (miraron más al cantante de la canción familiar en la fase de prueba que en la de línea base), y <strong>dos bebés</strong> mostraron lo contrario (miraron más al cantante de la canción familiar durante la línea base que durante la prueba).</p>
</section>
<section id="la-diferencia-media" class="level3" data-number="7.3.4">
<h3 data-number="7.3.4" class="anchored" data-anchor-id="la-diferencia-media"><span class="header-section-number">7.3.4</span> La diferencia media</h3>
<p>Como venimos diciendo, el efecto de interés en este estudio es la <strong>diferencia media</strong> entre la proporción de tiempo de mirada en línea base y en prueba. Podemos calcularla como la <strong>media de los puntajes de diferencia</strong>. Vamos a hacerlo. De paso, para divertirnos, también vamos a calcular la media de los puntajes en línea base, los de prueba y los de diferencia.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">infant</th>
<th style="text-align: left;">Línea_de_base</th>
<th style="text-align: left;">Test</th>
<th style="text-align: left;">diferencias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">0.44</td>
<td style="text-align: left;">0.6</td>
<td style="text-align: left;">0.16</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">0.41</td>
<td style="text-align: left;">0.68</td>
<td style="text-align: left;">0.27</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">0.75</td>
<td style="text-align: left;">0.72</td>
<td style="text-align: left;">-0.03</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">0.44</td>
<td style="text-align: left;">0.28</td>
<td style="text-align: left;">-0.16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">0.47</td>
<td style="text-align: left;">0.5</td>
<td style="text-align: left;">0.03</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">2.51</td>
<td style="text-align: left;">2.78</td>
<td style="text-align: left;">0.27</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">0.502</td>
<td style="text-align: left;">0.556</td>
<td style="text-align: left;">0.054</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Podemos ver que hubo una diferencia media positiva de 0.054 entre las fases de prueba y línea base. ¿Podemos apurarnos a concluir que los bebés se sienten más atraídos socialmente hacia personas que les cantaron una canción familiar? Espero que no, al menos no con una muestra tan pequeña. Primero, la diferencia en proporción de tiempo mirando no es muy grande, y por supuesto reconocemos que esa diferencia <strong>podría haberse producido por azar</strong>.</p>
<p>Vamos a evaluar más formalmente si esta diferencia pudo haber sido causada por el azar usando una prueba t de muestras pareadas. Pero antes, calculemos de nuevo <em>t</em> y pensemos qué nos dice <em>t</em> además de lo que ya nos dice la media de los puntajes de diferencia.</p>
</section>
<section id="calcular-t" class="level3" data-number="7.3.5">
<h3 data-number="7.3.5" class="anchored" data-anchor-id="calcular-t"><span class="header-section-number">7.3.5</span> Calcular <em>t</em></h3>
<p>Bueno, ¿cómo se calcula <em>t</em> para una prueba t de muestras pareadas? ¡Sorpresa! Usamos la <strong>misma fórmula de la prueba t de una muestra</strong> que ya aprendiste. Específicamente, usamos la fórmula de la prueba t de una muestra <strong>aplicada a los puntajes de diferencia</strong>. Tenemos una sola muestra de puntajes de diferencia (están en una sola columna), así que podemos usar la prueba t de una muestra. Lo que nos interesa es saber si la <strong>media</strong> de esos puntajes de diferencia podría provenir de una distribución con media 0. Esa distribución especial se llama la <strong>distribución nula</strong> (<em>null distribution</em>): es la distribución de la ausencia de diferencias. Claro que esta distribución puede generar diferencias pequeñas por error muestral, pero esas diferencias <strong>no</strong> están causadas por ninguna manipulación experimental, sino por el simple azar del muestreo.</p>
<p>Vamos a calcular <em>t</em> en un momento. Pero antes, pensemos de nuevo: ¿por qué queremos calcular <em>t</em>? ¿Por qué no quedarnos solo con la diferencia media?</p>
<p>Recordá: toda la idea detrás de <em>t</em> es que nos da una indicación de cuánta <strong>confianza</strong> deberíamos tener en nuestra media. El valor de <em>t</em> se obtiene al dividir una medida de la media (el numerador) por una medida de variación (el error estándar, en el denominador). <em>t</em> será chico cuando la diferencia media es chica, o cuando la variación es grande. O sea, valores bajos de <em>t</em> nos dicen que no deberíamos estar muy seguros sobre esa estimación de diferencia. En cambio, cuando la diferencia media es grande y/o la variación es pequeña, obtenemos un valor alto de <em>t</em>. Eso nos da <strong>más confianza</strong> en la estimación.</p>
<p>Vamos a calcular <em>t</em> para los puntajes de diferencia. Usamos las mismas fórmulas de antes:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 16%">
<col style="width: 6%">
<col style="width: 13%">
<col style="width: 26%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">infant</th>
<th style="text-align: left;">Linea_de_base</th>
<th style="text-align: left;">Test</th>
<th style="text-align: left;">diferencias</th>
<th style="text-align: left;">diferencias_a_la_media</th>
<th style="text-align: left;">diferencias_al_cuadrado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">0.44</td>
<td style="text-align: left;">0.6</td>
<td style="text-align: left;">0.16</td>
<td style="text-align: left;">0.106</td>
<td style="text-align: left;">0.011236</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">0.41</td>
<td style="text-align: left;">0.68</td>
<td style="text-align: left;">0.27</td>
<td style="text-align: left;">0.216</td>
<td style="text-align: left;">0.046656</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">0.75</td>
<td style="text-align: left;">0.72</td>
<td style="text-align: left;">-0.03</td>
<td style="text-align: left;">-0.084</td>
<td style="text-align: left;">0.00705600000000001</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">0.44</td>
<td style="text-align: left;">0.28</td>
<td style="text-align: left;">-0.16</td>
<td style="text-align: left;">-0.214</td>
<td style="text-align: left;">0.045796</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">0.47</td>
<td style="text-align: left;">0.5</td>
<td style="text-align: left;">0.03</td>
<td style="text-align: left;">-0.024</td>
<td style="text-align: left;">0.000575999999999999</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sumas</td>
<td style="text-align: left;">2.51</td>
<td style="text-align: left;">2.78</td>
<td style="text-align: left;">0.27</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0.11132</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Medias</td>
<td style="text-align: left;">0.502</td>
<td style="text-align: left;">0.556</td>
<td style="text-align: left;">0.054</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0.022264</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">sd</td>
<td style="text-align: left;">0.167</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">SEM</td>
<td style="text-align: left;">0.075</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">t</td>
<td style="text-align: left;">0.72</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Si hiciéramos este test usando R, obtendríamos casi los mismos números (hay un poco de redondeo en la tabla).</p>
<div class="cell">
<pre><code>#&gt; 
#&gt;  One Sample t-test
#&gt; 
#&gt; data:  diferencias
#&gt; t = 0.72381, df = 4, p-value = 0.5092
#&gt; alternative hypothesis: true mean is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  -0.1531384  0.2611384
#&gt; sample estimates:
#&gt; mean of x 
#&gt;     0.054</code></pre>
</div>
<p>Acá va una forma rápida de reportar los resultados de la prueba t: t(4) = .72, p = .509.</p>
<p>¿Qué nos dice todo esto? Hay algunos detalles que todavía no abordamos mucho. Por ejemplo, ese 4 representa los <strong>grados de libertad</strong>, de eso hablaremos más adelante. Lo importante por ahora es que el valor de <em>t</em> empiece a tener un poco más de sentido. Obtuvimos un valor <em>t</em> bastante chico: 0.72. ¿Qué podemos decir a partir de eso? Primero, es <strong>positivo</strong>, así que sabemos que la diferencia media también lo fue. El signo del valor <em>t</em> siempre es el mismo que el de la diferencia media (en nuestro caso fue +0.054).</p>
<p>También vemos que el valor <em>p</em> fue .509. Ya vimos valores <em>p</em> antes. Esto nos dice que obtener un valor de <em>t</em> igual o mayor al observado ocurre en aproximadamente un 50.9% de los casos… Bueno, en realidad significa <strong>algo más que eso</strong>. Y para entenderlo, tenemos que hablar de los conceptos de test <strong>bilateral</strong> (<em>de dos colas</em>) y <strong>unilateral</strong> (<em>de una cola</em>).</p>
</section>
<section id="interpretar-valores-t" class="level3" data-number="7.3.6">
<h3 data-number="7.3.6" class="anchored" data-anchor-id="interpretar-valores-t"><span class="header-section-number">7.3.6</span> Interpretar valores <em>t</em></h3>
<p>Recordá lo que estamos haciendo: estamos evaluando si nuestros datos muestrales podrían haber salido de una distribución específica. La distribución <strong>nula</strong>, de ausencia de diferencias. Esta es la distribución de valores <em>t</em> que ocurren con muestras de tamaño 5, con diferencia media igual a 0, y error estándar de la media de .075 (ese es el SEM que calculamos a partir de nuestra muestra).</p>
<p>Podemos ver cómo luce esta distribución nula en <a href="#fig-6tnull" class="quarto-xref">Figure&nbsp;<span>7.5</span></a>:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6tnull" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6tnull-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6tnull-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6tnull-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.5: Una distribución de valores t que pueden ocurrir solo por azar, cuando no hay diferencia entre la muestra y la población
</figcaption>
</figure>
</div>
</div>
</div>
<p>La distribución <em>t</em> de arriba muestra los valores que puede tomar <em>t</em> solo por azar, cuando medimos diferencias de medias en pares de muestras de tamaño 5 (como en nuestro caso). El valor más probable de <em>t</em> es cero, lo cual tiene sentido, porque estamos viendo la distribución de la ausencia de diferencias, que debería tener su mayor densidad en 0. Pero, a veces, por error muestral, pueden aparecer valores de <em>t</em> mayores o menores que cero. Notá que la distribución es <strong>simétrica</strong>: los valores <em>t</em> de la distribución nula son positivos la mitad de las veces, y negativos la otra mitad. Eso es justo lo que esperaríamos por azar.</p>
<p>Entonces, ¿qué queremos saber cuando obtenemos un valor <em>t</em> específico de nuestra muestra? Queremos saber <strong>qué tan probable es</strong> que ocurra ese valor <em>t</em> solo por azar. Esta es una pregunta con sutilezas. Por ejemplo, un valor específico de <em>t</em> no tiene una única probabilidad de ocurrir. Cuando hablamos de probabilidades, nos referimos a <strong>rangos</strong> de valores.</p>
<p>Usamos la letra <em>p</em> para referirnos a la probabilidad de que ocurran ciertos valores de <em>t</em>. Veamos algunos ejemplos:</p>
<ol type="1">
<li><p>¿Cuál es la probabilidad de que <em>t</em> sea igual a cero, o distinto de cero? La respuesta es <em>p = 1</em>, o 100%. Siempre vamos a obtener un valor de <em>t</em> que es cero o no cero… Bueno, a menos que no podamos calcularlo (por ejemplo, si la desviación estándar no está definida), pero si lo podemos calcular, será positivo, negativo o cero.</p></li>
<li><p>¿Cuál es la probabilidad de que <em>t</em> sea mayor o igual a 0? La respuesta es <em>p = .5</em>, o 50%. El 50% de los valores <em>t</em> son mayores o iguales a 0.</p></li>
<li><p>¿Y de que <em>t</em> sea menor o igual a 0? También <em>p = .5</em>. La mitad de los valores están en esa región.</p></li>
</ol>
<p>Podemos responder estas preguntas solo mirando la distribución <em>t</em> y dividiéndola en dos regiones iguales: la mitad izquierda (50% de los valores <em>t</em>) y la mitad derecha (los otros 50%).</p>
<p>¿Y si queremos un enfoque más fino? Por ejemplo, dividir en regiones del 10%. ¿Qué valores de <em>t</em> ocurren solo el 10% del tiempo? Podemos marcar líneas que dividan la distribución en regiones así. Notá que los valores extremos (más grandes o más chicos) son menos probables, entonces los intervalos más alejados del centro tienen que ser más anchos para contener el mismo 10%. Así se ve la figura <a href="#fig-6percentregions" class="quarto-xref">Figure&nbsp;<span>7.6</span></a>:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6percentregions" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6percentregions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6percentregions-1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6percentregions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.6: Dividiendo la distribución t en regiones que contienen cada una el 10% de los valores t. Los intervalos son más angostos cerca del centro, donde hay más valores t.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Considerá las probabilidades (<em>p</em>) de <em>t</em> para los distintos rangos:</p>
<ol type="1">
<li><em>t</em> ≤ -1.5 → <em>p</em> = 10%</li>
<li>-1.5 ≥ <em>t</em> ≤ -0.9 → <em>p</em> = 10%</li>
<li>-0.9 ≥ <em>t</em> ≤ -0.6 → <em>p</em> = 10%</li>
<li><em>t</em> ≥ 1.5 → <em>p</em> = 10%</li>
</ol>
<p>Fijate que en todos los casos la probabilidad es del 10%. Los valores <em>t</em> ocurren en esos rangos con un 10% de probabilidad.</p>
</section>
<section id="obtener-valores-p-para-valores-t" class="level3" data-number="7.3.7">
<h3 data-number="7.3.7" class="anchored" data-anchor-id="obtener-valores-p-para-valores-t"><span class="header-section-number">7.3.7</span> Obtener valores <em>p</em> para valores <em>t</em></h3>
<p>Capaz te estás preguntando de dónde saqué algunos de estos valores. Por ejemplo, ¿cómo sé que el 10% de los valores <em>t</em> en esta distribución nula son aproximadamente 1.5 o mayores? La respuesta es: se lo pedí a R. En la mayoría de los libros de estadística, te dirían: <em>hay una tabla al final del libro</em> donde podés buscar estos valores… Este libro <strong>no</strong> tiene esa tabla. Podríamos hacer una para vos. Y tal vez lo hagamos. Pero todavía no…</p>
<p>Entonces, ¿de dónde salen esos valores y cómo podés saberlos? La respuesta complicada es que <strong>no vamos a explicar las matemáticas detrás de cómo se obtienen</strong> estos valores, porque:</p>
<ol type="1">
<li>Algunos autores de este libro admiten que <strong>no entienden bien esas matemáticas</strong>;</li>
<li>Nos desviaría mucho del foco del libro;</li>
<li>Vas a aprender cómo obtener estos valores en el laboratorio usando software;</li>
<li>También vas a aprender cómo obtenerlos sin fórmulas, solo haciendo simulaciones;</li>
<li>Podés hacerlo en R, en Excel, o usando <a href="http://www.socscistatistics.com/pvalues/tdistribution.aspx">esta calculadora online</a>.</li>
</ol>
<p>En resumen: podés encontrar los valores <em>t</em> y sus <em>p</em> asociados usando software. Pero el software <strong>no te explica qué significan</strong> esos valores. Eso es lo que estamos haciendo acá. Además, vas a ver que el software te pide algunos datos más: los <strong>grados de libertad</strong> del test, y si el test es <strong>unilateral o bilateral</strong>. Todavía no explicamos eso. Vamos a hacerlo ahora.</p>
<p>Ojo: vamos a explicar los grados de libertad <strong>al final</strong>. Primero, vamos con el test <strong>unilateral</strong>.</p>
</section>
<section id="test-unilateral-de-una-cola-o-one-tailed-en-inglés" class="level3" data-number="7.3.8">
<h3 data-number="7.3.8" class="anchored" data-anchor-id="test-unilateral-de-una-cola-o-one-tailed-en-inglés"><span class="header-section-number">7.3.8</span> Test unilateral (de una cola, o one-tailed en inglés)</h3>
<p>Un <strong>test unilateral</strong> (<em>one-tailed test</em>) también se llama a veces <strong>test direccional</strong>. Se le dice así porque el investigador puede tener una hipótesis en mente que sugiere que la diferencia entre medias va a tener una <strong>dirección específica</strong>: o bien una diferencia positiva, o bien una negativa.</p>
<p>Típicamente, el investigador establece un <strong>criterio alfa</strong> (<em>alpha criterion</em>). Este criterio es como una línea en la arena para tomar decisiones. A menudo se fija en <span class="math inline">\(p = .05\)</span>. ¿Qué significa eso? La figura <a href="#fig-6critT" class="quarto-xref">Figure&nbsp;<span>7.7</span></a> muestra la distribución <em>t</em> con ese criterio alfa:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6critT" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6critT-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6critT-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6critT-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.7: El valor crítico de t para un criterio alfa de 0.05. El 5% de todos los valores t son iguales o mayores a este valor.
</figcaption>
</figure>
</div>
</div>
</div>
<p>La figura muestra que los valores <em>t</em> de <strong>+2.13 o más</strong> ocurren el 5% de las veces. Como la distribución <em>t</em> es simétrica, también sabemos que valores de <strong>–2.13 o menos</strong> ocurren el 5% de las veces. Ambas afirmaciones son ciertas bajo la distribución nula (sin diferencias). Esto significa que, cuando realmente no hay diferencias, un investigador puede esperar encontrar un valor <em>t</em> de 2.13 o mayor en el 5% de los casos.</p>
<p>Recapitulemos y conectemos algunos conceptos:</p>
<ol type="1">
<li><p><strong>Criterio alfa</strong>: el criterio que define el investigador para decidir si cree que la diferencia se debe o no al azar. En este caso, es <span class="math inline">\(p = .05\)</span>.</p></li>
<li><p><strong>t crítico</strong>: el valor <em>t</em> asociado al criterio alfa. Para un test unilateral, es el valor tal que el 5% de todos los <em>t</em> están en ese valor o más. En nuestro ejemplo, <em>t</em> crítico = 2.13. El 5% de los valores <em>t</em> (con 4 grados de libertad) son iguales o mayores a 2.13.</p></li>
<li><p><strong>t observado</strong>: el valor <em>t</em> que calculaste a partir de tu muestra. En el ejemplo de los bebés, fue <em>t</em>(4) = 0.72.</p></li>
<li><p><strong>Valor <em>p</em></strong>: el valor <em>p</em> es la probabilidad de obtener el valor <em>t</em> observado o uno mayor. En nuestro ejemplo anterior, el valor <em>p</em> para <em>t</em>(4) = 0.72 fue <em>p = .509</em>. SIN EMBARGO, ese valor <em>p</em> <strong>no fue calculado</strong> para un test direccional (unilateral)… (hablamos más sobre qué significa ese .509 en la siguiente sección).</p></li>
</ol>
<p>La <a href="#fig-6tonedirection" class="quarto-xref">Figure&nbsp;<span>7.8</span></a> muestra cómo se vería el valor <em>p</em> para <em>t</em>(4) = 0.72 en un test unilateral:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6tonedirection" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6tonedirection-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6tonedirection-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6tonedirection-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.8: Un caso en el que el valor t observado es mucho menor que el valor crítico para un test t unilateral.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Vamos paso a paso. Marcamos en el gráfico el valor <em>t</em> observado (0.72). Sombreamos de gris toda la región a su derecha. Esa región gris representa un 25.6% de todos los valores <em>t</em>. En otras palabras, <strong>el 25.6%</strong> de los valores <em>t</em> son mayores o iguales a 0.72. Es decir, <strong>por azar</strong>, se puede obtener un valor de <em>t</em> igual o mayor a 0.72 en más de una de cada cuatro veces.</p>
<p>Y de hecho, eso fue lo que encontramos: un <em>t</em> de 0.72. Sabiendo que un valor así o mayor ocurre el 25.6% del tiempo por azar, ¿estarías confiado en que la diferencia media <strong>no</strong> se debe al azar? Probablemente no, ya que el azar puede producir ese valor bastante seguido.</p>
<p>Siguiendo el procedimiento “estándar” de toma de decisiones, concluiríamos que nuestro valor no es estadísticamente significativo, porque no fue lo suficientemente grande. Si nuestro valor observado fuera mayor que el valor crítico (mayor que 2.13), definido por nuestro criterio alfa, entonces afirmaríamos que nuestro valor es estadísticamente significativo. Esto sería equivalente a decir que creemos que es poco probable que la diferencia observada se deba al azar. En general, para cualquier valor observado, el <em>p</em>-valor asociado indica cuán probable es observar un valor de ese tamaño o mayor. El <em>p</em>-valor siempre se refiere a un rango de valores, nunca a un solo valor específico. Los investigadores suelen utilizar el criterio alfa de 0.05, por conveniencia y por convención. Existen otras formas de interpretar estos valores que no dependen de una dicotomía estricta (significativo versus no significativo).</p>
</section>
<section id="test-bilateral-de-dos-cola-o-two-tailed-en-inglés" class="level3" data-number="7.3.9">
<h3 data-number="7.3.9" class="anchored" data-anchor-id="test-bilateral-de-dos-cola-o-two-tailed-en-inglés"><span class="header-section-number">7.3.9</span> Test bilateral (de dos cola, o two-tailed en inglés)</h3>
<p>OK, entonces eso fue sobre tests de una cola… ¿Qué son los tests de dos colas? El valor <span class="math inline">\(p\)</span> que calculamos originalmente a partir del <span class="math inline">\(t\)</span>-test para muestras pareadas era para un test de dos colas. A menudo, el valor <span class="math inline">\(p\)</span> por defecto corresponde a un test de dos colas.</p>
<p>El test de dos colas plantea una pregunta más general sobre si una diferencia es probable que haya sido producida por azar. La pregunta es: ¿cuál es la probabilidad de que exista alguna diferencia? También se lo llama un test <strong>no direccional</strong>, porque acá no nos importa la dirección o el signo de la diferencia (positivo o negativo), sino simplemente si hay alguna diferencia.</p>
<p>Se siguen los mismos principios básicos que antes. Definimos un criterio alfa (<span class="math inline">\(\alpha = 0.05\)</span>). Y decimos que cualquier valor observado de <span class="math inline">\(t\)</span> que tenga una probabilidad de <span class="math inline">\(p\)</span> &lt; .05 (el <span class="math inline">\(p\)</span> es menor que .05) va a ser llamado <strong>estadísticamente significativo</strong>, y aquellos que sean más probables (<span class="math inline">\(p\)</span> &gt; .05, el <span class="math inline">\(p\)</span> es mayor que .05) se van a considerar resultados nulos, o no estadísticamente significativos. La única diferencia está en cómo dibujamos el rango alfa. Antes estaba en el lado derecho de la distribución <span class="math inline">\(t\)</span> (recordá que estábamos haciendo un test de una cola, así que solo nos interesaba un lado).</p>
<p><span class="quarto-unresolved-ref">?fig-6twotailedt</span> muestra cuáles son el 5% más extremo de los valores <span class="math inline">\(t\)</span> cuando ignoramos su signo (ya sean positivos o negativos).</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption>El valor crítico de t para un test bilateral. El 5% total de los valores t son mayores o menores que los valores críticos.</figcaption>
</figure>
</div>
</div>
</div>
<p>¿Qué estamos viendo acá? Una distribución de ausencia de diferencias (la nula, que es la que estamos considerando) puede producir valores de <em>t</em> mayores o iguales a 2.78 el 2.5% del tiempo, y menores o iguales a -2.78 también el 2.5% del tiempo. En total, eso da un 5%. Podemos decir que <em>t</em>s mayores que ±2.78 ocurren el 5% de las veces.</p>
<p>Por eso, el valor crítico de <em>t</em> para un test bilateral es ±2.78. Como podés ver, el test bilateral <strong>no toma en cuenta la dirección del efecto</strong>. Justamente por eso el valor crítico de <em>t</em> es más alto en un test bilateral que en uno unilateral. Esperamos que ahora veas por qué se llama test de <strong>dos colas</strong>: hay <strong>dos colas</strong> de la distribución, a la izquierda y a la derecha, ambas sombreadas en verde.</p>
</section>
<section id="test-unilateral-o-bilateral" class="level3" data-number="7.3.10">
<h3 data-number="7.3.10" class="anchored" data-anchor-id="test-unilateral-o-bilateral"><span class="header-section-number">7.3.10</span> ¿Test unilateral o bilateral?</h3>
<p>Ahora que sabés que existen los dos tipos —test unilateral y test bilateral—, ¿cuál deberías usar? Hay cierta sabiduría convencional sobre esto… pero también hay debate. Al final, lo importante es que <strong>puedas justificar</strong> tu elección y por qué es adecuada para tus datos. Esa es la respuesta real.</p>
<p>La respuesta convencional es que usás un <strong>test unilateral</strong> cuando tenés una teoría o hipótesis que hace una <strong>predicción direccional</strong> (la teoría predice que la diferencia será positiva o negativa). Del mismo modo, usás un <strong>test bilateral</strong> cuando estás buscando <strong>cualquier diferencia</strong>, sin una predicción direccional (la teoría solo predice que habrá una diferencia, sin decir si será positiva o negativa).</p>
<p>También parece que las personas eligen entre test unilaterales o bilaterales según cuán <strong>arriesgados</strong> son como investigadores. Si siempre usaras tests unilaterales, los valores <em>t</em> críticos para tu criterio alfa serían <strong>más bajos</strong> que los de un test bilateral. A largo plazo, cometerías <strong>más errores tipo I</strong>, porque el umbral para detectar un efecto es más bajo en un test unilateral que en uno bilateral.</p>
<blockquote class="blockquote">
<p>Recordá: los errores tipo I ocurren cuando rechazás la idea de que la diferencia se deba al azar. Muchas veces no sabés que cometiste este error. Ocurre cuando el <strong>error muestral</strong> fue en realidad la causa de la diferencia, pero el investigador <strong>descarta</strong> esa posibilidad y concluye que su manipulación fue la causa.</p>
</blockquote>
<p>De forma similar, si siempre usás tests bilaterales, incluso cuando tenés una predicción direccional, vas a cometer <strong>menos errores tipo I</strong> a largo plazo, porque el <em>t</em> crítico es más alto. Es bastante común que los investigadores usen un <strong>test bilateral más conservador</strong>, incluso cuando hacen predicciones direccionales basadas en teoría.</p>
<p>En la práctica, los investigadores tienden a adoptar un estándar de reporte común en su disciplina. Si esa práctica está justificada o no, puede ser una cuestión abierta. Lo importante para cualquier investigador (o estudiante que aprende estadística) es <strong>poder justificar</strong> su elección del tipo de test.</p>
</section>
<section id="grados-de-libertad" class="level3" data-number="7.3.11">
<h3 data-number="7.3.11" class="anchored" data-anchor-id="grados-de-libertad"><span class="header-section-number">7.3.11</span> Grados de libertad</h3>
<p>Antes de cerrar con las pruebas t de muestras pareadas, tenemos que hablar de los <strong>grados de libertad</strong>.</p>
<p>Tenemos la impresión de que los estudiantes <strong>no entienden muy bien</strong> qué son los grados de libertad. Si estás leyendo este libro, capaz todavía te estás preguntando qué significa eso, ya que no lo explicamos hasta ahora.</p>
<p>Para la prueba t, hay una fórmula para los grados de libertad. Para las pruebas t de una muestra y de muestras pareadas, la fórmula es:</p>
<p><span class="math inline">\(\text{Grados de libertad} = \text{df} = n - 1\)</span></p>
<p>Donde <em>n</em> es el número de muestras del test.</p>
<p>En nuestro ejemplo con la prueba t pareado, había 5 bebés. Entonces:</p>
<p><span class="math inline">\(df = 5 - 1 = 4\)</span></p>
<p>Bueno, eso es una fórmula. Pero, ¿a quién le importan los grados de libertad? ¿Qué significa ese número? ¿Y por qué lo reportamos cuando presentamos una prueba t?</p>
<p>Seguro notaste el número entre paréntesis, por ejemplo: <em>t</em>(4) = .72. Ese 4 es el <em>df</em>, o grados de libertad.</p>
<p>Los grados de libertad son tanto un <strong>concepto</strong> como una <strong>corrección</strong>. El concepto es que, si estás estimando alguna propiedad de los datos y usás esa estimación, eso impone ciertas <strong>restricciones</strong> sobre tus datos.</p>
<p>Por ejemplo, considerá los números: 1, 2, 3. La media de estos números es 2. Ahora imaginá que te digo que <strong>la media de tres números es 2</strong>. Entonces, ¿cuántos de esos tres números tienen libertad? Suena como una pregunta rara, ¿no? Lo que queremos decir es: ¿cuántos de esos tres números pueden ser cualquier número libremente? Los <strong>primeros dos números</strong> pueden ser <strong>cualquier cosa</strong>. Pero una vez que fijás esos dos, el tercer número <strong>ya no tiene libertad</strong>: <strong>tiene que ser un número específico</strong> para que el promedio dé 2. Es decir, los dos primeros tienen libertad, el tercero no.</p>
<p>Para ilustrarlo: elijamos dos números cualquiera —por ejemplo, 51 y -3. Usé mi libertad para elegir esos dos. Ahora, si nuestros tres números son 51, -3 y <em>x</em>, y queremos que la media sea 2, solo hay una solución: <em>x</em> tiene que ser -42. De otro modo, el promedio no sería 2.</p>
<p>Esta es una forma de entender los <strong>grados de libertad</strong>. En este ejemplo, hay 3 números y <strong>n–1 = 2</strong> grados de libertad, porque <strong>2</strong> pueden ser libres, pero el tercero queda <strong>determinado</strong>.</p>
<p>En estadística, los grados de libertad se usan mucho, especialmente cuando una estimación depende de otra estimación. Por ejemplo: cuando calculamos la <strong>desviación estándar muestral</strong>, primero calculamos la <strong>media muestral</strong>, ¿no? Al estimar la media, estamos <strong>fijando</strong> un aspecto de la muestra. Entonces, cuando calculamos la desviación estándar, usamos <strong>n–1</strong> en lugar de <em>n</em>. Ahí aparece otra vez ese famoso <strong>n–1</strong>.</p>
<section id="simulación-del-efecto-de-los-grados-de-libertad-sobre-la-distribución-t" class="level4" data-number="7.3.11.1">
<h4 data-number="7.3.11.1" class="anchored" data-anchor-id="simulación-del-efecto-de-los-grados-de-libertad-sobre-la-distribución-t"><span class="header-section-number">7.3.11.1</span> Simulación del efecto de los grados de libertad sobre la distribución <em>t</em></h4>
<p>Hay al menos dos formas de pensar los grados de libertad para una prueba t. Por un lado, si querés <strong>usar fórmulas</strong> matemáticas para calcular aspectos de la distribución <em>t</em>, necesitás los grados de libertad como <strong>parámetro</strong> de entrada. (Si querés ver las fórmulas, bajá en la <a href="https://es.wikipedia.org/wiki/Distribuci%C3%B3n_t_de_Student">página de Wikipedia de la prueba t</a> hasta la parte de funciones de densidad de probabilidad o de distribución acumulada. A nosotros eso nos parece bastante intimidante, y quizás por eso los grados de libertad no se entienden bien.)</p>
<p>Pero si queremos simular la distribución <em>t</em>, ahí se ve más fácil cómo influyen los grados de libertad en su forma. Recordá: <em>t</em> es una estadística muestral, se <strong>calcula a partir de la muestra</strong>. Así que podríamos simular el proceso de calcular <em>t</em> en muchas muestras distintas, y luego graficar el histograma de esos valores para ver cómo se ve la distribución <em>t</em>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6dft" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6dft-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6dft-1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6dft-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.9: La distribución t se vuelve más angosta a medida que aumentan el tamaño muestral y los grados de libertad (de 4 a 100).
</figcaption>
</figure>
</div>
</div>
</div>
<p>En la <a href="#fig-6dft" class="quarto-xref">Figure&nbsp;<span>7.9</span></a>, fijate que la distribución roja para <span class="math inline">\(df = 4\)</span> es un poco más baja y más ancha que la distribución azul verdosa para <span class="math inline">\(df = 100\)</span>. A medida que aumentan los grados de libertad, la distribución <em>t</em> se vuelve más alta (en el centro) y más angosta en el rango. Se vuelve más picuda. ¿Adivinás por qué?</p>
<p>Recordá: estamos estimando una estadística muestral, y los grados de libertad son solo un número que representa cuántos sujetos hay (menos uno). Y ya sabemos que, al aumentar <em>n</em>, nuestras estadísticas muestrales se vuelven mejores estimaciones (con menos varianza) de los parámetros poblacionales. Entonces, <em>t</em> se vuelve una mejor estimación de su “valor verdadero” a medida que crece el tamaño muestral, lo que produce una distribución de <em>t</em> más angosta.</p>
<p>Existe una distribución <em>t</em> ligeramente distinta para cada grado de libertad, y las regiones críticas asociadas al 5% de los valores extremos cambian cada vez. Por eso <strong>reportamos los grados de libertad</strong> en cada prueba t: definen la distribución de valores <em>t</em> para el tamaño muestral que usamos.</p>
<p>¿Por qué usamos <em>n–1</em> y no <em>n</em>? Bueno, calculamos <em>t</em> usando la desviación estándar muestral para estimar el error estándar de la media, y esa estimación usa <em>n–1</em> en el denominador. Por eso, la distribución <em>t</em> se construye asumiendo <em>n–1</em>.</p>
<p>Con eso, ya tenés suficiente sobre grados de libertad…</p>
</section>
</section>
</section>
<section id="la-prueba-t-de-muestras-pareadas-contraataca" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="la-prueba-t-de-muestras-pareadas-contraataca"><span class="header-section-number">7.4</span> La prueba t de muestras pareadas contraataca</h2>
<p>Capaz te estás preguntando si <strong>alguna vez vamos a terminar</strong> de hablar sobre la prueba t de muestras pareadas… ¿¡por qué hay una segunda vuelta!? Tranquilo, esto es breve. Solo vamos a:</p>
<ol type="1">
<li><p>Recordarte qué estábamos haciendo con el estudio con bebés.</p></li>
<li><p>Hacer una prueba t de muestras pareadas usando <strong>todos</strong> los datos del estudio y discutir los resultados.</p></li>
</ol>
<p>Recordá que nos preguntábamos si los bebés mirarían más tiempo al cantante de la canción familiar durante la fase de prueba, comparado con la línea base. Ya te mostramos los datos de 5 bebés, y caminamos paso a paso por los cálculos de la prueba t. A modo de repaso, se veía así:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 7%">
<col style="width: 15%">
<col style="width: 29%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">infant</th>
<th style="text-align: left;">Baseline</th>
<th style="text-align: left;">Test</th>
<th style="text-align: left;">diferencias</th>
<th style="text-align: left;">diferencias_a_la_media</th>
<th style="text-align: left;">Squared_diferencias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">0.44</td>
<td style="text-align: left;">0.6</td>
<td style="text-align: left;">0.16</td>
<td style="text-align: left;">0.106</td>
<td style="text-align: left;">0.011236</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">0.41</td>
<td style="text-align: left;">0.68</td>
<td style="text-align: left;">0.27</td>
<td style="text-align: left;">0.216</td>
<td style="text-align: left;">0.046656</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">0.75</td>
<td style="text-align: left;">0.72</td>
<td style="text-align: left;">-0.03</td>
<td style="text-align: left;">-0.084</td>
<td style="text-align: left;">0.00705600000000001</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">0.44</td>
<td style="text-align: left;">0.28</td>
<td style="text-align: left;">-0.16</td>
<td style="text-align: left;">-0.214</td>
<td style="text-align: left;">0.045796</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">0.47</td>
<td style="text-align: left;">0.5</td>
<td style="text-align: left;">0.03</td>
<td style="text-align: left;">-0.024</td>
<td style="text-align: left;">0.000575999999999999</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sumas</td>
<td style="text-align: left;">2.51</td>
<td style="text-align: left;">2.78</td>
<td style="text-align: left;">0.27</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0.11132</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Medias</td>
<td style="text-align: left;">0.502</td>
<td style="text-align: left;">0.556</td>
<td style="text-align: left;">0.054</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0.022264</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">de</td>
<td style="text-align: left;">0.167</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">EEM</td>
<td style="text-align: left;">0.075</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">t</td>
<td style="text-align: left;">0.72</td>
</tr>
</tbody>
</table>
</div>
<pre><code>#&gt; 
#&gt;  One Sample t-test
#&gt; 
#&gt; data:  round(diferencias, digits = 2)
#&gt; t = 0.72381, df = 4, p-value = 0.5092
#&gt; alternative hypothesis: true mean is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  -0.1531384  0.2611384
#&gt; sample estimates:
#&gt; mean of x 
#&gt;     0.054</code></pre>
</div>
<p>Volvamos a escribir el resultado una vez más: la diferencia media fue 0.054, <em>t</em>(4) = .72, <em>p</em> = .509. Ahora también podemos confirmar que el valor <em>p</em> se obtuvo de un <strong>test bilateral</strong>. Entonces, ¿qué significa todo esto?</p>
<p>Podemos decir que un valor <em>t</em> con valor absoluto de .72 o más ocurre el 50.9% del tiempo. Más precisamente: la distribución de <strong>ausencia de diferencias</strong> (la nula) produce un valor <em>t</em> de ese tamaño o mayor el 50.9% de las veces. En otras palabras: <strong>el azar por sí solo podría haber producido perfectamente el valor <em>t</em> de nuestra muestra</strong>, y la diferencia media de 0.054 que observamos podría deberse simplemente al azar.</p>
<p>Ahora metamos <strong>todos los datos</strong> de la prueba t y corramos el análisis con los <strong>32 bebés</strong> del estudio:</p>
<div class="cell">
<pre><code>#&gt; 
#&gt;  One Sample t-test
#&gt; 
#&gt; data:  diferencias
#&gt; t = 2.4388, df = 31, p-value = 0.02066
#&gt; alternative hypothesis: true mean is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  0.01192088 0.13370412
#&gt; sample estimates:
#&gt; mean of x 
#&gt; 0.0728125</code></pre>
</div>
<p>Ahora obtenemos una respuesta muy distinta. Podríamos resumir los resultados diciendo que la diferencia media fue 0.073, <em>t</em>(31) = 2.44, <em>p</em> = 0.020. ¿Cuántos bebés hubo en total? Bueno, los grados de libertad fueron 31, así que debió haber <strong>32 bebés</strong> en el estudio.</p>
<p>Ahora vemos un valor <em>p</em> mucho más bajo. Este también fue un <strong>test bilateral</strong>, así que observar un valor <em>t</em> de 2.4 o más (en valor absoluto) ocurre solo el 2% del tiempo. En otras palabras, la <strong>distribución de ausencia de diferencias</strong> rara vez produce un valor <em>t</em> como el que observamos. Por lo tanto, es <strong>poco probable</strong> que la diferencia media observada de 0.073 se deba al azar (podría deberse al azar, sí, pero es muy poco probable).</p>
<p>Como resultado, podemos tener <strong>cierta confianza</strong> en concluir que <strong>ver y escuchar a una persona desconocida cantar una canción familiar</strong> lleva al bebé a prestar más atención a esa persona, y eso <strong>podría beneficiar su aprendizaje social</strong>.</p>
</section>
<section id="prueba-t-de-muestras-independientes-el-regreso-d-la-prueba-t" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="prueba-t-de-muestras-independientes-el-regreso-d-la-prueba-t"><span class="header-section-number">7.5</span> Prueba t de muestras independientes: ¿el regreso d la prueba t?</h2>
<p>Si venís siguiendo las referencias a Star Wars, esta sería la última película de la trilogía original… la <strong>prueba t de muestras independientes</strong>. Es básicamente la misma historia de antes, pero con un giro. Recordá que hay distintos tipos de <em>t</em>-tests para distintos diseños experimentales. Cuando tu diseño es de <strong>grupos independientes</strong> (<em>between-subjects</em>), usás una <strong>prueba t de muestras independientes</strong>.</p>
<p>Los diseños entre sujetos implican personas diferentes en cada condición experimental. Si hay dos condiciones y 10 personas por condición, entonces hay 20 personas en total. Y no hay puntajes pareados, porque <strong>cada persona se mide una sola vez</strong>. No hay medidas repetidas. Como no hay medidas repetidas, no tiene sentido calcular <strong>diferencias entre condiciones</strong> para cada sujeto. Los puntajes no están emparejados de forma significativa, así que <strong>no tiene sentido restarlos</strong>. Entonces, ¿qué hacemos?</p>
<p>La lógica de la prueba t de muestras independientes es la <strong>misma</strong> que en las otras pruebas t. Calculamos la media de cada grupo, luego la diferencia. Esa diferencia va al numerador de la fórmula del <em>t</em>. Después estimamos la <strong>variación</strong> para el denominador. Dividimos la diferencia de medias por esa estimación, y obtenemos <em>t</em>. Es como antes. La única complicación es: ¿qué va en el denominador? ¿Cómo estimamos la varianza? Estaría bueno si pudiéramos hacer algo directo, como esto (en un experimento con dos grupos, A y B):</p>
<p><span class="math inline">\(t = \frac{\bar{A} - \bar{B}}{\left(\frac{SEM_A + SEM_B}{2}\right)}\)</span></p>
<p>En lenguaje simple, esto sería:</p>
<ol type="1">
<li>Calculás la diferencia de medias y la ponés arriba;</li>
<li>Calculás el <strong>error estándar de la media</strong> (SEM) para cada grupo;</li>
<li>Promediás esos SEMs para obtener una sola estimación, combinando ambas muestras.</li>
</ol>
<p>Esto estaría bueno, pero lamentablemente, resulta que sacar el promedio de dos errores estándar de la media no es la mejor forma de hacerlo. Eso generaría un estimador sesgado de la variación para la distribución hipotética donde no hay diferencias. No vamos a meternos con las matemáticas acá, pero en vez de usar la fórmula de arriba, podemos usar otra que nos da una <strong>estimación no sesgada del error estándar combinado de la media muestral</strong>. Nuestra nueva y mejorada fórmula del <span class="math inline">\(t\)</span> se vería así:</p>
<p><span class="math inline">\(t = \frac{\bar{X}_A - \bar{X}_B}{s_p \cdot \sqrt{\frac{1}{n_A} + \frac{1}{n_B}}}\)</span></p>
<p>Y <span class="math inline">\(s_p\)</span>, que es la desviación estándar combinada de las muestras, se define así (notá que las <em>s</em> en la fórmula son <strong>varianzas</strong>):</p>
<p><span class="math inline">\(s_p = \sqrt{\frac{(n_A - 1)s_A^2 + (n_B - 1)s_B^2}{n_A + n_B - 2}}\)</span></p>
<p>Créeme: es mucha más fórmula de la que quería tipear. ¿Hacemos un ejemplo de prueba t de muestras independientes <strong>a mano</strong>, para ver cómo se hacen los cálculos? Dale… pero lo vamos a hacer de una forma <strong>ligeramente distinta</strong> a la que esperás. Voy a mostrarte los pasos usando R.</p>
<p>Inventé unos puntajes ficticios para los grupos A y B. Luego seguí todos los pasos de la fórmula, pero hice que R haga cada uno de los cálculos. Esto te muestra los pasos necesarios siguiendo el código. Al final imprimo los valores de la prueba t que calculé “a mano”, y luego el valor de la prueba t que da la función <code>t.test()</code> de R. Deberías obtener el mismo valor de <em>t</em> si te animás a calcularlo a mano.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="do">## A mano, usando código en R</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">9</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>mean_difference <span class="ot">&lt;-</span> <span class="fu">mean</span>(a) <span class="sc">-</span> <span class="fu">mean</span>(b) <span class="co"># diferencia de medias</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>variance_a <span class="ot">&lt;-</span> <span class="fu">var</span>(a) <span class="co"># varianza para A</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>variance_b <span class="ot">&lt;-</span> <span class="fu">var</span>(b) <span class="co"># varianza para B</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Parte superior e inferior de la fórmula de sp</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>sp_numerator <span class="ot">&lt;-</span> (<span class="dv">4</span> <span class="sc">*</span> variance_a <span class="sc">+</span> <span class="dv">4</span> <span class="sc">*</span> variance_b) </span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>sp_denominator <span class="ot">&lt;-</span> <span class="dv">5</span> <span class="sc">+</span> <span class="dv">5</span> <span class="sc">-</span> <span class="dv">2</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>sp <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(sp_numerator <span class="sc">/</span> sp_denominator) <span class="co"># calcular sp</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a><span class="co"># calcular t según la fórmula</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> mean_difference <span class="sc">/</span> (sp <span class="sc">*</span> <span class="fu">sqrt</span>((<span class="dv">1</span><span class="sc">/</span><span class="dv">5</span>) <span class="sc">+</span> (<span class="dv">1</span><span class="sc">/</span><span class="dv">5</span>)))</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>t <span class="co"># mostrar resultado</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] -2.017991</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a><span class="co"># usando la función de R</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(a, b, <span class="at">paired =</span> <span class="cn">FALSE</span>, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Two Sample t-test</span></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; data:  a and b</span></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; t = -2.018, df = 8, p-value = 0.0783</span></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; alternative hypothesis: true difference in means is not equal to 0</span></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 95 percent confidence interval:</span></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  -5.5710785  0.3710785</span></span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; sample estimates:</span></span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; mean of x mean of y </span></span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;       3.0       5.6</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="simulando-datos-para-tests-t" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="simulando-datos-para-tests-t"><span class="header-section-number">7.6</span> Simulando datos para tests <span class="math inline">\(t\)</span></h2>
<p>Un tema “avanzado” dentro de los tests <span class="math inline">\(t\)</span> es la idea de usar R para hacer simulaciones de tests <span class="math inline">\(t\)</span>.</p>
<p>Si te acordás, el <span class="math inline">\(t\)</span> es una propiedad de una muestra. Calculamos el <span class="math inline">\(t\)</span> a partir de nuestra muestra. La distribución <span class="math inline">\(t\)</span> representa el comportamiento hipotético de nuestras muestras. Es decir, si hubiéramos tomado miles y miles de muestras, y calculado el <span class="math inline">\(t\)</span> para cada una, y luego miráramos la distribución de esos valores de <span class="math inline">\(t\)</span>, tendríamos la distribución muestral del <span class="math inline">\(t\)</span>.</p>
<p>Puede ser muy útil acostumbrarse a usar R para simular datos bajo ciertas condiciones, para ver cómo se comportan tus datos muestrales y cosas como el <span class="math inline">\(t\)</span>. ¿Por qué es útil esto? Principalmente porque te ayuda a desarrollar una intuición sobre cómo el error muestral (el azar) puede influir en tus resultados, dadas ciertas características de tu diseño, como el tamaño de la muestra, el tamaño de la diferencia de medias que esperás encontrar en tus datos, y la cantidad de variación que podría haber. Estos métodos pueden usarse formalmente para hacer análisis de potencia (<em>power analyses</em>), o de manera más informal para tener una mejor idea de los datos.</p>
<section id="simular-una-prueba-t-de-una-muestra" class="level3" data-number="7.6.1">
<h3 data-number="7.6.1" class="anchored" data-anchor-id="simular-una-prueba-t-de-una-muestra"><span class="header-section-number">7.6.1</span> Simular una prueba t de una muestra</h3>
<p>Acá están los pasos que podrías seguir para simular datos para una prueba t de una muestra:</p>
<ol type="1">
<li><p>Hacés algunas suposiciones sobre cómo podría ser tu muestra (que estás planeando recolectar). Por ejemplo, podrías planear recolectar datos de 30 personas. Los puntajes podrían venir de una distribución normal (media = 50, sd = 10).</p></li>
<li><p>Simulás números desde esa distribución y luego hacés una prueba t sobre esos datos simulados. Guardás las estadísticas que te interesan (como los <em>t</em> y <em>p</em>) y después observás cómo se comportan.</p></li>
</ol>
<p>Hagámoslo un par de veces. Primero, vamos a simular muestras con N = 30, tomadas de una distribución normal (media = 50, sd = 25). Vamos a hacer una simulación con 1000 repeticiones. En cada repetición, comparamos la media muestral con una media poblacional de 50. En promedio, no debería haber diferencia. La <a href="#fig-6nullt" class="quarto-xref">Figure&nbsp;<span>7.10</span></a> es la distribución nula que estamos simulando.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6nullt" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6nullt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6nullt-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6nullt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.10: Distribución de valores t bajo la nula. Estos son los t que surgen solo por azar.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6flatp" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6flatp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6flatp-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6flatp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.11: La distribución de valores p observados es plana bajo la nula.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Buenísimo. Vemos una distribución <em>t</em>, que se parece a una <em>t</em> como debe ser. Y también vemos la distribución de valores <em>p</em>. Esto nos muestra qué tan seguido obtenemos valores <em>t</em> de distintos tamaños.</p>
<p>Capaz te llame la atención que la distribución de <em>p</em> es <strong>plana</strong> bajo la nula (que es lo que estamos simulando). Esto significa que tenés <strong>la misma probabilidad</strong> de obtener un valor <em>p</em> entre 0 y 0.05 que de obtener uno entre 0.90 y 0.95. Esos rangos tienen un 5% de ancho, así que contienen la <strong>misma cantidad de valores t por definición</strong>.</p>
<p>Acá va otra forma de hacer la misma simulación en R, usando la función <code>replicate</code> en vez de un <code>for</code>:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6simtsRep" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6simtsRep-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6simtsRep-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6simtsRep-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.12: Simulando valores t en R.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6simpsRep" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6simpsRep-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6simpsRep-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6simpsRep-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.13: Simulando valores p en R.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="simular-una-prueba-t-de-muestras-pareadas" class="level3" data-number="7.6.2">
<h3 data-number="7.6.2" class="anchored" data-anchor-id="simular-una-prueba-t-de-muestras-pareadas"><span class="header-section-number">7.6.2</span> Simular una prueba t de muestras pareadas</h3>
<p>El código de abajo está preparado para tomar 10 puntajes de la condición A y 10 de la condición B, ambos desde la misma distribución normal. La simulación se corre 1000 veces, y se guardan los <em>t</em> y <em>p</em> para graficarlos luego.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>guarda_ps <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>guarda_ts <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>) {</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  condicion_A <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">10</span>,<span class="dv">5</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  condicion_B <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">10</span>,<span class="dv">5</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  diferencias <span class="ot">&lt;-</span> condicion_A <span class="sc">-</span> condicion_B</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(diferencias, <span class="at">mu =</span> <span class="dv">0</span>)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  guarda_ps[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>p.value</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  guarda_ts[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>statistic</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6simps1000" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6simps1000-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6simps1000-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6simps1000-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.14: 1000 valores t simulados de la distribución nula
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6simts1000" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6simts1000-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6simts1000-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6simts1000-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.15: 1000 valores p simulados de la distribución nula
</figcaption>
</figure>
</div>
</div>
</div>
<p>Según la simulación, cuando <strong>no hay diferencias</strong> entre las condiciones y las muestras provienen de <strong>la misma distribución</strong>, se obtienen estas dos distribuciones para <em>t</em> y <em>p</em>. Una vez más, muestran cómo se comporta la <strong>distribución nula de ausencia de diferencias</strong>.</p>
<p>En cualquiera de estas simulaciones, si rechazaras la hipótesis nula (que la diferencia se debe al azar), estarías cometiendo un <strong>error tipo I</strong>. Si fijás tu criterio alfa en <span class="math inline">\(alpha = .05\)</span>, podemos preguntar cuántos errores tipo I se cometieron en estas 1000 simulaciones. La respuesta es:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(guarda_ps[guarda_ps <span class="sc">&lt;</span> .<span class="dv">05</span>])</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 59</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(guarda_ps[guarda_ps <span class="sc">&lt;</span> .<span class="dv">05</span>]) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0.059</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Resulta que cometimos 59. La expectativa a largo plazo es una tasa de error tipo I del 5% (si tu alfa es .05).</p>
<p>¿Qué pasa si en realidad <strong>sí hay una diferencia</strong> en los datos simulados? Probemos con una condición que tenga una media mayor que la otra:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>guarda_ps <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>guarda_ts <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>) {</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  condicion_A <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="dv">10</span>, <span class="dv">5</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  condicion_B <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="dv">13</span>, <span class="dv">5</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  diferencias <span class="ot">&lt;-</span> condicion_A <span class="sc">-</span> condicion_B</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(diferencias, <span class="at">mu =</span> <span class="dv">0</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  guarda_ps[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>p.value</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  guarda_ts[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>statistic</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6simtruets" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6simtruets-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6simtruets-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6simtruets-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.16: 1000 valores t cuando hay una diferencia real
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6simtrueps" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6simtrueps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6simtrueps-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6simtrueps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.17: 1000 valores p cuando hay una diferencia real
</figcaption>
</figure>
</div>
</div>
</div>
<p>Ahora podés ver que la distribución de valores <em>p</em> está <strong>sesgada hacia la izquierda</strong>. Esto pasa porque cuando hay un efecto real, obtenés valores <em>p</em> menores a .05 <strong>más seguido</strong>. O sea, obtenés valores <em>t</em> mayores de lo que obtendrías si no hubiera diferencias.</p>
<p>En este caso, <strong>no estarías cometiendo un error tipo I</strong> si rechazás la nula cuando <em>p</em> es menor a .05. ¿Cuántas veces lo harías de las 1000 simulaciones?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(guarda_ps[guarda_ps <span class="sc">&lt;</span> .<span class="dv">05</span>])</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 231</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(guarda_ps[guarda_ps <span class="sc">&lt;</span> .<span class="dv">05</span>]) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0.231</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Obtuvimos 231 simulaciones donde <em>p</em> fue menor a .05, lo cual representa 0.231 experimentos. Si fueras el investigador, ¿te gustaría correr un experimento que solo tiene éxito 0.231 del tiempo? Yo no. Yo correría un experimento mejor.</p>
<p>¿Cómo harías una mejor simulación? Bueno, podés aumentar <em>n</em>, el número de sujetos. Aumentemos <em>n</em> de 10 a 100 y veamos qué pasa con la cantidad de experimentos “significativos”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>guarda_ps <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>guarda_ts <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>) {</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  condicion_A <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="dv">10</span>, <span class="dv">5</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  condicion_B <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="dv">13</span>, <span class="dv">5</span>)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  diferencias <span class="ot">&lt;-</span> condicion_A <span class="sc">-</span> condicion_B</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(diferencias, <span class="at">mu =</span> <span class="dv">0</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  guarda_ps[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>p.value</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  guarda_ts[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>statistic</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6simtsB" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6simtsB-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6simtsB-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6simtsB-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.18: 1000 valores t para n = 100, cuando hay un efecto real
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<pre><code>#&gt; [1] 990
#&gt; [1] 0.99</code></pre>
<div class="cell-output-display">
<div id="fig-6simpsB" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6simpsB-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6simpsB-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6simpsB-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.19: 1000 valores p para n = 100, cuando hay un efecto real
</figcaption>
</figure>
</div>
</div>
</div>
<p>Genial, ahora casi todos los experimentos muestran un valor <em>p</em> menor a .05 (usando un test bilateral, que es la opción por defecto en R). ¿Ves? Podés usar este proceso de simulación para determinar <strong>cuántos sujetos necesitás</strong> para detectar confiablemente tu efecto.</p>
</section>
<section id="simular-una-prueba-t-de-muestras-independientes" class="level3" data-number="7.6.3">
<h3 data-number="7.6.3" class="anchored" data-anchor-id="simular-una-prueba-t-de-muestras-independientes"><span class="header-section-number">7.6.3</span> Simular una prueba t de muestras independientes</h3>
<p>Solo cambiá la función <code>t.test</code> de esta forma… esto es para simular bajo la nula, asumiendo que <strong>no hay diferencia entre los grupos</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>guarda_ps <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>guarda_ts <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>) {</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  group_A <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="dv">10</span>, <span class="dv">5</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  group_B <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="dv">10</span>, <span class="dv">5</span>)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(group_A, group_B, <span class="at">paired =</span> <span class="cn">FALSE</span>, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  guarda_ps[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>p.value</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  guarda_ts[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>statistic</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6simtsC" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6simtsC-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6simtsC-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6simtsC-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.20: 1000 valores t para n = 100, cuando hay un efecto real
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<pre><code>#&gt; [1] 60
#&gt; [1] 0.06</code></pre>
<div class="cell-output-display">
<div id="fig-6simpsC" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6simpsC-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6simpsC-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6simpsC-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.21: 1000 valores p para n = 100, cuando hay un efecto real
</figcaption>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="videos" class="level2" data-number="7.7">
<h2 data-number="7.7" class="anchored" data-anchor-id="videos"><span class="header-section-number">7.7</span> Videos</h2>
<section id="test-de-una-o-dos-colas" class="level3" data-number="7.7.1">
<h3 data-number="7.7.1" class="anchored" data-anchor-id="test-de-una-o-dos-colas"><span class="header-section-number">7.7.1</span> Test de una o dos colas</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/PuoGsguuY30" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-mehr20165" class="csl-entry" role="listitem">
Mehr, Samuel A, Lee Ann Song, and Elizabeth S Spelke. 2016. <span>“For 5-Month-Old Infants, Melodies Are Social.”</span> <em>Psychological Science</em> 27 (4): 486–501. <a href="https://doi.org/10.1177/0956797615626691">https://doi.org/10.1177/0956797615626691</a>.
</div>
<div id="ref-Student1908" class="csl-entry" role="listitem">
Student, A. 1908. <span>“The Probable Error of a Mean.”</span> <em>Biometrika</em> 6: 1–2.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/almadana\.github\.io\/libro_cuanti\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05-Foundation_Inference.html" class="pagination-link" aria-label="Fundamentos de la inferencia">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Fundamentos de la inferencia</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./06b-chi_cuadrado.html" class="pagination-link" aria-label="Pruebas chi cuadrado">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Pruebas chi cuadrado</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/almadana/libro_cuanti/edit/master/06-ttests.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>