project:
  type: book
  output-dir: docs

book:
  title: "Respondiendo preguntas con datos"
  cover-image: imgs/TextbookCover.png
  author:
    - "Álvaro Cabana"
    - "Clementina Tomás"
    - "Matthew J. C. Crump"
    - "Danielle J. Navarro"
    - "Jeffrey Suzuki"
  date: "2018-09-01"
  abstract: "Un libro gratis que introduce la estadística a nivel de grado para psicología, incluye un manual de laboratorio, y una web del curso. Licensia: CC BY SA 4.0"
  chapters:
    - index.qmd
    - 01-Science_Data.qmd
    - 02-Describing_Data.qmd
    - 02b-tablas_final.qmd
    - 03-Correlation.qmd
    - 04-SamplesPopulations.qmd
    - 05-Foundation_Inference.qmd
    - 06-ttests.qmd
    - 06b-chi_cuadrado.qmd
    - 07-ANOVA.qmd
    #- 08-RMANOVA.qmd
    #- 09-FactorialANOVA.qmd
    #- 10-MixedANOVA.qmd
    #- 11-Simulation.qmd
    #- 12-Thinking.qmd
    - 13-Gifs.qmd
    - references.qmd
  site-url: https://almadana.github.io/libro_cuanti/
  repo-url: https://github.com/almadana/libro_cuanti/
  repo-branch: master
  repo-actions: [edit]
  google-analytics: "G-1116FZ99DZ"
  open-graph: true
  twitter-card:
    site: "@MattCrumpLab"
    description: "A free textbook teaching introductory statistics for undergraduates in psychology, including a lab manual, and course website. Licensed on CC BY SA 4.0"
    card-style: "summary"
    image: imgs/TextbookCover.png

bibliography: [StatisticsTextbook.bib]

format:
  html:
    theme: cosmo
    css: cuantistats.css
  pdf:
    documentclass: scrreprt

editor: visual

execute:
  cache: true
