<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Matthew J. C. Crump">

<title>6&nbsp; Fundamentos de la inferencia – Respondiendo preguntas con datos</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06-ttests.html" rel="next">
<link href="./04-SamplesPopulations.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-1116FZ99DZ"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-1116FZ99DZ', { 'anonymize_ip': true});
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="cuantistats.css">
<meta property="og:title" content="6&nbsp; Fundamentos de la inferencia – Respondiendo preguntas con datos">
<meta property="og:description" content="Traducido al español rioplatense por ChatGPT4-o bajo la supervisión de Álvaro Cabana.">
<meta property="og:site_name" content="Respondiendo preguntas con datos">
<meta name="twitter:title" content="6&nbsp; Fundamentos de la inferencia – Respondiendo preguntas con datos">
<meta name="twitter:description" content="A free textbook teaching introductory statistics for undergraduates in psychology, including a lab manual, and course website. Licensed on CC BY SA 4.0">
<meta name="twitter:image" content="https://almadana.github.io/libro_cuanti/imgs/TextbookCover.png">
<meta name="twitter:site" content="@MattCrumpLab">
<meta name="twitter:card" content="summary">
<meta name="twitter:image-height" content="1310">
<meta name="twitter:image-width" content="916">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-Foundation_Inference.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Fundamentos de la inferencia</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Respondiendo preguntas con datos</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/almadana/libro_cuanti/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Science_Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">¿Por qué estadística?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Describing_Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describir los datos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02b-tablas_final.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Tablas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Correlación</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-SamplesPopulations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Probabilidad, muestreo y estimación</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Foundation_Inference.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Fundamentos de la inferencia</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-ttests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Pruebas t</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06b-chi_cuadrado.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Pruebas chi cuadrado</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-Gifs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">GIFs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#breve-repaso-de-los-experimentos" id="toc-breve-repaso-de-los-experimentos" class="nav-link active" data-scroll-target="#breve-repaso-de-los-experimentos"><span class="header-section-number">6.1</span> Breve repaso de los experimentos</a></li>
  <li><a href="#los-datos-provienen-de-una-distribución" id="toc-los-datos-provienen-de-una-distribución" class="nav-link" data-scroll-target="#los-datos-provienen-de-una-distribución"><span class="header-section-number">6.2</span> Los datos provienen de una distribución</a>
  <ul class="collapse">
  <li><a href="#distribución-uniforme" id="toc-distribución-uniforme" class="nav-link" data-scroll-target="#distribución-uniforme"><span class="header-section-number">6.2.1</span> Distribución uniforme</a></li>
  <li><a href="#no-todas-las-muestras-son-iguales-de-hecho-suelen-ser-bastante-distintas" id="toc-no-todas-las-muestras-son-iguales-de-hecho-suelen-ser-bastante-distintas" class="nav-link" data-scroll-target="#no-todas-las-muestras-son-iguales-de-hecho-suelen-ser-bastante-distintas"><span class="header-section-number">6.2.2</span> No todas las muestras son iguales — de hecho, suelen ser bastante distintas</a></li>
  <li><a href="#las-muestras-grandes-se-parecen-más-a-la-distribución-de-la-que-provienen" id="toc-las-muestras-grandes-se-parecen-más-a-la-distribución-de-la-que-provienen" class="nav-link" data-scroll-target="#las-muestras-grandes-se-parecen-más-a-la-distribución-de-la-que-provienen"><span class="header-section-number">6.2.3</span> Las muestras grandes se parecen más a la distribución de la que provienen</a></li>
  </ul></li>
  <li><a href="#hay-una-diferencia" id="toc-hay-una-diferencia" class="nav-link" data-scroll-target="#hay-una-diferencia"><span class="header-section-number">6.3</span> ¿Hay una diferencia?</a>
  <ul class="collapse">
  <li><a href="#el-azar-puede-producir-diferencias" id="toc-el-azar-puede-producir-diferencias" class="nav-link" data-scroll-target="#el-azar-puede-producir-diferencias"><span class="header-section-number">6.3.1</span> El azar puede producir diferencias</a></li>
  <li><a href="#las-diferencias-causadas-por-el-azar-se-pueden-simular" id="toc-las-diferencias-causadas-por-el-azar-se-pueden-simular" class="nav-link" data-scroll-target="#las-diferencias-causadas-por-el-azar-se-pueden-simular"><span class="header-section-number">6.3.2</span> Las diferencias causadas por el azar se pueden simular</a></li>
  </ul></li>
  <li><a href="#el-azar-hace-que-algunas-diferencias-sean-más-probables-que-otras" id="toc-el-azar-hace-que-algunas-diferencias-sean-más-probables-que-otras" class="nav-link" data-scroll-target="#el-azar-hace-que-algunas-diferencias-sean-más-probables-que-otras"><span class="header-section-number">6.4</span> El azar hace que algunas diferencias sean más probables que otras</a></li>
  <li><a href="#la-prueba-de-crump" id="toc-la-prueba-de-crump" class="nav-link" data-scroll-target="#la-prueba-de-crump"><span class="header-section-number">6.5</span> La prueba de Crump</a>
  <ul class="collapse">
  <li><a href="#métodos-intuitivos" id="toc-métodos-intuitivos" class="nav-link" data-scroll-target="#métodos-intuitivos"><span class="header-section-number">6.5.1</span> Métodos intuitivos</a></li>
  <li><a href="#parte-1-intuición-basada-en-frecuencia-sobre-ocurrencias" id="toc-parte-1-intuición-basada-en-frecuencia-sobre-ocurrencias" class="nav-link" data-scroll-target="#parte-1-intuición-basada-en-frecuencia-sobre-ocurrencias"><span class="header-section-number">6.5.2</span> Parte 1: Intuición basada en frecuencia sobre ocurrencias</a></li>
  <li><a href="#parte-2-simulando-el-azar" id="toc-parte-2-simulando-el-azar" class="nav-link" data-scroll-target="#parte-2-simulando-el-azar"><span class="header-section-number">6.5.3</span> Parte 2: Simulando el azar</a></li>
  <li><a href="#parte-3-juicio-y-toma-de-decisiones" id="toc-parte-3-juicio-y-toma-de-decisiones" class="nav-link" data-scroll-target="#parte-3-juicio-y-toma-de-decisiones"><span class="header-section-number">6.5.4</span> Parte 3: Juicio y toma de decisiones</a></li>
  <li><a href="#zonas-grises" id="toc-zonas-grises" class="nav-link" data-scroll-target="#zonas-grises"><span class="header-section-number">6.5.5</span> Zonas grises</a></li>
  <li><a href="#parte-4-diseño-experimental" id="toc-parte-4-diseño-experimental" class="nav-link" data-scroll-target="#parte-4-diseño-experimental"><span class="header-section-number">6.5.6</span> Parte 4: Diseño experimental</a></li>
  <li><a href="#parte-5-yo-tengo-el-poder" id="toc-parte-5-yo-tengo-el-poder" class="nav-link" data-scroll-target="#parte-5-yo-tengo-el-poder"><span class="header-section-number">6.5.7</span> Parte 5: Yo tengo el poder</a></li>
  <li><a href="#resumen-de-la-prueba-de-crump" id="toc-resumen-de-la-prueba-de-crump" class="nav-link" data-scroll-target="#resumen-de-la-prueba-de-crump"><span class="header-section-number">6.5.8</span> Resumen de la prueba de Crump</a></li>
  </ul></li>
  <li><a href="#la-prueba-de-aleatorización-o-prueba-de-permutación" id="toc-la-prueba-de-aleatorización-o-prueba-de-permutación" class="nav-link" data-scroll-target="#la-prueba-de-aleatorización-o-prueba-de-permutación"><span class="header-section-number">6.6</span> La prueba de aleatorización (o prueba de permutación)</a>
  <ul class="collapse">
  <li><a href="#ejemplo-ficticio-masticar-chicle-mejora-tus-calificaciones" id="toc-ejemplo-ficticio-masticar-chicle-mejora-tus-calificaciones" class="nav-link" data-scroll-target="#ejemplo-ficticio-masticar-chicle-mejora-tus-calificaciones"><span class="header-section-number">6.6.1</span> Ejemplo ficticio: ¿masticar chicle mejora tus calificaciones?</a></li>
  <li><a href="#lo-que-nos-queda-hasta-ahora" id="toc-lo-que-nos-queda-hasta-ahora" class="nav-link" data-scroll-target="#lo-que-nos-queda-hasta-ahora"><span class="header-section-number">6.6.2</span> Lo que nos queda hasta ahora</a></li>
  </ul></li>
  <li><a href="#videos" id="toc-videos" class="nav-link" data-scroll-target="#videos"><span class="header-section-number">6.7</span> Videos</a>
  <ul class="collapse">
  <li><a href="#hipótesis-nula-y-alternativa" id="toc-hipótesis-nula-y-alternativa" class="nav-link" data-scroll-target="#hipótesis-nula-y-alternativa"><span class="header-section-number">6.7.1</span> Hipótesis nula y alternativa</a></li>
  <li><a href="#tipos-de-errores" id="toc-tipos-de-errores" class="nav-link" data-scroll-target="#tipos-de-errores"><span class="header-section-number">6.7.2</span> Tipos de Errores</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/almadana/libro_cuanti/edit/master/05-Foundation_Inference.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Fundamentos de la inferencia</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Matthew J. C. Crump </p>
          </div>
  </div>
    
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Notas</div>
    Traducido al español rioplatense por ChatGPT4-o bajo la supervisión de Álvaro Cabana.
  </div>
</div>


</header>


<blockquote class="blockquote">
<p>Los datos y los conjuntos de datos no son objetivos; son creaciones del diseño humano. Les damos voz a los números, inferimos a partir de ellos, y definimos su significado a través de nuestras interpretaciones. — Katie Crawford</p>
</blockquote>
<p>Hasta ahora hemos estado hablando sobre cómo describir datos y buscar posibles relaciones entre las cosas que medimos. Comenzamos con el problema de tener demasiados números y discutimos cómo podían resumirse con estadísticas descriptivas y comunicarse a través de gráficos. También analizamos la idea de relaciones entre cosas. Si una cosa causa un cambio en otra, entonces, si medimos cómo una varía, deberíamos ver que la otra también varía, o que cambia de forma sistemática como consecuencia de la primera. Al final del capítulo sobre correlación, mostramos cómo las correlaciones —que implican una relación entre dos cosas— son muy difíciles de interpretar. ¿Por qué? Porque una correlación observada puede ser causada por una tercera variable oculta, o puede ser un hallazgo espurio “causado” por el azar.</p>
<p>Ahora comenzamos nuestro recorrido por la <strong>estadística inferencial</strong>. Estas son herramientas que se utilizan para hacer inferencias sobre de dónde provienen nuestros datos, y para hacer inferencias sobre qué causa qué.</p>
<p>En este capítulo vamos a presentar algunas ideas fundamentales. Nos mantendremos mayormente en un nivel conceptual, y usaremos muchas simulaciones, como hicimos en los capítulos anteriores. En los capítulos siguientes formalizaremos las intuiciones desarrolladas acá para explicar cómo funcionan algunas estadísticas inferenciales comunes.</p>
<section id="breve-repaso-de-los-experimentos" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="breve-repaso-de-los-experimentos"><span class="header-section-number">6.1</span> Breve repaso de los experimentos</h2>
<p>En el capítulo uno hablamos sobre métodos de investigación y experimentos. Los experimentos son una manera estructurada de recolectar datos que puede permitir inferencias sobre causalidad. Si quisiéramos saber si algo como ver videos de gatos en YouTube aumenta la felicidad, necesitaríamos un experimento. Ya vimos que simplemente buscar un montón de personas, medir cuántas horas ven videos de gatos y su nivel de felicidad, y correlacionar ambas cosas <strong>no permite inferencias causales</strong>. Por ejemplo, el flujo causal podría estar invertido: tal vez <strong>ser feliz causa</strong> que la gente quiera mirar más videos de gatos. Necesitamos un experimento.</p>
<p>Un experimento tiene dos partes: una manipulación y una medición. La <strong>manipulación</strong> está bajo el control de quien realiza el experimento. Las manipulaciones también se llaman <strong>variables independientes</strong>. Por ejemplo, podríamos manipular el tiempo dedicado a mirar videos de gatos: 1 hora versus 2 horas. La <strong>medición</strong> es el dato que se recolecta. Podríamos medir cuán feliz se siente una persona después de ver videos de gatos, usando una escala del 1 al 100. Las mediciones también se llaman <strong>variables dependientes</strong>. Entonces, en un experimento básico como el que estamos considerando, recogemos medidas de felicidad de personas asignadas a una de dos condiciones experimentales definidas por la variable independiente. Supongamos que realizamos el experimento con 50 participantes. A 25 personas se las asigna al azar para ver 1 hora de videos de gatos, y a las otras 25 se las asigna al azar para ver 2 horas. Luego, medimos cuán felices se sienten al final del experimento.</p>
<p>¿Qué deberíamos mirar en los datos? Si mirar videos de gatos causara un cambio en la felicidad, entonces esperaríamos que las medidas de felicidad de las personas que vieron 1 hora de videos de gatos fueran diferentes de las medidas de aquellas que vieron 2 horas. Si mirar videos de gatos no produjera ningún cambio en la felicidad, entonces no deberíamos encontrar diferencias en las medidas de felicidad entre las dos condiciones. Las fuerzas causales provocan cambios, y el experimento está diseñado para detectar ese cambio.</p>
<p>Ahora podemos plantear una gran pregunta general: <strong>¿cómo sabemos si los datos cambiaron entre condiciones?</strong> Si podemos estar razonablemente seguros de que hubo un cambio entre condiciones, entonces podemos inferir que nuestra manipulación causó un cambio en la medición. Si no podemos estar seguros de que hubo un cambio, entonces <strong>no podemos</strong> inferir que la manipulación haya causado una diferencia. Necesitamos construir herramientas que nos permitan <strong>detectar cambios</strong>, para poder reconocer un cambio cuando ocurra.</p>
<p>“Pará un poco, si solo estamos buscando un cambio, ¿no sería fácil ver eso mirando los números y viendo si son diferentes? ¿Qué tiene de difícil eso?” Buena pregunta. Ahora necesitamos hacer un desvío. La respuesta breve es que <strong>siempre</strong> va a haber cambio en los datos (recordá la varianza).</p>
</section>
<section id="los-datos-provienen-de-una-distribución" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="los-datos-provienen-de-una-distribución"><span class="header-section-number">6.2</span> Los datos provienen de una distribución</h2>
<p>En el capítulo anterior hablamos sobre muestras y distribuciones, y sobre la idea de que podés tomar muestras desde una distribución. Así que, de ahora en más, cada vez que veas un conjunto de números deberías preguntarte: “¿De dónde vienen estos números?”. ¿Qué causó que algunos tipos de números aparecieran más que otros? La respuesta a esta pregunta nos lleva de nuevo al mundo abstracto de las distribuciones.</p>
<p>Una <strong>distribución</strong> es un lugar de donde pueden salir los números. La distribución establece las restricciones: determina qué números es probable que ocurran y cuáles no. Las distribuciones son ideas abstractas, pero pueden hacerse concretas, y podemos representarlas con dibujos —como ya has visto antes— llamados histogramas.</p>
<p>Lo que viene a continuación puede parecer un poco repetitivo con respecto al capítulo anterior. Volvemos a mirar muestreo de números desde una distribución uniforme. Mostramos que las muestras individuales pueden lucir bastante diferentes entre sí. Gran parte del comienzo de este capítulo ya te va a resultar familiar, pero llevamos los conceptos en una dirección un poco distinta: la dirección es cómo hacer inferencias sobre el papel del azar en tu experimento.</p>
<section id="distribución-uniforme" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="distribución-uniforme"><span class="header-section-number">6.2.1</span> Distribución uniforme</h3>
<p>Como recordatorio del capítulo anterior, la <a href="#fig-5unifagain" class="quarto-xref">Figura&nbsp;<span>6.1</span></a> muestra que la forma de una distribución uniforme es completamente plana.</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5unifagain_c3d275d950043f5a659b4cd7b06c4c95">
<div class="cell-output-display">
<div id="fig-5unifagain" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5unifagain-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-Foundation_Inference_files/figure-html/fig-5unifagain-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5unifagain-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.1: Distribución uniforme que muestra que los números del 1 al 10 tienen la misma probabilidad de ser muestreados
</figcaption>
</figure>
</div>
</div>
</div>
<p>OK, eso no parece gran cosa. ¿Qué está pasando acá? El eje y está etiquetado como <code>Probabilidad</code>, y va de 0 a 1. El eje x está etiquetado como <code>Número</code>, y va del 1 al 10. Hay una línea horizontal atravesando el gráfico. Esa línea indica la probabilidad de cada número del 1 al 10. Notá que la línea es plana. Esto significa que <strong>todos los números tienen la misma probabilidad de ocurrir</strong>. Más específicamente, hay 10 números del 1 al 10 (1,2,3,4,5,6,7,8,9,10), y todos tienen la misma chance de aparecer. 1 dividido 10 es 0,1, que es la probabilidad indicada por la línea horizontal.</p>
<p>“¿Y qué con eso?” Imaginá que esta distribución uniforme es una máquina generadora de números. Escupe números, pero escupe <strong>cada número con la probabilidad indicada por la línea</strong>. Si esta distribución comenzara a generar números, escupiría un 10% de unos, un 10% de doses, un 10% de treses, y así sucesivamente, hasta un 10% de dieces. ¿Querés ver cómo se vería eso? Hagamos que escupa 100 números y pongámoslos en la <a href="#tbl-5100rand" class="quarto-xref">Tabla&nbsp;<span>6.1</span></a>.</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/tbl-5100rand_45db0cf74b2b30a9bca7b613edaba8a5">
<div id="tbl-5100rand" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-hash="05-Foundation_Inference_cache/html/tbl-5100rand_45db0cf74b2b30a9bca7b613edaba8a5">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-5100rand-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;6.1: 100 números muestreados aleatoriamente de una distribución uniforme.
</figcaption>
<div aria-describedby="tbl-5100rand-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">7</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: right;">9</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">7</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">3</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Usamos la distribución uniforme para generar estos números. Formalmente, a esto lo llamamos <strong>muestreo</strong> desde una <strong>distribución</strong>. Muestrear es lo que hacés en el supermercado cuando hay comida para degustar. Podés seguir tomando más. Sin embargo, si tomás <strong>todas</strong> las muestras, lo que tenés se llama <strong>población</strong>. Vamos a hablar más sobre muestras y poblaciones más adelante. Como usamos la distribución uniforme para generar los números, ya sabemos de dónde vienen. Pero por ahora, podemos fingir que alguien aparece en tu puerta, te muestra estos números, y vos te preguntás de dónde salieron. ¿Podés decir, solo mirando los números, que provienen de una distribución uniforme?</p>
<p>¿Qué deberías observar? Quizás quieras saber si todos los números ocurren con <strong>aproximadamente la misma frecuencia</strong> —después de todo, eso es lo que <strong>debería</strong> pasar, ¿no? Es decir, si cada número tiene la misma chance de ocurrir, deberíamos ver que <strong>cada número ocurre más o menos la misma cantidad de veces</strong>. Ya sabemos qué es un histograma, así que podemos poner nuestra muestra de 100 números en un histograma y ver cómo se distribuyen los conteos. Si todos los números del 1 al 10 aparecen con igual frecuencia, entonces cada número individual debería aparecer unas 10 veces. La <a href="#fig-5histunif" class="quarto-xref">Figura&nbsp;<span>6.2</span></a> muestra el histograma:</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5histunif_a54bf8bec11c0ec060e130275f3b5929">
<div class="cell-output-display">
<div id="fig-5histunif" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5histunif-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-Foundation_Inference_files/figure-html/fig-5histunif-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5histunif-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.2: Histograma de 100 números muestreados aleatoriamente de una distribución uniforme que contiene los enteros del 1 al 10
</figcaption>
</figure>
</div>
</div>
</div>
<p>Uy… como podés ver, <strong>no</strong> todos los números ocurrieron exactamente 10 veces. Las barras no tienen toda la misma altura. Esto muestra que el muestreo aleatorio de números desde esta distribución <strong>no garantiza</strong> que los números muestrados se vean exactamente como la distribución original. A esto lo llamamos <strong>error muestral</strong>, o <strong>variabilidad del muestreo</strong>.</p>
</section>
<section id="no-todas-las-muestras-son-iguales-de-hecho-suelen-ser-bastante-distintas" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="no-todas-las-muestras-son-iguales-de-hecho-suelen-ser-bastante-distintas"><span class="header-section-number">6.2.2</span> No todas las muestras son iguales — de hecho, suelen ser bastante distintas</h3>
<p>Veamos más de cerca el error muestral. Vamos a tomar una muestra de 20 números de la distribución uniforme. Deberíamos esperar que cada número entre 1 y 10 ocurra unas dos veces. Como antes, esta expectativa puede visualizarse con un histograma.</p>
<p>Para tener una mejor idea de la variabilidad muestral, repitamos ese proceso <strong>diez veces</strong>. La <a href="#fig-5manysamples" class="quarto-xref">Figura&nbsp;<span>6.3</span></a> muestra 10 histogramas, cada uno representando una muestra distinta de 20 números:</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5manysamples_656e30a9011c3e34d3e8afcd5ee1fe66">
<div class="cell-output-display">
<div id="fig-5manysamples" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5manysamples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-Foundation_Inference_files/figure-html/fig-5manysamples-1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5manysamples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.3: Histogramas de 10 muestras distintas de la distribución uniforme. Cada muestra contiene 20 números. Todos los histogramas se ven bastante distintos. Las diferencias entre las muestras se deben al error muestral o al azar.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Probablemente notes enseguida que ninguno de los histogramas es igual. Aunque estamos tomando aleatoriamente 20 números de la misma distribución uniforme, <strong>cada muestra de 20 números resulta diferente</strong>. Esto es <strong>variabilidad muestral</strong>, o <strong>error de muestreo</strong>.</p>
<p>La <a href="#fig-5expectedUnif" class="quarto-xref">Figura&nbsp;<span>6.4</span></a> muestra una versión animada del proceso de elegir repetidamente 20 números aleatorios nuevos y graficar un histograma. La línea horizontal muestra la forma plana de la distribución uniforme. La línea cruza el eje y en el valor 2; y esperamos que cada número (del 1 al 10) ocurra unas 2 veces en una muestra de 20. Sin embargo, cada muestra varía bastante, debido al azar.</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5expectedUnif_3afb2cb154ee922603c09837ba8aa403">
<div class="cell-output-display">
<div id="fig-5expectedUnif" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5expectedUnif-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="imgs/gifs/sampleUnifExpected-1_es.gif" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5expectedUnif-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.4: Animación de histogramas para diferentes muestras de 20 valores de una distribución uniforme (números del 1 al 10). Las líneas negras muestran la cantidad esperada de veces que debería aparecer cada número. El hecho de que no todos los números aparezcan exactamente 2 veces ilustra el error asociado al muestreo.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Observar los histogramas anteriores nos muestra que puede ser difícil averiguar de dónde vinieron nuestros números. En el mundo real, nuestras mediciones son muestras. Por lo general, solo tenemos el lujo de obtener <strong>una única muestra</strong> de mediciones, en lugar de repetirlas 10 veces o más. Si mirás los histogramas, verás que algunos de ellos parecen haber salido de una distribución uniforme: la mayoría de las barras están cerca de 2, y todas más o menos alineadas. Pero si te tocara otra muestra distinta, podrías ver un histograma muy irregular, con algunos números ocurriendo mucho más que otros. Eso podría hacerte pensar que esos números <strong>no</strong> provienen de una distribución uniforme (parecen demasiado irregulares). Pero recordá: <strong>todas</strong> estas muestras vinieron de una distribución uniforme. Así es como se ven las muestras tomadas de esa distribución. Esto es lo que el <strong>azar</strong> le hace a las muestras: introduce <strong>ruido</strong> en los datos individuales.</p>
</section>
<section id="las-muestras-grandes-se-parecen-más-a-la-distribución-de-la-que-provienen" class="level3" data-number="6.2.3">
<h3 data-number="6.2.3" class="anchored" data-anchor-id="las-muestras-grandes-se-parecen-más-a-la-distribución-de-la-que-provienen"><span class="header-section-number">6.2.3</span> Las muestras grandes se parecen más a la distribución de la que provienen</h3>
<p>Volvamos a la pregunta: ¿cuál de las dos muestras en <a href="#fig-5whichone" class="quarto-xref">Figura&nbsp;<span>6.5</span></a> te parece que vino de una distribución uniforme?</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5whichone_fbdab88cf594bdcdab702b2595062a35">
<div class="cell-output-display">
<div id="fig-5whichone" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5whichone-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-Foundation_Inference_files/figure-html/fig-5whichone-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5whichone-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.5: ¿Cuál de estas dos muestras proviene de una distribución uniforme?
</figcaption>
</figure>
</div>
</div>
</div>
<p>La respuesta es que <strong>ambas</strong> vinieron de una distribución uniforme. Pero ninguna <strong>parece</strong> que lo haya hecho.</p>
<p>¿Podemos mejorar las cosas y facilitar ver si una muestra proviene de una distribución uniforme? Sí, podemos. Lo único que necesitamos hacer es <strong>aumentar el tamaño de la muestra</strong>. A menudo usamos la letra <code>n</code> para referirnos al tamaño muestral. <code>n</code> es el número de observaciones en la muestra.</p>
<p>Así que aumentemos el número de observaciones en cada muestra, de 20 a 100. Vamos a crear 10 muestras (cada una con 100 observaciones), y a graficar un histograma para cada una. Todas estas muestras se extraen de la <strong>misma</strong> distribución uniforme. Esto significa que deberíamos esperar que <strong>cada número del 1 al 10 ocurra unas 10 veces</strong> en cada muestra. Los histogramas están en la <a href="#fig-5unifsamp100" class="quarto-xref">Figura&nbsp;<span>6.6</span></a>.</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5unifsamp100_e949f4773fce909fa4b0b6029e408851">
<div class="cell-output-display">
<div id="fig-5unifsamp100" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5unifsamp100-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-Foundation_Inference_files/figure-html/fig-5unifsamp100-1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5unifsamp100-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.6: Histogramas de diferentes muestras de una distribución uniforme. N = 1000 para cada muestra.
</figcaption>
</figure>
</div>
</div>
</div>
<p>De nuevo, la mayoría de estos histogramas no se ven muy planos, y todas las barras parecen ir hacia arriba o hacia abajo; además, no están exactamente en 10 cada una. Así que todavía estamos lidiando con el error muestral. Es un fastidio. Siempre está presente.</p>
<p>Aumentemos el <span class="math inline">\(N\)</span> por muestra de 100 a 1000. Deberíamos esperar que cada número aparezca unas 100 veces. ¿Qué sucede?</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5unifsamp1000_d661c16f2ad303b66325c6cb27c93ecc">
<div class="cell-output-display">
<div id="fig-5unifsamp1000" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5unifsamp1000-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-Foundation_Inference_files/figure-html/fig-5unifsamp1000-1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5unifsamp1000-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.7: Histogramas de diferentes muestras de una distribución uniforme. N = 100 para cada muestra.
</figcaption>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-5unifsamp1000" class="quarto-xref">Figura&nbsp;<span>6.7</span></a> muestra que los histogramas empiezan a aplanarse. Las barras todavía no están perfectamente en 100, porque sigue habiendo error muestral (siempre lo habrá). Pero si vieras un histograma que se ve plano y supieras que la muestra contiene muchas observaciones, podrías tener más confianza en que esos números provienen de una distribución uniforme.</p>
<p>Solo por diversión, hagamos muestras realmente grandes. Digamos, 100.000 observaciones por muestra. En ese caso, deberíamos esperar que cada número ocurra unas 10.000 veces. ¿Qué pasa?</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5sampunifALOT_41c30c6a85c61702514ee18cef8bfa1c">
<div class="cell-output-display">
<div id="fig-5sampunifALOT" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5sampunifALOT-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-Foundation_Inference_files/figure-html/fig-5sampunifALOT-1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5sampunifALOT-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.8: Histogramas de distintas muestras de una distribución uniforme. N = 100.000 para cada muestra.
</figcaption>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-5sampunifALOT" class="quarto-xref">Figura&nbsp;<span>6.8</span></a> muestra que los histogramas de cada muestra empiezan a parecerse entre sí. Todas tienen 100.000 observaciones, y eso le da suficiente oportunidad al azar para distribuir los números de manera más equitativa, asegurándose aproximadamente de que todos ocurran más o menos la misma cantidad de veces. Como podés ver, las barras están todas muy cerca de 10.000, que es donde deberían estar si la muestra realmente proviene de una distribución uniforme. De nuevo, <strong>no todas las barras tienen exactamente el mismo alto</strong> —todavía hay error muestral—, pero <strong>el patrón general</strong> es ahora mucho más claro. Cada número ocurre más o menos la misma cantidad de veces, y las diferencias entre muestras son mucho menores.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Consejo pro
</div>
</div>
<div class="callout-body-container callout-body">
<p>El patrón que muestra una muestra tiende a estabilizarse a medida que aumenta el tamaño muestral. Las muestras pequeñas pueden mostrar todo tipo de patrones, debido al error muestral (el azar).</p>
</div>
</div>
<p>Antes de volver al tema de los experimentos con el que comenzamos, hagamos dos preguntas más. Primero: ¿cuál de las dos muestras en <a href="#fig-5whichoneB" class="quarto-xref">Figura&nbsp;<span>6.9</span></a> creés que proviene de una distribución uniforme? Dato: cada una de estas muestras tiene 20 observaciones.</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5whichoneB_840a907e7adc3becb32f4357cf9430d0">
<div class="cell-output-display">
<div id="fig-5whichoneB" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5whichoneB-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-Foundation_Inference_files/figure-html/fig-5whichoneB-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5whichoneB-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.9: ¿Cuál de estas muestras proviene de una distribución uniforme?
</figcaption>
</figure>
</div>
</div>
</div>
<p>Si no estás muy segurx de la respuesta, es porque el <strong>error muestral</strong> (el azar) está “difuminando” los histogramas.</p>
<p>Acá va exactamente la misma pregunta, solo que esta vez tomamos <strong>1.000 observaciones por muestra</strong>. ¿Cuál histograma en <a href="#fig-5whichoneC" class="quarto-xref">Figura&nbsp;<span>6.10</span></a> creés que proviene de una distribución uniforme, y cuál no?</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5whichoneC_06cc4b18a876960bfeb6f7c6b4b6823c">
<div class="cell-output-display">
<div id="fig-5whichoneC" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5whichoneC-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-Foundation_Inference_files/figure-html/fig-5whichoneC-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5whichoneC-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.10: ¿Cuál de estas muestras proviene de una distribución uniforme?
</figcaption>
</figure>
</div>
</div>
</div>
<p>Ahora que aumentamos <code>N</code>, podemos ver que el patrón en cada muestra se vuelve más evidente. El histograma de la muestra 1 tiene barras cercanas a 100; no son perfectamente planas, pero <strong>se parece</strong> a una distribución uniforme. El histograma de la muestra 2 no es plano <strong>en absoluto</strong>.</p>
<p>¡Felicitaciones! Acabamos de hacer inferencias estadísticas sin usar fórmulas.</p>
<p>“¿Lo hicimos?” Sí: al mirar nuestras dos muestras, inferimos que la muestra 2 <strong>no</strong> provino de una distribución uniforme. También inferimos que la muestra 1 <strong>podría</strong> haber venido de una distribución uniforme. Fantástico. Este tipo de inferencias son las mismas que vamos a hacer durante el resto del curso.</p>
<p>Vamos a mirar algunos números, preguntarnos de dónde salieron, y luego organizarlos de forma tal que podamos hacer inferencias sobre <strong>el tipo de distribución</strong> de la que provinieron. Eso es todo.</p>
<!--
## Jugando con distribuciones

Hablar sobre algunas distribuciones distintas. Incluir app de Shiny.

SHINY APP acá
-->
</section>
</section>
<section id="hay-una-diferencia" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="hay-una-diferencia"><span class="header-section-number">6.3</span> ¿Hay una diferencia?</h2>
<p>Volvamos a los experimentos. En un experimento, queremos saber si una <strong>variable independiente</strong> (nuestra manipulación) <strong>causa un cambio</strong> en una <strong>variable dependiente</strong> (la medición). Si esto ocurre, entonces esperamos ver <strong>alguna diferencia</strong> en nuestra medición como función de la manipulación.</p>
<p>Considerá el ejemplo del interruptor de luz:</p>
<p><strong>Experimento del interruptor de luz</strong>: manipulás el interruptor hacia arriba (condición 1 de la variable independiente), la luz se enciende (medición). Manipulás el interruptor hacia abajo (condición 2 de la variable independiente), la luz se apaga (otra medición). La medición (la luz) <strong>cambia</strong> (se enciende o se apaga) como función de la manipulación (mover el interruptor hacia arriba o hacia abajo).</p>
<p>Podés ver el cambio en la medición entre condiciones, es tan obvio como el día y la noche. Entonces, cuando realizás una manipulación y <strong>ves la diferencia</strong> (el cambio) en tu medición, podés estar bastante seguro de que tu manipulación <strong>está causando el cambio</strong>.</p>
<blockquote class="blockquote">
<p>Nota: para ser cautos, podemos decir que <strong>“algo”</strong> relacionado con tu manipulación está causando el cambio; tal vez no sea exactamente lo que pensás que es, si tu manipulación es muy complicada e involucra muchos elementos en juego.</p>
</blockquote>
<section id="el-azar-puede-producir-diferencias" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="el-azar-puede-producir-diferencias"><span class="header-section-number">6.3.1</span> El azar puede producir diferencias</h3>
<p>¿Creés que el azar puede producir la apariencia de diferencias, incluso cuando en realidad no hay ninguna? Espero que sí. Ya mostramos que el proceso de muestreo de números desde una distribución es algo azaroso que genera muestras distintas. Las muestras diferentes son diferentes entre sí, así que sí: el azar puede producir diferencias. Y eso puede complicar la interpretación de los experimentos.</p>
<p>Hagamos un experimento ficticio en el que <strong>no esperamos encontrar diferencias</strong>, porque vamos a manipular algo que no debería generar ningún efecto. Este es el planteo:</p>
<p>Vos sos el experimentador y estás parado frente a una máquina expendedora de bolitas. Es muy grande, tiene miles de bolitas. El 50% son verdes y el 50% son rojas. Querés averiguar si sacar bolitas con la mano derecha o con la izquierda te hace sacar más bolitas verdes. Además, vas a estar con los ojos vendados todo el tiempo. La variable independiente es <strong>mano</strong>: derecha vs.&nbsp;izquierda. La variable dependiente es <strong>el color</strong> de cada bolita que sacás.</p>
<p>Realizás el experimento así:</p>
<ol type="1">
<li>te colocás una venda en los ojos.</li>
<li>sacás 10 bolitas al azar con la mano izquierda y las dejás a un lado.</li>
<li>sacás 10 bolitas al azar con la mano derecha y las dejás a otro lado.</li>
<li>contás cuántas bolitas verdes y cuántas rojas sacaste con cada mano.</li>
</ol>
<p>Esperamos que estés de acuerdo en que tus manos no pueden distinguir entre bolitas verdes y rojas. Si no estás de acuerdo, vamos a estipular además que las bolitas son completamente idénticas en todo, salvo en el color, así que sería imposible diferenciarlas usando el tacto. Entonces, ¿qué debería pasar en este experimento?</p>
<p>—“Eh… quizás saques 5 bolitas rojas y 5 verdes con la mano izquierda, y lo mismo con la derecha?” Más o menos, eso es lo que usualmente pasaría. Pero no es lo único que podría pasar. Acá tenés algunos datos de un experimento ficticio:</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/unnamed-chunk-2_19fc695c944c2c5fb5cf5dd3968d1342">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">mano</th>
<th style="text-align: right;">bolita</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">izquierda</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">izquierda</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">izquierda</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">izquierda</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">izquierda</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">izquierda</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">izquierda</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">izquierda</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">izquierda</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">izquierda</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">derecha</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">derecha</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">derecha</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">derecha</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">derecha</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">derecha</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">derecha</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">derecha</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">derecha</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">derecha</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>—“¿Qué estoy viendo acá?” Esta es una tabla en formato largo. Cada fila es una bolita. La primera columna indica con qué mano se sacó. La segunda indica qué tipo de bolita es. Vamos a decir que los valores <code>1</code> representan bolitas verdes y los <code>0</code> representan bolitas rojas.</p>
<p>Entonces… ¿la mano izquierda te hizo sacar más bolitas verdes que la mano derecha? Sería más fácil mirar los datos usando un gráfico de barras (<a href="#fig-5bolitaA" class="quarto-xref">Figura&nbsp;<span>6.11</span></a>). Para simplificar, vamos a contar solo las bolitas verdes (las otras necesariamente son rojas). Así que solo necesitamos sumar los unos; los ceros no suman nada.</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5bolitaA_8ff65e0fcce264699da77e474b77ae67">
<div class="cell-output-display">
<div id="fig-5bolitaA" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5bolitaA-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-Foundation_Inference_files/figure-html/fig-5bolitaA-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5bolitaA-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.11: Conteo de bolitas verdes seleccionadas al azar por cada mano.
</figcaption>
</figure>
</div>
</div>
</div>
<p>“¡Ah mirá! Las barras no son iguales. Una mano sacó más bolitas verdes que la otra. ¿Eso significa que una de tus manos secretamente sabe cómo encontrar bolitas verdes?” No.&nbsp;Es solo otro caso de <strong>error muestral</strong>, eso que también llamamos suerte o azar. La diferencia acá fue causada por el azar, no por la manipulación (es decir, por qué mano usaste).</p>
<blockquote class="blockquote">
<p><strong>¡Alerta de un problema importante para la inferencia!</strong> Hacemos experimentos para buscar diferencias, de modo que podamos inferir si nuestras manipulaciones causan cambios en nuestras mediciones. Sin embargo, este ejemplo demuestra que <strong>podemos encontrar diferencias solo por azar</strong>. Entonces, ¿cómo sabemos si una diferencia es real o simplemente fue causada por el azar?</p>
</blockquote>
</section>
<section id="las-diferencias-causadas-por-el-azar-se-pueden-simular" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="las-diferencias-causadas-por-el-azar-se-pueden-simular"><span class="header-section-number">6.3.2</span> Las diferencias causadas por el azar se pueden simular</h3>
<p>Recordá cuando mostramos que el azar puede producir correlaciones. También mostramos que el azar tiene <strong>limitaciones</strong> en su capacidad para producir correlaciones. Por ejemplo, el azar <strong>genera con más frecuencia correlaciones débiles que fuertes</strong>. ¿Te acordás de la “ventana del azar”? Antes descubrimos que las correlaciones que caen fuera de esa ventana son muy poco probables.</p>
<p>Podemos hacer lo mismo con las diferencias. Vamos a investigar exactamente qué puede hacer el azar en nuestro experimento. Una vez que sepamos de lo que el azar es capaz, vamos a estar en una mejor posición para juzgar si nuestra manipulación causó una diferencia, o si simplemente <strong>podría haber sido el azar</strong>.</p>
<p>Lo primero que vamos a hacer es simular que realizás el experimento de las bolitas <strong>10 veces seguidas</strong>. Eso va a producir 10 conjuntos distintos de resultados. La <a href="#fig-5bolitasims" class="quarto-xref">Figura&nbsp;<span>6.12</span></a> muestra gráficos de barras para cada repetición del experimento. Ahora podemos ver si la mano izquierda sacó más bolitas verdes que la derecha.</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5bolitasims_55e4edcb54c3f54265a9bbaa57db1a83">
<div class="cell-output-display">
<div id="fig-5bolitasims" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5bolitasims-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-Foundation_Inference_files/figure-html/fig-5bolitasims-1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5bolitasims-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.12: 10 repeticiones simuladas del experimento de sacar bolitas. Cada repetición da una respuesta ligeramente distinta. Cualquier diferencia entre las barras se debe al azar, o al error muestral. Esto muestra que el azar por sí solo puede producir diferencias, simplemente por el acto de muestrear.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Estos 10 experimentos nos permiten observar mejor lo que el azar puede hacer. Y también debería coincidir con tus expectativas: si todo está determinado por el azar (como lo diseñamos acá), entonces a veces tu mano izquierda va a sacar más bolitas verdes, otras veces será la derecha, y otras veces ambas sacarán la misma cantidad. ¿Correcto? Correcto.</p>
</section>
</section>
<section id="el-azar-hace-que-algunas-diferencias-sean-más-probables-que-otras" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="el-azar-hace-que-algunas-diferencias-sean-más-probables-que-otras"><span class="header-section-number">6.4</span> El azar hace que algunas diferencias sean más probables que otras</h2>
<p>Bien, ya vimos que el azar puede producir diferencias. Pero todavía no tenemos una buena idea de qué es lo que el azar usualmente puede o no puede hacer. Por ejemplo, si pudiéramos encontrar la “ventana de oportunidad” acá, podríamos descubrir que el azar normalmente <strong>no produce diferencias demasiado grandes</strong>. Y si supiéramos cuál es ese umbral, entonces, si realizamos un experimento y nuestra diferencia es más grande que lo que el azar puede producir, podríamos tener confianza en que <strong>no fue el azar</strong> lo que generó nuestra diferencia.</p>
<p>Pensemos en nuestra medición de bolitas verdes en términos de una <strong>diferencia</strong>. Por ejemplo, en cada experimento contamos las bolitas verdes para la mano izquierda y la derecha. Lo que realmente queremos saber es si hay una diferencia entre ellas. Así que podemos calcular el <strong>puntaje de diferencia</strong>. Vamos a definir ese puntaje de diferencia como: <strong># de bolitas verdes con la izquierda menos # de bolitas verdes con la derecha</strong>. Ahora vamos a simular este experimento mil veces. Cada vez, vamos a contar la cantidad de bolitas verdes para cada mano y calcular la diferencia. Luego, vamos a graficar los puntajes de diferencia para ver qué tipo de valores produce el azar.</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5bolitadiffs_fff4368cec5171e7574d1a1f11f5d15e">
<div class="cell-output-display">
<div id="fig-5bolitadiffs" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5bolitadiffs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-Foundation_Inference_files/figure-html/fig-5bolitadiffs-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5bolitadiffs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.13: Un vistazo a las diferencias en el número de bolitas verdes entre manos en distintas repeticiones. La diferencia esperada es cero, pero el error muestral produce diferencias distintas de cero.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Las barras faltantes significan que se extrajo la misma cantidad de bolitas verdes con ambas manos (puntaje de diferencia igual a 0). Un valor positivo indica que la mano izquierda sacó más bolitas verdes que la derecha. Un valor negativo significa que fue la derecha la que sacó más verdes. Notá que si hubiéramos decidido (y lo podemos hacer) calcular la diferencia al revés (mano derecha menos mano izquierda), los signos de los puntajes se invertirían.</p>
<p>Empezamos a ver mejor qué tipo de diferencias puede generar el azar. Los puntajes de diferencia están mayormente entre -2 y +2. Podríamos hacernos una idea más clara si corremos este experimento ficticio <strong>100 veces</strong> en lugar de solo 10. Los resultados se muestran en <a href="#fig-5manydiffs" class="quarto-xref">Figura&nbsp;<span>6.14</span></a>.</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5manydiffs_2a5cf3b57ddb4f530bad7a396100cfa4">
<div class="cell-output-display">
<div id="fig-5manydiffs" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5manydiffs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-Foundation_Inference_files/figure-html/fig-5manydiffs-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5manydiffs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.14: Repetimos el experimento 100 veces y observamos las diferencias en cada repetición. Hay muchas diferencias que pueden ser causadas solo por el azar.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Upss, acabamos de realizar tantos experimentos simulados que el eje x es ilegible, pero va de 1 a 100. Cada barra representa la diferencia de número de bolas verdes elegidas al azar por la mano izquierda o derecha. ¿Empiezas a notar algo? Mira el eje y, éste muestra el tamaño de la diferencia. Sí, hay muchas barras de diferentes tamaños, esto nos muestra que muchos tipos de diferencias ocurren por azar. Sin embargo, el eje y también está restringido. No va de -10 a +10. Las grandes diferencias superiores a 5 o -5 no ocurren muy a menudo.</p>
<p>Ahora que tenemos un método para simular las diferencias debidas al azar, vamos a realizar 10.000 experimentos simulados. Pero, en lugar de trazar las diferencias en un gráfico de barras para cada experimento, ¿qué tal si observamos el histograma de puntuaciones de diferencia? El histograma en la <a href="#fig-5histdiffbolita" class="quarto-xref">Figura&nbsp;<span>6.15</span></a> proporciona una imagen más clara sobre qué diferencias ocurren con más frecuencia y cuáles no. Esta será otra ventana para observar qué tipo de diferencias es capaz de producir el azar.</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5histdiffbolita_0bb847eda87835f7b4b3d113ccb9eaa8">
<div class="cell-output-display">
<div id="fig-5histdiffbolita" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5histdiffbolita-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-Foundation_Inference_files/figure-html/fig-5histdiffbolita-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5histdiffbolita-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.15: Histograma de las diferencias obtenidas por azar en 10.000 repeticiones. La diferencia más frecuente es 0, que es lo que esperamos por azar. Pero las diferencias pueden llegar a ser tan grandes como -10 o +10. Las diferencias más grandes ocurren con menor frecuencia. El azar no puede hacer cualquier cosa.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Nuestra simulación por computadora nos permite forzar al azar a actuar miles de veces; cada vez produce una diferencia. Registramos la diferencia, y al final de la simulación graficamos el histograma de esas diferencias. Ese histograma empieza a mostrarnos <strong>de dónde vinieron esas diferencias</strong>. Recordá la idea de que los números provienen de una distribución, y que la distribución nos dice con qué frecuencia aparece cada número. Estamos viendo una de esas distribuciones. Nos está mostrando que el azar <strong>produce algunas diferencias más a menudo que otras</strong>.</p>
<p>Primero, el azar usualmente produce diferencias de 0 —esa es la barra más alta en el centro. También puede producir diferencias más grandes, pero a medida que las diferencias se alejan de 0 (positivas o negativas), ocurren con <strong>menos frecuencia</strong>. La forma de este histograma es tu <strong>ventana del azar</strong>. Te dice lo que el azar puede hacer, lo que el azar usualmente hace, y lo que usualmente <strong>no</strong> hace.</p>
<p>Podés usar esta ventana del azar para ayudarte a hacer inferencias. Si vos mismo hicieras el experimento de las bolitas y encontraras que tu mano izquierda eligió 2 bolitas verdes más que la derecha, ¿concluirías que tu mano izquierda es especial, y que te hizo elegir más bolitas verdes? Esperemos que no. Podés mirar la ventana del azar y ver que <strong>diferencias de +2 ocurren bastante seguido</strong> por puro azar. No deberías sorprenderte si obtuviste una diferencia de +2. Ahora bien, ¿qué pasa si tu mano izquierda eligió 5 bolitas verdes más que la derecha? Bueno, el azar <strong>no suele</strong> hacer eso. Tal vez empieces a pensar que pasa algo con tu mano izquierda. Y si sacaras 9 bolitas verdes más con la izquierda que con la derecha, <strong>realmente</strong> podrías empezar a preguntarte. Eso es algo que puede pasar (es posible), pero <strong>prácticamente nunca pasa por azar</strong>.</p>
<p>Cuando obtenés resultados que casi nunca ocurren por azar, podés tener más confianza en que la diferencia refleja una <strong>fuerza causal que no es el azar</strong>.</p>
</section>
<section id="la-prueba-de-crump" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="la-prueba-de-crump"><span class="header-section-number">6.5</span> La prueba de Crump</h2>
<p>Vamos a hacer muchas inferencias a lo largo del resto del curso. Y casi todas se reducen a una sola pregunta:</p>
<blockquote class="blockquote">
<p><strong>¿Fue el azar el que produjo las diferencias en mis datos?</strong></p>
</blockquote>
<p>Vamos a hablar sobre experimentos, principalmente. Y en los experimentos queremos saber si nuestra <strong>manipulación causó una diferencia</strong> en nuestra medición. Pero, medimos cosas que tienen variabilidad natural. Así que <strong>cada vez que medimos algo, siempre vamos a encontrar alguna diferencia</strong>. Lo que queremos saber es si <strong>la diferencia que encontramos entre nuestras condiciones experimentales podría haber sido producida por azar</strong>. Si el azar es una explicación <strong>muy poco probable</strong> para la diferencia observada, vamos a hacer la inferencia de que el azar <strong>no</strong> produjo la diferencia, y que <strong>algo en nuestra manipulación experimental sí lo hizo</strong>. Eso es todo (por ahora).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>La estadística no consiste únicamente en determinar si el azar ha podido producir un patrón en los datos observados. Las mismas herramientas de las que hablamos aquí pueden generalizarse para preguntarse si <strong>cualquier tipo de distribución</strong> podría haber producido las diferencias. Esto permite hacer comparaciones entre distintos modelos de los datos, para ver cuál era el más probable, en lugar de limitarse a rechazar los improbables (por ejemplo, el azar). Pero, dejaremos esos temas avanzados para otro libro de texto.</p>
</div>
</div>
<p>Este capítulo trata de construir intuiciones para hacer este tipo de inferencias sobre el papel del azar en tus datos. No me queda claro cuáles son las mejores cosas para decir, para ayudarte a desarrollar intuiciones sobre cómo hacer inferencia estadística. Así que este capítulo prueba diferentes caminos, algunos más estándar, y otros completamente inventados. Lo que vas a leer ahora es una forma inventada de hacer inferencia estadística, sin usar la jerga que normalmente usamos para hablar del tema. El objetivo es trabajar sin fórmulas ni probabilidades, y simplemente usar algunas ideas básicas con simulaciones para ver qué pasa. Vamos a mirar qué puede hacer el azar, y luego hablaremos de qué tiene que pasar en tus datos para que puedas tener confianza en que <strong>no fue el azar</strong> lo que produjo el patrón que observás.</p>
<section id="métodos-intuitivos" class="level3" data-number="6.5.1">
<h3 data-number="6.5.1" class="anchored" data-anchor-id="métodos-intuitivos"><span class="header-section-number">6.5.1</span> Métodos intuitivos</h3>
<p>Atención: esto es una prueba estadística no oficial, inventada por Matt Crump. Tiene sentido para él (para mí), y si resulta que alguien ya inventó esto antes, entonces Crump no hizo bien la tarea, y le cambiaremos el nombre al autor original más adelante. El punto de esta prueba es mostrar cómo <strong>operaciones aritméticas simples</strong> que ya conocés pueden usarse para construir una herramienta estadística para la inferencia. Esta prueba utiliza:</p>
<ol type="1">
<li>Muestreo aleatorio de números desde una distribución</li>
<li>Sumar y restar</li>
<li>Dividir para calcular la media</li>
<li>Contar</li>
<li>Graficar y trazar líneas</li>
<li><strong>NINGUNA FÓRMULA</strong></li>
</ol>
</section>
<section id="parte-1-intuición-basada-en-frecuencia-sobre-ocurrencias" class="level3" data-number="6.5.2">
<h3 data-number="6.5.2" class="anchored" data-anchor-id="parte-1-intuición-basada-en-frecuencia-sobre-ocurrencias"><span class="header-section-number">6.5.2</span> Parte 1: Intuición basada en frecuencia sobre ocurrencias</h3>
<p><strong>Pregunta:</strong> ¿Cuántas veces tiene que pasar algo para que consideres que pasa mucho? ¿Y cuántas veces tiene que pasar para que consideres que pasa muy poco, o casi nunca? ¿Tan pocas veces como para que no te preocupe que te pase? ¿Saldrías a la calle todos los días si pensás que te puede caer un rayo 1 de cada 10 veces? Yo no. Probablemente te caería un rayo más de una vez por mes, y morirías bastante rápido. 1 de cada 10 es <strong>mucho</strong> (para mí, tal vez no para vos —acá no hay una única respuesta correcta).</p>
<p>¿Saldrías todos los días si pensaras que te puede caer un rayo 1 de cada 100 veces? Uf, esa es difícil. ¿Qué haría yo? Si saliera todos los días, probablemente estaría muerto en un año. Tal vez saldría 2 o 3 veces por año —soy algo arriesgado—, pero probablemente viviría más si me quedara en casa para siempre. Sería un bajón.</p>
<p>¿Saldrías todos los días si pensás que te podría caer un rayo 1 de cada 1000 días? Bueno, probablemente te morirías en 3 a 6 años si hicieras eso. ¿Sos timbero? Tal vez saldrías una vez por mes. Igual, un garrón.</p>
<p>¿Saldrías todos los días si pensás que te puede caer un rayo 1 de cada 10.000 días? 10.000 es un número grande, difícil de imaginar. Equivale a que te caiga un rayo más o menos una vez cada 27 años. Sí, probablemente saldría unas 150 veces por año, y cruzaría los dedos.</p>
<p>¿Saldrías todos los días si pensás que te puede caer un rayo 1 de cada 100.000 días? ¿Cuántos años es eso? Son unos 273 años. Con esas probabilidades, probablemente saldría todo el tiempo y me olvidaría del tema. No pasa muy seguido.</p>
<p>El punto de considerar estas preguntas es que desarrolles tu propia intuición sobre qué cosas pasan mucho, qué cosas no pasan mucho, y cómo tomar decisiones importantes en función de qué tan frecuente es algo.</p>
</section>
<section id="parte-2-simulando-el-azar" class="level3" data-number="6.5.3">
<h3 data-number="6.5.3" class="anchored" data-anchor-id="parte-2-simulando-el-azar"><span class="header-section-number">6.5.3</span> Parte 2: Simulando el azar</h3>
<p>Esta parte podría hacerse de muchas maneras. Voy a hacer un montón de suposiciones que no voy a justificar, y no voy a afirmar que la prueba de Crump esté libre de problemas. Lo que sí voy a afirmar es que <strong>ayuda a hacer una inferencia</strong> sobre si el azar podría haber producido ciertas diferencias en los datos. Ya nos hemos familiarizado con las simulaciones, así que vamos a hacer otra.</p>
<p>Esto es lo que vamos a hacer. Soy un psicólogo cognitivo que está midiendo cierta variable X. Gracias a investigaciones previas, sé que cuando mido X, mis muestras tienden a tener una media y una desviación estándar particulares. Supongamos que la media suele ser 100, y la desviación estándar 15. En este caso, no me interesa usar esos números como estimaciones de parámetros poblacionales, simplemente estoy pensando en <strong>cómo suelen ser mis muestras</strong>. Lo que quiero saber es cómo se comportan cuando las muestreo. Quiero ver <strong>qué tipo de muestras ocurren con frecuencia</strong>, y cuáles no. Además, vivo en el mundo real, y en el mundo real, cuando hago experimentos para ver qué modifica X, usualmente tengo acceso a una cantidad limitada de participantes (a quienes agradezco mucho por colaborar). Supongamos que puedo incluir a 20 sujetos por condición. Mantenemos el experimento simple: dos condiciones, así que necesito 40 sujetos en total.</p>
<p>Me gustaría aprender algo que me ayude a inferir. Una posibilidad sería ver <strong>cómo se ve la distribución muestral de la media muestral</strong>. Esa distribución me diría qué valores de la media aparecen frecuentemente, y cuáles son raros. Pero en realidad voy a <strong>saltar esa parte</strong>.</p>
<p>Porque lo que realmente me interesa es <strong>cómo se ve la distribución muestral de la diferencia entre medias muestrales</strong>. Después de todo, voy a ejecutar un experimento con 20 personas en una condición y 20 en otra. Voy a calcular la media del grupo A, la media del grupo B, y mirar la diferencia. Probablemente encuentre una diferencia, pero mi pregunta es: ¿esa diferencia fue causada por mi manipulación, o es del tipo que suele ocurrir por azar? Si supiera qué puede hacer el azar y con qué frecuencia produce diferencias de determinado tamaño, entonces podría comparar la diferencia que observé con lo que el azar puede hacer, y entonces <strong>tomar una decisión</strong>. Si mi diferencia <strong>no ocurre muy seguido</strong>, (ya vamos a definir qué es “muy seguido”), entonces tal vez esté dispuesto a creer que <strong>mi manipulación causó la diferencia</strong>. Si mi diferencia ocurre todo el tiempo solo por azar, entonces no voy a pensar que fue causada por mi manipulación, porque podría haber sido simplemente el azar.</p>
<p>Entonces, esto es lo que vamos a hacer, <strong>incluso antes de ejecutar el experimento</strong>. Vamos a hacer una simulación. Vamos a muestrear números para el grupo A y para el grupo B, luego vamos a calcular las medias de cada grupo, y después vamos a calcular la diferencia entre esas medias.</p>
<p>Pero vamos a hacer <strong>algo muy importante</strong>: vamos a fingir que <strong>no hicimos ninguna manipulación</strong>. Si hacemos esto —no hacemos nada, ninguna intervención que pudiera causar una diferencia—, entonces sabemos que <strong>cualquier diferencia entre las medias de los grupos A y B solo puede deberse al error muestral</strong>. Eliminamos todas las demás causas: solo queda el azar. Haciendo esto, vamos a poder ver exactamente qué puede hacer el azar. Más importante aún, vamos a ver qué tipo de diferencias ocurren frecuentemente, y cuáles no.</p>
<p>Antes de hacer la simulación, necesitamos responder una pregunta: <strong>¿cuánto es “mucho”?</strong> Podríamos elegir cualquier número. Yo voy a elegir 10.000. Eso es mucho. Si algo ocurre solo 1 vez en 10.000, estoy dispuesto a decir que <strong>eso no es mucho</strong>.</p>
<p>Bien, ya tenemos nuestro número. Vamos a simular las diferencias de medias entre los grupos A y B <strong>que podrían surgir solo por azar</strong>. Lo vamos a hacer 10.000 veces. Eso le da al azar muchas oportunidades para mostrarnos qué puede hacer y qué no.</p>
<p>Esto es lo que hice: muestreé 20 números para el grupo A y 20 para el grupo B. Ambos grupos provienen de la misma distribución normal, con media = 100 y desviación estándar = 15. Como las muestras provienen de la <strong>misma distribución</strong>, esperamos que, en promedio, sean similares (aunque ya sabemos que las muestras siempre difieren entre sí). Después calculo la media de cada grupo, y luego la diferencia entre esas medias. Guardo ese <strong>puntaje de diferencia de medias</strong>, y repito esto hasta tener 10.000 de ellos. Después, dibujo un histograma como el de la <a href="#fig-5crumptestdiff" class="quarto-xref">Figura&nbsp;<span>6.16</span></a>.</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5crumptestdiff_6e151bd4722f27e7d16b5098d3be6c78">
<div class="cell-output-display">
<div id="fig-5crumptestdiff" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5crumptestdiff-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-Foundation_Inference_files/figure-html/fig-5crumptestdiff-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5crumptestdiff-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.16: Histograma de diferencias entre medias surgidas por azar.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>Por supuesto, podríamos reconocer que el azar <strong>podría</strong> producir una diferencia mayor que 15. Simplemente <strong>no le dimos la oportunidad</strong>. Solo corrimos la simulación 10.000 veces. Si la corriéramos un millón de veces, tal vez una diferencia mayor que 15 o incluso 20 ocurriría un par de veces. Si la corriéramos un trillón de veces, tal vez una diferencia mayor que 30 ocurriría muy de vez en cuando. Si fuéramos hasta el infinito, entonces el azar podría producir todo tipo de diferencias grandes <strong>cada tanto</strong>. Pero ya decidimos que 1 en 10.000 <strong>no es mucho</strong>. Así que cosas que ocurren 0 veces en 10.000 simulaciones —como diferencias mayores a 15— se consideran extremadamente improbables.</p>
</div>
</div>
<p>Ahora podemos ver lo que el azar puede hacer con respecto al tamaño de nuestras diferencias de medias. El eje x muestra el tamaño de la diferencia de medias. Como tomamos ambas muestras de la <strong>misma distribución poblacional</strong>, la diferencia entre ellas <strong>debería tender a ser 0</strong>, y eso es lo que vemos en el histograma.</p>
<p>Pausa un segundo. ¿Por qué las diferencias de medias deberían tender a cero? ¿No era que la media poblacional era 100? ¿No deberían las diferencias rondar 100? No.&nbsp;La media del grupo A tenderá a estar alrededor de 100, y la del grupo B también. Entonces, la diferencia tenderá a ser 100 − 100 = 0.Por eso esperamos una <strong>diferencia de medias igual a cero</strong> cuando las muestras provienen de la misma población.</p>
<p>Entonces, las diferencias cercanas a cero ocurren con más frecuencia —eso es bueno, es lo que esperábamos. Las diferencias más grandes (positivas o negativas) ocurren cada vez menos. Diferencias mayores que 15 o menores que -15 <strong>no ocurrieron nunca</strong>. Para nuestros fines, parece que el azar <strong>solo produce diferencias entre -15 y 15</strong>.</p>
<p>OK, hagamos un par de preguntas simples.¿Cuál fue el número negativo más grande (es decir, el más negativo) que ocurrió en la simulación? Vamos a usar R para esto. Todos los 10.000 puntajes de diferencia están guardados en una variable que llamé <code>diferencia</code>. Si queremos encontrar el valor mínimo, usamos la función <code>min</code>. Este es el resultado:</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/unnamed-chunk-3_d7944ca3898e8d62aaa2cd25264c96d3">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(diferencia)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] -16.25988</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Bien, ¿y cuál fue el número positivo más grande que ocurrió? Usemos la función <code>max</code> para averiguarlo. Esa función encuentra el valor más grande (máximo) de una variable. Por cierto, acabamos de calcular el rango: el mínimo y el máximo de los datos. Recordá que ya aprendimos eso antes. De todos modos, acá va el máximo:</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/unnamed-chunk-4_86b68daf83474f61b3e0cc356d2cae47">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(diferencia)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 17.3742</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ambos valores extremos ocurrieron <strong>solo una vez</strong>. Fueron tan poco frecuentes que ni siquiera los pudimos ver en el histograma —la barra era tan baja que no se notaba. Además, el mayor valor negativo y el mayor positivo tienen prácticamente el mismo tamaño (ignorando el signo), lo cual tiene sentido porque la distribución parece bastante simétrica.</p>
<p>Entonces, ¿qué podemos decir sobre estos dos números —el mínimo y el máximo? Podemos decir que el mínimo ocurrió 1 vez de cada 10.000. Y que el máximo ocurrió 1 vez de cada 10.000. ¿Eso es mucho? Para mí, no. <strong>No es mucho.</strong></p>
<p>¿Y con qué frecuencia ocurre una diferencia de 30 (mucho más grande que el máximo)? No podemos decirlo exactamente, porque <strong>30 no ocurrió nunca</strong> en la simulación. Con lo que tenemos, podemos decir: 0 veces de cada 10.000. Eso significa: <strong>nunca</strong>.</p>
<p>Estamos por pasar a la parte tres, que consiste en <strong>trazar líneas de decisión</strong> y hablar sobre ellas. La parte realmente importante de la parte 3 es esta: ¿Qué dirías si hicieras este experimento una vez y encontraras una diferencia de medias de 30? Yo diría: eso ocurre <strong>0 veces de cada 10.000</strong> por azar. Yo diría: <strong>el azar no produjo mi diferencia de 30</strong>. Eso es lo que diría. Vamos a desarrollar esta idea ahora mismo.</p>
</section>
<section id="parte-3-juicio-y-toma-de-decisiones" class="level3" data-number="6.5.4">
<h3 data-number="6.5.4" class="anchored" data-anchor-id="parte-3-juicio-y-toma-de-decisiones"><span class="header-section-number">6.5.4</span> Parte 3: Juicio y toma de decisiones</h3>
<p>Recordá: ni siquiera hemos hecho un experimento real. Simplemente simulamos lo que podría pasar <strong>si</strong> lo hiciéramos. Hicimos un histograma. Vimos que el azar produce algunas diferencias más que otras, y que nunca produce diferencias realmente grandes. ¿Qué deberíamos hacer con esa información?</p>
<p>Lo que vamos a hacer es hablar sobre <strong>juicio y toma de decisiones</strong>. ¿De qué tipo? Bueno, cuando finalmente hagas un experimento real, vas a obtener dos medias —una para el grupo A y otra para el grupo B—, y entonces vas a tener que hacer algunos juicios, y quizás incluso tomar una decisión, si querés.</p>
<p>Vas a tener que juzgar si el azar (es decir, el error muestral) <strong>podría haber producido la diferencia que observaste</strong>. Si juzgás que no fue el azar, quizás decidas contarle al mundo que tu manipulación experimental realmente funciona. Si juzgás que sí podría haber sido el azar, quizás tomes una decisión distinta. Estas decisiones son importantes para los investigadores. Sus carreras pueden depender de ellas. Y además, sus decisiones <strong>importan para el público</strong>. A nadie le gusta escuchar noticias falsas en los medios sobre hallazgos científicos.</p>
<p>Así que lo que estamos haciendo es prepararnos para tomar esos juicios. Vamos a trazar un plan, <strong>antes incluso de ver los datos</strong>, sobre cómo vamos a juzgar y decidir lo que encontremos. Este tipo de planificación también puede usarse para <strong>interpretar los resultados de otras personas</strong>, como una forma de comprobar dos veces si creés que esos resultados son plausibles. El tema con el juicio y la toma de decisiones es que <strong>las personas razonables no se ponen de acuerdo sobre cómo hacerlo</strong>, las personas poco razonables realmente no se ponen de acuerdo, y los estadísticos e investigadores <strong>también discrepan sobre cómo hacerlo</strong>. Voy a proponer algunas ideas con las que la gente va a estar en desacuerdo. Está bien. Estas ideas igual tienen sentido. Y esas ideas que generan desacuerdo apuntan a problemas importantes que son muy reales en cualquier test de inferencia estadística “real”.</p>
<p>Hablemos ahora de algunos hechos objetivos que <strong>sabemos con certeza</strong> a partir de nuestra simulación de 10.000 repeticiones. Por ejemplo, podemos trazar algunas líneas en el gráfico y marcar algunas regiones distintas. Vamos a hablar de dos tipos de regiones:</p>
<ol type="1">
<li><strong>Región del azar</strong>. El azar lo hizo. El azar <strong>podría</strong> haberlo hecho.</li>
<li><strong>Región del no azar</strong>. El azar <strong>no</strong> lo hizo. El azar <strong>no podría</strong> haberlo hecho.</li>
</ol>
<p>Las regiones están definidas por el valor mínimo y el valor máximo observados en la simulación. El azar <strong>nunca produjo un número menor ni mayor</strong> que esos extremos. La región <strong>dentro del rango</strong> es lo que el azar <strong>sí hizo</strong>, y la región <strong>fuera del rango</strong>, en ambos extremos, es lo que el azar <strong>nunca hizo</strong>.</p>
<p>Se ve así en la <a href="#fig-5crumpdecision" class="quarto-xref">Figura&nbsp;<span>6.17</span></a>:</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5crumpdecision_b0c427886d365a85f40c2fa1a0439735">
<div class="cell-output-display">
<div id="fig-5crumpdecision" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5crumpdecision-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-Foundation_Inference_files/figure-html/fig-5crumpdecision-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5crumpdecision-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.17: Aplicación de límites de decisión al histograma de diferencias de medias. Los límites identifican qué diferencias produjo (o no produjo) el azar en la simulación.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Acabamos de trazar unas líneas, sombrear algunas regiones y construir un plan que podríamos usar para tomar decisiones. ¿Cómo funcionarían esas decisiones? Supongamos que hiciste el experimento y encontraste una diferencia de medias entre los grupos A y B de 25. ¿Dónde está el 25 en la figura? Está en la parte verde. ¿Qué dice la parte verde? “NO AZAR”. ¿Qué significa esto? Significa que el azar <strong>nunca</strong> produjo una diferencia de 25. Eso ocurrió <strong>0 veces de cada 10.000</strong>. Si encontramos una diferencia de 25, quizás podamos concluir con confianza que el azar <strong>no causó esa diferencia</strong>. Si yo encontrara una diferencia de 25 con este tipo de datos, estaría bastante seguro de que el azar no la causó, y me daría permiso a mí mismo para considerar que <strong>mi manipulación experimental podría estar causando la diferencia</strong>.</p>
<p>¿Y qué pasa con una diferencia de +10? Eso está en la parte roja, <strong>donde vive el azar</strong>. El azar <strong>podría haber producido</strong> una diferencia de +10, porque podemos ver que <strong>a veces lo hizo</strong>. La parte roja es la ventana de lo que el azar hizo en nuestra simulación. Cualquier cosa dentro de esa ventana podría haber sido una diferencia causada por el azar. Si encontrara una diferencia de +10, diría: “sí, podría haber sido el azar”. Y también estaría <strong>menos seguro</strong> de que la diferencia fue causada solamente por mi manipulación experimental.</p>
<p>La inferencia estadística <strong>podría ser tan simple como esto</strong>: El número que obtenés de tu experimento podría estar <strong>dentro de la ventana del azar</strong> (entonces no podés descartar al azar como causa), o podría estar <strong>fuera de la ventana del azar</strong> (entonces sí podés descartarlo). Caso cerrado. Vámonos todos a casa.</p>
</section>
<section id="zonas-grises" class="level3" data-number="6.5.5">
<h3 data-number="6.5.5" class="anchored" data-anchor-id="zonas-grises"><span class="header-section-number">6.5.5</span> Zonas grises</h3>
<p>Entonces, ¿cuál es el problema? Dependiendo de quién seas, y qué tipo de riesgos estés dispuesto a tomar, puede que no haya ningún problema. Pero si sos <strong>aunque sea un poco arriesgado</strong>, entonces sí hay un problema que hace difícil emitir juicios claros sobre el papel del azar.</p>
<p>Nos gustaría decir que <strong>el azar causó</strong> o <strong>no causó</strong> la diferencia que observamos. Pero en realidad, siempre estamos en la posición de tener que admitir que <strong>el azar podría haberla causado a veces</strong>, o que <strong>no la habría causado la mayoría de las veces</strong>.</p>
<p>Estas son afirmaciones ambiguas, imprecisas, entre el “sí” y el “no”. Y está bien. El gris también es un color. Vamos a darle un poco de respeto al gris.</p>
<p>—“¿De qué zonas grises estás hablando? ¡Solo veo rojo y verde! ¿Tengo daltonismo para el gris?”—</p>
<p>Veamos dónde podrían estar algunas zonas grises. Digo “podrían”, porque la gente no se pone de acuerdo sobre <strong>dónde empieza el gris</strong>. Las personas tienen distintos niveles de tolerancia al gris.</p>
<p>La <a href="#fig-5crumpuncertainty" class="quarto-xref">Figura&nbsp;<span>6.18</span></a> muestra <strong>mi</strong> opinión sobre dónde se ubican las zonas grises:</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5crumpuncertainty_3fc5277ed02d82d389ae6f58acff1c90">
<div class="cell-output-display">
<div id="fig-5crumpuncertainty" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5crumpuncertainty-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-Foundation_Inference_files/figure-html/fig-5crumpuncertainty-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5crumpuncertainty-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.18: Los signos de interrogación indican una zona donde hay cierta incertidumbre. Las diferencias dentro de esta zona no ocurren muy seguido por azar. Cuando encontrás diferencias de ese tamaño, ¿deberías rechazar la idea de que fueron causadas por azar? Siempre vas a tener algo de incertidumbre asociada a esa decisión, porque está claro que el azar podría haber causado la diferencia. Pero, el azar usualmente no produce diferencias de ese tamaño.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Hice dos zonas grises, y son grisáceo-rojizas, porque todavía estamos dentro de la ventana del azar. Hay signos de interrogación (?) en las zonas grises. ¿Por qué? Los signos de interrogación reflejan cierta <strong>incertidumbre</strong> que tenemos respecto a esas diferencias en particular. Por ejemplo, si encontrás una diferencia dentro de una zona gris, digamos una de 15. 15 está por debajo del máximo, lo que significa que el azar sí <strong>produjo diferencias cercanas a 15</strong>. Pero, las diferencias de 15 <strong>no ocurren muy seguido</strong>.</p>
<p>¿Qué podés concluir o decir sobre ese 15 que encontraste? ¿Podés decir, sin lugar a dudas, que el azar <strong>no</strong> produjo esa diferencia? Por supuesto que no. Sabés que el azar <strong>podría haberla producido</strong>. Aun así, es una de esas cosas que <strong>no ocurren mucho</strong>. Eso hace que el azar sea una explicación <strong>poco probable</strong>. En lugar de pensar que fue el azar, quizás estés dispuesto a <strong>tomar el riesgo</strong> y decir que tu manipulación experimental <strong>causó la diferencia</strong>. Estás haciendo una apuesta de que no fue el azar… pero podría ser una apuesta razonable, ya que sabés que <strong>las probabilidades están de tu lado</strong>.</p>
<p>Tal vez estés pensando que tus zonas grises no son iguales a las que dibujé yo. Quizás quieras ser más conservador y hacerlas más chicas. O, tal vez seas más arriesgado y prefieras hacerlas más grandes. O incluso, quizás quieras extender la zona gris un poco <strong>dentro de la zona verde</strong> (después de todo, el azar podría producir diferencias más grandes alguna que otra vez, y para evitarlas tendrías que hacer que la zona gris invada un poco el área verde).</p>
<p>Otra cosa en la que pensar es en tu <strong>política de decisión</strong>. ¿Qué vas a hacer cuando tu diferencia observada caiga dentro de la zona gris? ¿Siempre vas a tomar la misma decisión sobre el papel del azar? ¿O a veces vas a cambiar de parecer, según cómo te sientas? Tal vez pienses que no debería haber una política estricta, y que deberías aceptar cierto nivel de incertidumbre. La diferencia que encontraste <strong>podría ser real… o tal vez no lo sea</strong>. Hay incertidumbre, es difícil evitarla.</p>
<p>Así que vamos a ilustrar <strong>otro tipo de estrategia</strong> para tomar decisiones. Recién hablamos de una que incluía líneas y regiones. Eso hace que parezca una elección binaria: podemos <strong>descartar</strong> o <strong>no descartar</strong> el papel del azar. Otra perspectiva es que <strong>todo es un matiz de gris</strong>, como en la <a href="#fig-5crumpshade" class="quarto-xref">Figura&nbsp;<span>6.19</span></a>.</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5crumpshade_611902b9be6c0338308c10c0ef21701e">
<div class="cell-output-display">
<div id="fig-5crumpshade" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5crumpshade-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-Foundation_Inference_files/figure-html/fig-5crumpshade-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5crumpshade-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.19: El sombreado de las barras azules indica los niveles de confianza en si una diferencia podría haber sido producida por azar. Las barras más oscuras representan mayor confianza en que la diferencia no fue causada por azar. Las barras se oscurecen a medida que la diferencia de medias aumenta en valor absoluto.
</figcaption>
</figure>
</div>
</div>
</div>
<p>OK, así que lo hice con tonos de azul (porque era más fácil en R). Ahora podemos ver dos planes de decisión al mismo tiempo. Notá que a medida que las barras se vuelven más bajas, también se vuelven de un azul más oscuro e intenso. El color puede usarse como guía para tu confianza. Es decir, tu confianza en la creencia de que <strong>tu manipulación causó la diferencia</strong>, y <strong>no el azar</strong>. Si encontrás una diferencia cerca de una barra azul bien oscura, esas diferencias <strong>no ocurren muy seguido por azar</strong>, así que podrías estar muy confiado en que <strong>el azar no la causó</strong>. Si encontrás una diferencia cerca de una barra azul un poco más clara, podrías estar <strong>un poco menos confiado</strong>. Eso es todo. Ejecutás tu experimento, obtenés tus datos, y después tenés cierto <strong>nivel de confianza</strong> en que la diferencia <strong>no fue producida por azar</strong>.</p>
<p>Esta forma de pensar se desarrolla de manera mucho más interesante en el mundo bayesiano de la estadística. No vamos a meternos demasiado en eso, pero lo mencionaremos un poco acá y allá. Vale la pena saber que existe.</p>
<section id="tomar-decisiones-y-equivocarse" class="level4" data-number="6.5.5.1">
<h4 data-number="6.5.5.1" class="anchored" data-anchor-id="tomar-decisiones-y-equivocarse"><span class="header-section-number">6.5.5.1</span> Tomar decisiones y equivocarse</h4>
<p>No importa cómo planees tomar decisiones sobre tus datos, <strong>siempre vas a estar propenso a cometer errores</strong>. Podrías declarar que un resultado es real, cuando en realidad fue causado por azar. Eso se llama un <strong>error tipo I</strong>, o un <strong>falso positivo</strong>. Podrías ignorar un resultado, decir que fue azar, cuando en realidad <strong>no lo fue</strong> (aunque estaba dentro de la ventana). Eso se llama un <strong>error tipo II</strong>, o un <strong>falso negativo</strong>.</p>
<p>La forma en que tomás decisiones puede influir en <strong>con qué frecuencia cometés errores a lo largo del tiempo</strong>. Si sos investigador, vas a correr muchos experimentos, y vas a cometer cierta cantidad de errores con el tiempo.</p>
<p>Si usás algo como el método muy estricto de <strong>solo aceptar resultados como reales cuando están en la zona de “no azar”</strong>, entonces <strong>no cometerás muchos errores tipo I</strong>. Prácticamente todos tus resultados serán reales. Pero también vas a cometer <strong>errores tipo II</strong>, porque vas a perderte cosas reales que tu criterio de decisión dice que son producto del azar. Y también vale lo contrario. Si estás dispuesto a ser más liberal, y aceptar como reales los resultados que están en la zona gris, entonces vas a cometer <strong>más errores tipo I</strong>, pero <strong>no vas a cometer tantos errores tipo II</strong>. Bajo la estrategia de decisión que usa estas regiones de corte para decidir, hay un <strong>compromiso necesario</strong>: no podés minimizar ambos tipos de error a la vez.</p>
<p>La perspectiva bayesiana evita un poco este problema. Los bayesianos hablan de <strong>actualizar sus creencias y niveles de confianza con el tiempo</strong>. En esa visión, lo único que tenés es <strong>un cierto nivel de confianza</strong> sobre si algo es real o no, y al ejecutar más experimentos podés <strong>aumentar o disminuir</strong> ese nivel de confianza. Esto, de alguna forma, <strong>evita el compromiso entre errores tipo I y tipo II</strong>.</p>
<p>De todos modos, hay otra forma de reducir los errores tipo I y tipo II, y <strong>de aumentar tu confianza en los resultados incluso antes de hacer el experimento</strong>. Se llama: <strong>Saber cómo diseñar un buen experimento.</strong></p>
</section>
</section>
<section id="parte-4-diseño-experimental" class="level3" data-number="6.5.6">
<h3 data-number="6.5.6" class="anchored" data-anchor-id="parte-4-diseño-experimental"><span class="header-section-number">6.5.6</span> Parte 4: Diseño experimental</h3>
<p>Ya vimos lo que puede hacer el azar. Ahora ejecutamos un experimento. Manipulamos algo entre los grupos A y B, obtenemos los datos, calculamos las medias de grupo, y luego observamos la diferencia. Después cruzamos todos los dedos de las manos y los pies, y rezamos con todas nuestras fuerzas que la diferencia sea lo suficientemente grande como para <strong>no haber sido causada por azar</strong>. Eso es mucho rezar.</p>
<p>El asunto es el siguiente: a menudo <strong>no sabemos qué tan fuerte es nuestra manipulación</strong> desde el principio. Entonces, incluso si puede causar un cambio, no necesariamente sabemos <strong>cuánto</strong> puede cambiar las cosas. Por eso estamos ejecutando el experimento.</p>
<p>Muchas manipulaciones en Psicología <strong>no son lo suficientemente fuertes</strong> como para causar grandes cambios. Y eso es un problema cuando queremos detectar esas fuerzas causales más pequeñas. En nuestro ejemplo ficticio, podrías manipular algo que tenga una influencia muy leve, que nunca empuje la diferencia de medias más allá de, digamos, 5 o 10. En nuestra simulación, <strong>necesitábamos algo más cercano a 15, 17 o 21 —o mejor aún, ¡30!— porque el azar nunca hace eso</strong>. Digamos que tu manipulación es escuchar música vs.&nbsp;no escuchar música. Escuchar música podría cambiar algo sobre X, pero si solo cambia X en +5, <strong>nunca vas a poder afirmar con confianza que no fue el azar</strong>. Y no es tan fácil cambiar completamente la condición de música para que sea súper intensa y realmente cause un cambio en X comparado con la condición sin música.</p>
<blockquote class="blockquote">
<p><strong>¡DISEÑO EXPERIMENTAL AL RESCATE!</strong> Último momento: a menudo es posible cambiar cómo ejecutás tu experimento para que sea <strong>más sensible</strong> a efectos pequeños.</p>
</blockquote>
<p>¿Tenés alguna idea de cómo se puede hacer esto? Acá va una pista: es todo eso que aprendiste sobre la distribución muestral de la media muestral, y el papel del tamaño muestral. ¿Qué le pasa a la distribución muestral de la media cuando <code>N</code> (el tamaño de muestra) aumenta? La distribución <strong>se vuelve más y más angosta</strong>, y empieza a parecerse a un único número (la media hipotética de la población hipotética). Eso es genial.</p>
<p>Si cambiás el enfoque y pensás en las <strong>diferencias de medias</strong>, como la distribución que creamos en esta prueba, ¿qué creés que va a pasar con esa distribución a medida que aumentamos <code>N</code>? También se va a <strong>achicar</strong>. A medida que aumentamos <code>N</code> hacia el infinito, esa distribución se reduce a 0. Lo que significa que, cuando <code>N</code> es infinito, el azar <strong>nunca produce diferencias</strong>. Podemos usar esto a nuestro favor.</p>
<p>Por ejemplo, podríamos correr nuestro experimento con 20 sujetos por grupo. O podríamos decidir invertir más tiempo y correrlo con 40 sujetos por grupo, o 80, o 150. Cuando vos sos quien ejecuta el experimento, <strong>vos decidís el diseño</strong>. Y esas decisiones importan muchísimo. Básicamente, <strong>cuantos más sujetos tenés, más sensible es tu experimento</strong>. Con un <code>N</code> más grande, vas a poder detectar de manera confiable diferencias de medias más pequeñas, y podés concluir con confianza que esas diferencias <strong>no fueron producidas por azar</strong>.</p>
<p>Fijate en los histogramas de <a href="#fig-5sampleDistNormal" class="quarto-xref">Figura&nbsp;<span>6.20</span></a> . Es la misma simulación de antes, pero con cuatro tamaños muestrales distintos: 20, 40, 80, 160. Vamos duplicando el tamaño muestral en cada simulación, solo para ver qué pasa con el <strong>ancho de la ventana del azar</strong>.</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5sampleDistNormal_126ac39d3231637ae6f916ca1ddd660c">
<div class="cell-output-display">
<div id="fig-5sampleDistNormal" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5sampleDistNormal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-Foundation_Inference_files/figure-html/fig-5sampleDistNormal-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5sampleDistNormal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.20: El rango (o ancho) de las diferencias producidas por azar se reduce a medida que aumenta el tamaño muestral.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Ahí lo tenés. La <strong>distribución muestral de las diferencias de medias</strong> se contrae hacia 0 a medida que aumenta el tamaño muestral. Esto significa que, si ejecutás un experimento con un tamaño muestral mayor, vas a poder detectar diferencias de medias más pequeñas, y estar seguro de que <strong>no se deben al azar</strong>.</p>
<p>La <a href="#tbl-5minmax" class="quarto-xref">Tabla&nbsp;<span>6.2</span></a> muestra los valores mínimos y máximos que el azar produjo para cada uno de los cuatro tamaños muestrales:</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/tbl-5minmax_d61f0bbc70c06ffb52597b7be7a50622">
<div id="tbl-5minmax" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-hash="05-Foundation_Inference_cache/html/tbl-5minmax_d61f0bbc70c06ffb52597b7be7a50622">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-5minmax-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;6.2: La diferencia de medias más pequeña y más grande producida por azar en función del tamaño muestral.
</figcaption>
<div aria-describedby="tbl-5minmax-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">Tamaño de muestra</th>
<th style="text-align: center;">menor</th>
<th style="text-align: center;">mayor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">20</td>
<td style="text-align: center;">-21.46</td>
<td style="text-align: center;">23.53</td>
</tr>
<tr class="even">
<td style="text-align: center;">40</td>
<td style="text-align: center;">-15.71</td>
<td style="text-align: center;">15.59</td>
</tr>
<tr class="odd">
<td style="text-align: center;">80</td>
<td style="text-align: center;">-13.51</td>
<td style="text-align: center;">10.82</td>
</tr>
<tr class="even">
<td style="text-align: center;">160</td>
<td style="text-align: center;">-8.03</td>
<td style="text-align: center;">7.48</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>La tabla muestra que el rango de comportamiento del azar es <strong>mucho más amplio para tamaños muestrales pequeños</strong>, y <strong>más estrecho para tamaños muestrales grandes</strong>. Pensá en lo que implica ese estrechamiento para el diseño de tu experimento. Por ejemplo, un aspecto del diseño es la elección del tamaño muestral, <code>N</code> —o, en un experimento de psicología, la cantidad de participantes. Si resulta que tu manipulación va a causar una diferencia de +11, ¿qué deberías hacer? ¿Ejecutar un experimento con <code>N = 20</code> personas? Espero que no. Si lo hicieras, podrías obtener una diferencia de medias de +11 <strong>bastante seguido solo por azar</strong>.</p>
<p>Sin embargo, si ejecutarás el experimento con <strong>160 personas</strong>, entonces sí podrías decir con seguridad que <strong>+11 no fue causado por azar</strong>, estaría fuera del rango de lo que el azar puede producir. Incluso podrías considerar correr el experimento con <strong>80 participantes</strong>. Una diferencia de +11 ahí <strong>no ocurriría muy seguido por azar</strong>, y además serías más eficiente en términos de tiempo y recursos.</p>
<p>El punto es: <strong>el diseño del experimento determina el tamaño de los efectos que puede detectar.</strong> Si querés detectar un efecto pequeño, <strong>aumentá el tamaño muestral</strong>.</p>
<p>Es importante aclarar que <strong>esto no es lo único que podés hacer</strong>. También podés <strong>aumentar el tamaño de cada celda</strong>. Por ejemplo, muchas veces tomamos varias mediciones de un solo sujeto. Cuantas más mediciones tomás (es decir, mayor tamaño de celda), más estable es tu estimación de la media del sujeto. Vamos a hablar más de estas cuestiones más adelante. También podés intentar aplicar una manipulación <strong>más fuerte</strong>, cuando sea posible.</p>
</section>
<section id="parte-5-yo-tengo-el-poder" class="level3" data-number="6.5.7">
<h3 data-number="6.5.7" class="anchored" data-anchor-id="parte-5-yo-tengo-el-poder"><span class="header-section-number">6.5.7</span> Parte 5: Yo tengo el poder</h3>
<blockquote class="blockquote">
<p>Por el poder de Grayskull… ¡YO TENGO EL PODER! – He-Man</p>
</blockquote>
<p>El último tema de esta sección se llama <strong>poder</strong>. Más adelante vamos a definirlo con ideas estadísticas más específicas. Acá solo vamos a hablar de la idea general. Y vamos a mostrar cómo asegurarte de que <strong>tu diseño tenga un poder del 100%</strong>. Porque, ¿por qué ejecutar un diseño que no tenga poder?</p>
<p>La gran idea detrás del poder es el concepto de <strong>sensibilidad</strong>. El concepto de sensibilidad parte de la suposición de que <strong>hay algo a lo que ser sensible</strong>.</p>
<p>Es decir, <strong>existe una diferencia real</strong> que puede ser medida. Entonces, la pregunta es: <strong>¿cuán sensible es tu experimento?</strong> Ya vimos que <strong>el número de sujetos (tamaño muestral)</strong> cambia la sensibilidad del diseño. Más sujetos = más sensibilidad para detectar efectos más pequeños.</p>
<p>Veamos un gráfico más. Lo que vamos a hacer es simular una medida de sensibilidad para <strong>un conjunto de tamaños muestrales</strong>, desde 10 hasta 300. Lo haremos en incrementos de 10. Para cada simulación, vamos a calcular las diferencias de medias como lo hicimos antes. Pero, en lugar de mostrar el histograma, simplemente vamos a calcular <strong>el valor mínimo y el máximo</strong>. Esto es una buena medida del alcance extremo del azar. Luego vamos a graficar esos valores en función del tamaño muestral y ver qué obtenemos.</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5crumpminmax_49dca067c224c3bf72d7b06901a7858e">
<div class="cell-output-display">
<div id="fig-5crumpminmax" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5crumpminmax-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-Foundation_Inference_files/figure-html/fig-5crumpminmax-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5crumpminmax-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.21: Gráfico del máximo y mínimo de las diferencias de medias producidas por azar en función del tamaño muestral. El rango se reduce a medida que el tamaño muestral aumenta, mostrando que el azar por sí solo produce un rango más pequeño de diferencias cuando el tamaño muestral es mayor.
</figcaption>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-5crumpminmax" class="quarto-xref">Figura&nbsp;<span>6.21</span></a> muestra una ventana de sensibilidad razonablemente precisa en función del tamaño muestral. Para cada tamaño muestral, podemos ver la diferencia máxima que el azar produjo y la mínima. En esas simulaciones, <strong>el azar nunca produjo diferencias mayores ni menores</strong> que esos valores extremos. Así que cada diseño es sensible a cualquier diferencia que esté <strong>por debajo de la línea inferior o por encima de la línea superior</strong>.</p>
<p>Otra forma de decirlo es la siguiente: ¿Cuáles de los tamaños muestrales son sensibles a una diferencia de +10 o -10? Es decir, si se observa una diferencia de +10 o -10, entonces podríamos decir con mucha confianza que <strong>esa diferencia no fue causada por azar</strong>, porque según estas simulaciones, el azar <strong>nunca</strong> produjo diferencias tan grandes. Para ayudarnos a ver cuáles son sensibles, la <a href="#fig-5crumpredline" class="quarto-xref">Figura&nbsp;<span>6.22</span></a> traza líneas horizontales en -10 y +10:</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5crumpredline_d8409a80f3a3c10c4908055c31104e5a">
<div class="cell-output-display">
<div id="fig-5crumpredline" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5crumpredline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-Foundation_Inference_files/figure-html/fig-5crumpredline-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5crumpredline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.22: La línea roja representa el tamaño de una diferencia de medias que un investigador podría estar interesado en detectar. Todos los puntos que están por fuera (por encima o por debajo) de la línea roja representan diseños con tamaños muestrales pequeños. Cuando ocurre una diferencia de 10 en esos diseños, podemos descartar con confianza que haya sido causada por azar. Los puntos entre las líneas rojas representan diseños con tamaños muestrales grandes. Estos diseños nunca producen diferencias tan grandes como 10, así que cuando ocurren, podemos confiar en que no fueron producto del azar.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Según una estimación visual aproximada, los diseños con tamaño muestral <strong>mayor o igual a 100</strong> son todos sensibles a diferencias reales de 10. Los diseños con tamaño muestral <strong>mayor a 100</strong> nunca produjeron diferencias extremas fuera de las líneas rojas <strong>solo por azar</strong>. Si se usaran esos diseños, y se observara un efecto de 10 o más, entonces podríamos tener confianza en que <strong>el azar no produjo ese efecto</strong>. Diseñar tu experimento de modo que sepas que <strong>es sensible a lo que estás buscando detectar</strong> es la gran idea detrás del <strong>poder estadístico</strong>.</p>
</section>
<section id="resumen-de-la-prueba-de-crump" class="level3" data-number="6.5.8">
<h3 data-number="6.5.8" class="anchored" data-anchor-id="resumen-de-la-prueba-de-crump"><span class="header-section-number">6.5.8</span> Resumen de la prueba de Crump</h3>
<p>¿Qué aprendimos con esta supuesta “prueba de Crump falsa” que nadie usa? Bueno, aprendimos lo básico de lo que estaremos haciendo de ahora en más. Y lo hicimos <strong>sin matemática difícil ni fórmulas</strong>.</p>
<p>Muestreamos números, calculamos medias, restamos las medias entre condiciones experimentales, luego repetimos ese proceso muchas veces, contamos las diferencias de medias y las pusimos en un histograma. Eso nos mostró <strong>lo que puede hacer el azar en un experimento</strong>. Después, discutimos cómo tomar decisiones en torno a esos hechos. Y mostramos cómo podemos <strong>controlar el papel del azar</strong> simplemente cambiando cosas como el tamaño muestral.</p>
</section>
</section>
<section id="la-prueba-de-aleatorización-o-prueba-de-permutación" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="la-prueba-de-aleatorización-o-prueba-de-permutación"><span class="header-section-number">6.6</span> La prueba de aleatorización (o prueba de permutación)</h2>
<p>Bienvenidos a la <strong>primera estadística inferencial oficial</strong> de este libro. Hasta ahora estuvimos construyendo algunas intuiciones. A continuación, vamos a ser un poco más formales y mostrar cómo podemos usar el azar para decirnos si nuestro resultado experimental <strong>probablemente fue causado por el azar o no</strong>. Hacemos esto con algo llamado una <strong>prueba de aleatorización</strong>. Las ideas detrás de la prueba de aleatorización son <strong>las mismas ideas</strong> que están detrás del resto de las estadísticas inferenciales que vamos a discutir en los capítulos siguientes. Y —sorpresa— ya hemos hablado de <strong>todas las ideas principales</strong>. Ahora, simplemente las vamos a reunir, y darles el nombre de <strong>prueba de aleatorización</strong>.</p>
<p>Acá va la idea principal. Cuando ejecutás un experimento y recolectás algunos datos, podés descubrir <strong>qué pasó esa única vez</strong>. Pero, como ejecutaste el experimento solo una vez, <strong>no podés saber qué podría haber pasado</strong>. La prueba de aleatorización es una forma de averiguar <strong>qué podría haber pasado</strong>. Y, una vez que sabés eso, podés comparar <strong>lo que pasó</strong> en tu experimento con <strong>lo que podría haber pasado</strong>.</p>
<section id="ejemplo-ficticio-masticar-chicle-mejora-tus-calificaciones" class="level3" data-number="6.6.1">
<h3 data-number="6.6.1" class="anchored" data-anchor-id="ejemplo-ficticio-masticar-chicle-mejora-tus-calificaciones"><span class="header-section-number">6.6.1</span> Ejemplo ficticio: ¿masticar chicle mejora tus calificaciones?</h3>
<p>Supongamos que ejecutás un experimento para saber si masticar chicle hace que los estudiantes obtengan mejores notas en un examen de estadística. Asignás al azar a 20 estudiantes a la condición “con chicle”, y a otros 20 estudiantes a la condición “sin chicle”. Después, les tomás un examen de estadística a todos y medís sus notas. Si masticar chicle causa mejores calificaciones, entonces el grupo con chicle debería tener, en promedio, <strong>notas más altas</strong> que el grupo sin chicle.</p>
<p>Digamos que los datos lucen así:</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/unnamed-chunk-5_dfe4210e8732c96c6c1b055719a58a09">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">estudiante</th>
<th style="text-align: left;">chicle</th>
<th style="text-align: left;">no_chicle</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">95</td>
<td style="text-align: left;">87</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">87</td>
<td style="text-align: left;">61</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">98</td>
<td style="text-align: left;">74</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">79</td>
<td style="text-align: left;">82</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">85</td>
<td style="text-align: left;">66</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">98</td>
<td style="text-align: left;">67</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">97</td>
<td style="text-align: left;">83</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">90</td>
<td style="text-align: left;">66</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;">76</td>
<td style="text-align: left;">44</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">96</td>
<td style="text-align: left;">45</td>
</tr>
<tr class="odd">
<td style="text-align: left;">11</td>
<td style="text-align: left;">74</td>
<td style="text-align: left;">60</td>
</tr>
<tr class="even">
<td style="text-align: left;">12</td>
<td style="text-align: left;">84</td>
<td style="text-align: left;">71</td>
</tr>
<tr class="odd">
<td style="text-align: left;">13</td>
<td style="text-align: left;">85</td>
<td style="text-align: left;">86</td>
</tr>
<tr class="even">
<td style="text-align: left;">14</td>
<td style="text-align: left;">73</td>
<td style="text-align: left;">86</td>
</tr>
<tr class="odd">
<td style="text-align: left;">15</td>
<td style="text-align: left;">95</td>
<td style="text-align: left;">59</td>
</tr>
<tr class="even">
<td style="text-align: left;">16</td>
<td style="text-align: left;">74</td>
<td style="text-align: left;">78</td>
</tr>
<tr class="odd">
<td style="text-align: left;">17</td>
<td style="text-align: left;">95</td>
<td style="text-align: left;">87</td>
</tr>
<tr class="even">
<td style="text-align: left;">18</td>
<td style="text-align: left;">91</td>
<td style="text-align: left;">61</td>
</tr>
<tr class="odd">
<td style="text-align: left;">19</td>
<td style="text-align: left;">74</td>
<td style="text-align: left;">84</td>
</tr>
<tr class="even">
<td style="text-align: left;">20</td>
<td style="text-align: left;">78</td>
<td style="text-align: left;">57</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sumas</td>
<td style="text-align: left;">1724</td>
<td style="text-align: left;">1404</td>
</tr>
<tr class="even">
<td style="text-align: left;">Medias</td>
<td style="text-align: left;">86.2</td>
<td style="text-align: left;">70.2</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Entonces, ¿los estudiantes que masticaron chicle tuvieron mejor desempeño que los que no lo hicieron? Mirá la fila de medias al final de la tabla. La media para los estudiantes que masticaron chicle fue 86.2, y la media para los estudiantes sin chicle fue 70.2. A simple vista, parece que masticar chicle <strong>funcionó</strong>.</p>
<p>“¡PAREN LAS ROTATIVAS, esto es ridículo!”. Ya sabemos que es ridículo porque estamos usando datos inventados. Pero, incluso si estos fueran datos reales, podrías pensar: “Eso del chicle no tiene sentido, esta diferencia podría haber sido causada por azar. Quizás los estudiantes más inteligentes cayeron por azar en el grupo con chicle, y por eso sus notas fueron más altas… el chicle en realidad no hizo nada…”. Estamos de acuerdo. Pero echemos un vistazo más de cerca. Ya sabemos cómo salieron los datos. Lo que queremos saber es <strong>cómo podrían haber salido</strong>. ¿Cuáles son todas las posibilidades?</p>
<p>Por ejemplo, los datos habrían salido un poco distintos si hubiéramos asignado a algunos estudiantes del grupo con chicle al grupo sin chicle, y viceversa. Pensá en todas las formas posibles de asignar a los 40 estudiantes en dos grupos; hay <strong>muchísimas maneras</strong>. Y las medias de cada grupo serían diferentes dependiendo de cómo se asignen los estudiantes.</p>
<p>En la práctica, no es posible ejecutar el experimento de todas esas formas posibles —eso llevaría demasiado tiempo. Pero <strong>sí podemos estimar cómo habrían salido todos esos experimentos</strong> usando simulación. Esta es la idea: Tomamos las 40 mediciones (las notas del examen) que obtuvimos para todos los estudiantes. Luego, seleccionamos aleatoriamente a 20 de ellas y fingimos que fueron del grupo con chicle, y las 20 restantes las asignamos al grupo sin chicle. Entonces, volvemos a calcular las medias para ver qué habría pasado. Y seguimos haciendo esto una y otra vez, cada vez calculando lo que habría pasado en esa versión alternativa del experimento.</p>
<section id="haciendo-la-aleatorización" class="level4" data-number="6.6.1.1">
<h4 data-number="6.6.1.1" class="anchored" data-anchor-id="haciendo-la-aleatorización"><span class="header-section-number">6.6.1.1</span> Haciendo la aleatorización</h4>
<p>Antes de hacer eso, vamos a mostrar cómo funciona la parte de la aleatorización. Usaremos menos números para que el proceso sea más fácil de visualizar. Acá están los primeros 5 puntajes de examen para los estudiantes en ambos grupos:</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/unnamed-chunk-6_80cd3e85a7c5b946693141655e841b76">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">estudiante</th>
<th style="text-align: left;">chicle</th>
<th style="text-align: left;">no_chicle</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">95</td>
<td style="text-align: left;">87</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">87</td>
<td style="text-align: left;">61</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">98</td>
<td style="text-align: left;">74</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">79</td>
<td style="text-align: left;">82</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">85</td>
<td style="text-align: left;">66</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">444</td>
<td style="text-align: left;">370</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">88.8</td>
<td style="text-align: left;">74</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Las cosas podrían haber salido diferente si algunos de los sujetos en el grupo con chicle hubieran sido intercambiados con sujetos del grupo sin chicle. Así es cómo podemos hacer un poco de aleatorización.</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/unnamed-chunk-7_215fa17f12eeeda57ac7b1db490711d4">
<pre><code>#&gt; [1] 79 74 66 82 61
#&gt; [1] 87 87 85 95 98</code></pre>
</div>
<p>Tomamos los primeros 5 números de los datos originales, y los pusimos todos en una variable llamada <code>all_scores</code>. Luego usamos la función <code>sample</code> en R para mezclar los puntajes. Finalmente, tomamos los primeros 5 puntajes mezclados y los guardamos en una nueva variable llamada <code>new_chicle</code>. Después, colocamos los últimos 5 puntajes en la variable <code>new_no_chicle</code>. Luego los imprimimos, así podemos verlos.</p>
<p>Si hacemos esto un par de veces y lo ponemos en una tabla, podemos ver que las medias para “con chicle” y “sin chicle” serían distintas si los sujetos se asignaran al azar de otra forma. Fijate:</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/unnamed-chunk-8_0a31089fa8c4a4c5d4874cc8d3fc2709">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 16%">
<col style="width: 10%">
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 16%">
<col style="width: 12%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">estudiante</th>
<th style="text-align: left;">chicle</th>
<th style="text-align: left;">no_chicle</th>
<th style="text-align: left;">chicle2</th>
<th style="text-align: left;">no_chicle2</th>
<th style="text-align: left;">chicle3</th>
<th style="text-align: left;">no_chicle3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">95</td>
<td style="text-align: left;">87</td>
<td style="text-align: left;">87</td>
<td style="text-align: left;">61</td>
<td style="text-align: left;">82</td>
<td style="text-align: left;">85</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">87</td>
<td style="text-align: left;">61</td>
<td style="text-align: left;">74</td>
<td style="text-align: left;">66</td>
<td style="text-align: left;">61</td>
<td style="text-align: left;">95</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">98</td>
<td style="text-align: left;">74</td>
<td style="text-align: left;">82</td>
<td style="text-align: left;">98</td>
<td style="text-align: left;">87</td>
<td style="text-align: left;">79</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">79</td>
<td style="text-align: left;">82</td>
<td style="text-align: left;">85</td>
<td style="text-align: left;">79</td>
<td style="text-align: left;">66</td>
<td style="text-align: left;">87</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">85</td>
<td style="text-align: left;">66</td>
<td style="text-align: left;">87</td>
<td style="text-align: left;">95</td>
<td style="text-align: left;">98</td>
<td style="text-align: left;">74</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sumas</td>
<td style="text-align: left;">444</td>
<td style="text-align: left;">370</td>
<td style="text-align: left;">415</td>
<td style="text-align: left;">399</td>
<td style="text-align: left;">394</td>
<td style="text-align: left;">420</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Medias</td>
<td style="text-align: left;">88.8</td>
<td style="text-align: left;">74</td>
<td style="text-align: left;">83</td>
<td style="text-align: left;">79.8</td>
<td style="text-align: left;">78.8</td>
<td style="text-align: left;">84</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="simulando-las-diferencias-de-medias-en-distintas-aleatorizaciones" class="level4" data-number="6.6.1.2">
<h4 data-number="6.6.1.2" class="anchored" data-anchor-id="simulando-las-diferencias-de-medias-en-distintas-aleatorizaciones"><span class="header-section-number">6.6.1.2</span> Simulando las diferencias de medias en distintas aleatorizaciones</h4>
<p>En nuestro experimento ficticio encontramos que la media para los estudiantes que masticaron chicle fue 86.2, y la media para los que no lo hicieron fue 70.2. La diferencia de medias (chicle – sin chicle) fue 16. Esa es una diferencia bastante grande. Eso es <strong>lo que pasó</strong>. Pero, <strong>¿qué podría haber pasado</strong>? Si probáramos todos los experimentos posibles en los que los sujetos se asignan de forma diferente, ¿cómo luciría la distribución de las posibles diferencias de medias?</p>
<p>Vamos a averiguarlo. De eso se trata exactamente la prueba de aleatorización. Cuando hacemos nuestra prueba de aleatorización, vamos a medir la diferencia de medias en los puntajes del examen entre el grupo con chicle y el grupo sin chicle. Cada vez que hagamos una aleatorización, guardaremos la diferencia de medias.</p>
<p>Veamos una pequeña animación de lo que ocurre durante la prueba de aleatorización. La <a href="#fig-5randtest" class="quarto-xref">Figura&nbsp;<span>6.23</span></a> muestra datos de otro experimento ficticio, pero los principios son los mismos. Después volveremos al experimento del chicle.</p>
<p>La animación muestra tres cosas importantes: Primero, los puntos púrpuras muestran las medias de los puntajes en dos grupos (no estudió vs.&nbsp;estudió). Parece que hay una diferencia, ya que un punto está más bajo que el otro. Queremos saber si <strong>el azar podría producir una diferencia tan grande</strong>.</p>
<p>Al comienzo de la animación, los puntos verde claro y rojo muestran los puntajes individuales de cada uno de los 10 sujetos en el diseño (los puntos púrpura son las medias de estos puntajes originales). Luego, durante las aleatorizaciones, mezclamos aleatoriamente los puntajes originales entre los grupos. Podés ver esto ocurriendo a lo largo de la animación, mientras los puntos verde y rojo aparecen en diferentes combinaciones aleatorias. Los puntos amarillos en movimiento te muestran las <strong>nuevas medias para cada grupo después de la aleatorización</strong>. Las diferencias entre los puntos amarillos te muestran el <strong>rango de diferencias que el azar podría producir</strong>.</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5randtest_7ed97a7079ad7c274f06b97927925d4d">
<div class="cell-output-display">
<div id="fig-5randtest" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5randtest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="imgs/gifs/randomizationTest-1_es.gif" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5randtest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.23: Animación de una prueba de aleatorización. Los puntos púrpura representan la ubicación de las medias originales en cada condición. Los puntos amarillos representan las medias de cada muestra aleatorizada. Los puntos azules y rojos muestran cómo los puntajes originales son redistribuidos al azar en cada aleatorización.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Estamos haciendo una inferencia estadística <strong>visual</strong>. Al observar el rango de movimiento de los puntos amarillos, estamos viendo qué tipo de diferencias puede producir el azar. En esta animación, los puntos púrpura —que representan la diferencia original— están generalmente <strong>fuera del rango del azar</strong>. Los puntos amarillos <strong>no se mueven más allá</strong> de los puntos púrpura, así que el azar parece ser una explicación poco probable de la diferencia.</p>
<p>Si los puntos púrpura estuvieran <strong>dentro del rango de los puntos amarillos</strong>, entonces sabríamos que el azar <strong>es capaz de producir</strong> la diferencia que observamos, y que lo hace <strong>con bastante frecuencia</strong>. En ese caso, <strong>no deberíamos concluir</strong> que la manipulación causó la diferencia, porque <strong>podría haber ocurrido fácilmente por azar</strong>.</p>
<p>Volvamos al ejemplo del chicle. Después de aleatorizar nuestras notas muchas veces, y de calcular las nuevas medias y las diferencias de medias, vamos a tener <strong>un montón de diferencias</strong> para observar, que podemos representar en un histograma. Ese histograma da una imagen de <strong>lo que podría haber pasado</strong>. Luego, podemos comparar <strong>lo que pasó realmente</strong> con <strong>lo que podría haber pasado</strong>.</p>
<p>Este es el histograma de las diferencias de medias obtenidas con la prueba de aleatorización. Para esta simulación, aleatorizamos los resultados del experimento original 1000 veces. Esto es lo que <strong>podría haber pasado</strong>. La línea azul en la <a href="#fig-5randhist" class="quarto-xref">Figura&nbsp;<span>6.24</span></a> muestra <strong>dónde se ubica la diferencia observada</strong> sobre el eje x.</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5randhist_e12a2079e3c4aef0de44ce3fa682a25f">
<div class="cell-output-display">
<div id="fig-5randhist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5randhist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-Foundation_Inference_files/figure-html/fig-5randhist-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5randhist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.24: Histograma de diferencias de medias simuladas en una prueba de aleatorización
</figcaption>
</figure>
</div>
</div>
</div>
<p>¿Qué pensás? ¿Podría la diferencia representada por la línea azul haber sido causada por azar? Mi respuesta es: probablemente no. El histograma nos muestra la ventana del azar. La línea azul <strong>no está dentro de esa ventana</strong>. Esto significa que podemos estar bastante seguros de que <strong>la diferencia que observamos no se debe al azar</strong>.</p>
<p>Estamos mirando otra ventana del azar. Estamos viendo un histograma de los tipos de diferencias de medias que podrían haber ocurrido en nuestro experimento, si hubiéramos asignado a los sujetos al grupo con chicle y al grupo sin chicle de otra forma.</p>
<p>Como podés ver, las diferencias de medias varían de negativas a positivas. La diferencia más frecuente es 0. Además, la distribución parece simétrica en torno al cero, lo que muestra que teníamos aproximadamente las mismas probabilidades de obtener una diferencia positiva o negativa. También notá que a medida que las diferencias se hacen más grandes (ya sea en dirección positiva o negativa), <strong>se vuelven menos frecuentes</strong>. La línea azul nos muestra <strong>la diferencia observada</strong>, la que encontramos en nuestro experimento inventado. ¿Dónde está? Muy a la derecha. Está <strong>bien fuera del histograma</strong>. En otras palabras, cuando miramos <strong>lo que podría haber pasado</strong>, vemos que <strong>lo que pasó realmente</strong> no ocurre muy seguido.</p>
<p><strong>IMPORTANTE:</strong> En este caso, cuando hablamos de <strong>lo que podría haber pasado</strong>, nos referimos a lo que <strong>podría haber pasado por azar</strong>. Cuando comparamos lo que pasó con lo que el azar podría haber producido, podemos tener una mejor idea de si nuestro resultado fue o no <strong>causado por azar</strong>.</p>
<p>OK, ahora vamos a fingir que obtuvimos una diferencia de medias <strong>mucho más pequeña</strong> cuando ejecutamos el experimento. Podemos trazar nuevas líneas (azul y roja) para representar una media más pequeña que podríamos haber encontrado.</p>
<div class="cell" data-hash="05-Foundation_Inference_cache/html/fig-5randquestion_7431ea7746509117ffcbb1d630f9e82c">
<div class="cell-output-display">
<div id="fig-5randquestion" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5randquestion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-Foundation_Inference_files/figure-html/fig-5randquestion-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5randquestion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.25: ¿Esperarías que una diferencia de medias representada por la línea azul ocurra más o menos seguido por azar, en comparación con la diferencia representada por la línea roja?
</figcaption>
</figure>
</div>
</div>
</div>
<p>Fijate en la línea azul de la <a href="#fig-5randquestion" class="quarto-xref">Figura&nbsp;<span>6.25</span></a>. Si encontraras una diferencia de medias de 10, ¿te convencería de que esa diferencia <strong>no fue causada por azar</strong>? Como podés ver, la línea azul <strong>está dentro de la ventana del azar</strong>. Aunque las diferencias de +10 <strong>no ocurren muy seguido</strong>, podrías inferir que <strong>probablemente no fueron causadas por azar</strong> (pero tal vez te mantendrías algo escéptico, porque <strong>sí podrían haberlo sido</strong>).</p>
<p>¿Y qué pasa con la línea roja? La línea roja representa una diferencia de +5. Si encontraras una diferencia de +5 acá, ¿estarías seguro de que <strong>no fue causada por azar</strong>? Yo no lo estaría. La línea roja está completamente dentro de la ventana del azar —<strong>este tipo de diferencia ocurre con bastante frecuencia</strong>. Necesitaría <strong>más evidencia</strong> para considerar la afirmación de que alguna variable independiente realmente <strong>causó la diferencia</strong>. Me sentiría mucho más cómodo asumiendo que la diferencia fue probablemente <strong>causada por error muestral</strong>.</p>
</section>
</section>
<section id="lo-que-nos-queda-hasta-ahora" class="level3" data-number="6.6.2">
<h3 data-number="6.6.2" class="anchored" data-anchor-id="lo-que-nos-queda-hasta-ahora"><span class="header-section-number">6.6.2</span> Lo que nos queda hasta ahora</h3>
<p>¿Notaste que hasta ahora <strong>no usamos ninguna fórmula</strong>, pero aun así pudimos hacer estadística inferencial? Veremos algunas fórmulas más adelante, pero <strong>las ideas detrás de esas fórmulas son más importantes que las fórmulas mismas</strong>.</p>
<p>La estadística inferencial es un intento de resolver el problema: <strong>¿De dónde provienen mis datos?</strong> En el ejemplo de la prueba de aleatorización, nuestra pregunta fue: <strong>¿De dónde provienen las diferencias entre las medias de mis datos?</strong></p>
<p>Sabemos que esas diferencias <strong>podrían haber sido producidas solo por azar</strong>. Simulamos lo que puede hacer el azar usando aleatorización. Luego trazamos lo que puede hacer el azar usando un histograma. Y después usamos esa imagen para ayudarnos a hacer una inferencia: ¿La diferencia observada <strong>proviene de la distribución del azar, o no</strong>?</p>
<p>Cuando la diferencia observada está claramente dentro de la distribución del azar, entonces podemos inferir que nuestra diferencia <strong>podría haber sido producida por azar</strong>. Cuando la diferencia observada <strong>no está claramente dentro</strong> de la distribución del azar, entonces podemos inferir que nuestra diferencia <strong>probablemente no fue producida por azar</strong>.</p>
<p>En mi opinión, estas imágenes son muy, muy útiles. Si uno de nuestros objetivos es ayudarnos a resumir un montón de números complicados para llegar a una inferencia, entonces <strong>las imágenes hacen un excelente trabajo</strong>. Ni siquiera necesitamos un número resumen: solo necesitamos mirar la imagen y ver si la diferencia observada está <strong>dentro o fuera de la ventana del azar</strong>. <strong>De eso se trata todo esto.</strong> Crear formas <strong>intuitivas y significativas</strong> de hacer inferencias a partir de nuestros datos. A medida que avancemos, lo principal que haremos será <strong>formalizar nuestro proceso</strong> y hablar más sobre las estadísticas inferenciales “estándar”.</p>
<p>Por ejemplo, en lugar de mirar una imagen (aunque eso es algo útil), vamos a construir <strong>algunos números útiles</strong>. Por ejemplo: ¿y si quisieras saber <strong>cuál es la probabilidad de que tu diferencia haya sido producida por azar</strong>? Esa podría ser un número único, como el 95%. Si hubiera una probabilidad del 95% de que el azar pueda producir la diferencia que observaste, tal vez no estés muy confiado de que tu manipulación experimental fue la causa. Si hubiera solo un 1% de probabilidad de que el azar pueda producir esa diferencia, entonces podrías tener más confianza en que el <strong>azar no produjo la diferencia</strong>; y podrías, en cambio, estar cómodo con la posibilidad de que <strong>tu manipulación experimental fue realmente la causa</strong>.</p>
<p>Entonces, ¿cómo podemos llegar a esos números? Para llegar a eso, vamos a presentarte algunas herramientas <strong>más fundamentales</strong> para la inferencia estadística.</p>
<hr>
</section>
</section>
<section id="videos" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="videos"><span class="header-section-number">6.7</span> Videos</h2>
<section id="hipótesis-nula-y-alternativa" class="level3" data-number="6.7.1">
<h3 data-number="6.7.1" class="anchored" data-anchor-id="hipótesis-nula-y-alternativa"><span class="header-section-number">6.7.1</span> Hipótesis nula y alternativa</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/gJ38qX0ihPc" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>
</section>
<section id="tipos-de-errores" class="level3" data-number="6.7.2">
<h3 data-number="6.7.2" class="anchored" data-anchor-id="tipos-de-errores"><span class="header-section-number">6.7.2</span> Tipos de Errores</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/zhhDCFPzlkw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>
<p>:::::</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/almadana\.github\.io\/libro_cuanti\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./04-SamplesPopulations.html" class="pagination-link" aria-label="Probabilidad, muestreo y estimación">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Probabilidad, muestreo y estimación</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./06-ttests.html" class="pagination-link" aria-label="Pruebas t">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Pruebas t</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/almadana/libro_cuanti/edit/master/05-Foundation_Inference.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li></ul></div></div></div></footer></body></html>